### ISSUE TITLE
Update .github/ISSUE_TEMPLATE/bug_report.yaml

### ISSUE THREAD

**Issue by dtomvan** [25huizengek1/ViTune#107]
In-reply-to:
> Can't reproduce unfortunately. Do you have any logs or other context to this? A few things come to mind:
>
> - What device are you using? Does it run an official (Google or vendor) Android build?
> - What kind of bluetooth device are you using?
> - Are you using a release build or nightly?
> - Can you provide a screen recording of the issues you are experiencing?
> - Could you please try this with today's (will be released in less than an hour) nightly build?
>
> Thank you in advance. I'll try and get back with you while I investigate.

_Originally posted by @25huizengek1 in [#89](https://github.com/25huizengek1/ViMusic/issues/89#issuecomment-1908969787)_

---

I saw this comment and figured it would be a good idea to update the issue template incorporating some of these questions to reduce friction when reporting bugs in the future. Also some instruction (through an HTML comment) on reporting logs (through logfox, then a pastebin, such a workflow) could be nice. This would allow you to further streamline the bugsquashing. I would say with bug reports it's definitely quality over quantity.

**Comment by dtomvan** [comment]
Just a non-exhaustive list of what could be included based on previous experience with issue reporting on this repo, to hopefully provide some inspiration:
- A checklist (did you use the latest stable release etc.)
- What type of issue is this? (I believe GitHub can assign tags based on the answer to some dropdown in an issue template)
- What android version are you on?
- Which brand of device do you have?
- What model is it?
- Could you provide some logs? (with instructions on how to do that)
- Does this issue also appear in vfsfitvnm/ViMusic?
- If relevant, are you sure you are able to access YouTube music from your country/region/state?
- If relevant, could you provide a database export?

**Comment by 25huizengek1** [comment]
I think these are enough changes for now, please leave your suggestions here if you have any.

**Comment by dtomvan** [comment]
L134:
> This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

This seems ambiguous; it could either mean:
- The checkbox isn't checked: the issue isn't reproducible,
- The checkbox isn't checked: the issue might be reproducible, but I haven't tested it,
- The checkbox is checked: it's marked as "task" but it is optional, so I skipped this step en just marked it as completed,
- The checkbox is checked: the issue is reproducible.

**Comment by 25huizengek1** [comment]
You’re right, I’ve experienced this in the last few days so we’ll have to find a solution to this.

**Comment by 25huizengek1** [comment]
I just changed the template, at least for now (I'll finish the template when I'm finally migrating to 'ViTune')

I guess we can close again?
