### ISSUE TITLE
Playlist sorting is still broken 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#127]
### Steps to reproduce the bug

1. Open a local playlist
2. Try to move a song from top to bottom of the list (works best with 20+ songs added to the playlist)

### Expected behavior

1. The song should stick to the new position 

### Actual behavior

1. Either the song just disappears midway during sorting, so you don't actually know where the song will go
2. It doesn't get sorted at all i.e position it reverts to initial state 

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/140274753/9c91f4af-45c0-491b-8be6-3f3b1d7085d2

### ViMusic version

v0.6.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Tecno spark go (2021) running on HiOS

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
Thank you for reporting your concerns. Unfortunately, this is not considered a bug as the song gets placed in the position of your finger, even though the overscrolling behavior could cause confusion because of the (and I agree it looks a bit weird right now) visual feedback. I guess I can correct this by changing the offset of the reordered list element, but I'm not entirely sure what looks best.

**Comment by genericbetatester** [comment]
> Thank you for reporting your concerns. Unfortunately, this is not considered a bug as the song gets placed in the position of your finger, even though the overscrolling behavior could cause confusion because of the (and I agree it looks a bit weird right now) visual feedback. I guess I can correct this by changing the offset of the reordered list element, but I'm not entirely sure what looks best.

Hello, I haven't had time to check here for some weeks.

I don't think you understand what my complaints are, the first issue is minor but the second one is really disturbing. 

The song doesn't stay where you put it. It revert to initial position or just place itself randomly.

I'm surprised you said it's not considered a bug even though it was shown clearly in the video that the song doesn't stay where you put it. I don't think that works correctly.

P.S I'm on the latest version of the app.

**Comment by genericbetatester** [comment]
> > Thank you for reporting your concerns. Unfortunately, this is not considered a bug as the song gets placed in the position of your finger, even though the overscrolling behavior could cause confusion because of the (and I agree it looks a bit weird right now) visual feedback. I guess I can correct this by changing the offset of the reordered list element, but I'm not entirely sure what looks best.
> 
> Hello, I haven't had time to check here for some weeks.
> 
> I don't think you understand what my complaints are, the first issue is minor but the second one is really disturbing.
> 
> The song doesn't stay where you put it. It revert to initial position or just place itself randomly.
> 
> I'm surprised you said it's not considered a bug even though it was shown clearly in the video that the song doesn't stay where you put it. I don't think that works correctly.
> 
> P.S I'm on the latest version of the app.

@25huizengek1

**Comment by 25huizengek1** [comment]
I'll look into this later.

**Comment by genericbetatester** [comment]
> Cannot reproduce. Can you try the latest nightly build, see if this still persists?

Okay

**Comment by genericbetatester** [comment]
@25huizengek1 can you please provide the nightly version for testing

**Comment by 25huizengek1** [comment]
Forgot to reschedule nightly builds. @genericbetatester 

I'll schedule new builds for tonight.

**Comment by genericbetatester** [comment]
> Forgot to reschedule nightly builds. @genericbetatester
> 
> I'll schedule new builds for tonight.

Okay I'll be expecting it. I have a question; is there anyway to download the nightly version here on GitHub

**Comment by 25huizengek1** [comment]
Of course ==> https://github.com/25huizengek1/fdroid-repo/tree/master/fdroid/repo

**Comment by genericbetatester** [comment]
I've tested it, sorting is still messed up, I've attached a video

https://github.com/25huizengek1/ViTune/assets/140274753/5edce1c5-dc39-43aa-bb03-e866d1b75056

**Comment by 25huizengek1** [comment]
Once more, I still can't reproduce this, very weird...

**Comment by genericbetatester** [comment]
> Once more, I still can't reproduce this, very weird...

Indeed. So there is no solution?
