### ISSUE TITLE
Swipe behaviour on wavy seekbar

### ISSUE THREAD

**Issue by NeeRaj-2401** [25huizengek1/ViTune#138]
### Steps to reproduce the bug

1. Enable modern player layout
2. Play a song
3. Swipe up on player ( irrespective of seekbar position)

### Expected behavior

The wavy seekbar should show the song duration information & seekbar status without moving the seek position

### Actual behavior

The seek position is moved to the point from where the swipe up is performed , irrespective of actual status

### ViMusic version

v0.6.5 +

### What kind of build are you using?

Nightly (F-Droid)

### Android version

12

### Device info

Device : Realme 7, 
Rom : Realme ui 3.0 ( based on Android 12 )

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
What do you mean exactly? I know the swipe up is a thing but this is certainly not a bug, just an inconvenience at most.

**Comment by NeeRaj-2401** [comment]
https://github.com/25huizengek1/ViTune/assets/88180887/9dd4bc14-df11-4a58-bdc5-097704ed2847


U can notice in the screen recording, that most of the time the seek position is misplaced irrespective of actual song duration played.
