### ISSUE TITLE
Some singles load endlessly

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#139]
### Steps to reproduce the bug

1.go to the artist page
2.go to Singles 
3. the loading of the singles does not stop

### Expected behavior

Strangely enough, this error does not occur with all artists

### Actual behavior

The singles should be loaded for all artists

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/103368536/57114e51-e1a4-4c69-bb9d-c043b1ca730b

### ViMusic version

0.6.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

Samsung Galaxy a21s

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
Very strange, it loads for me almost instantly. Can you please provide some logs? What language is your device using?

**Comment by siggi1984** [comment]
> Very strange, it loads for me almost instantly. Can you please provide some logs? What language is your device using?

Just wanted to create logs and realized that it now works. Maybe it was my cell phone. Sorry for the inconvenience and thanks for your effort. I'll close it again now.
