### ISSUE TITLE
Please swap the two buttons

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#140]
Please swap the two buttons, Siege screenshot. I've been wrong so many times when I wanted to listen to a song again, I've unliked it.

![Screenshot_20240302-085047_1](https://github.com/25huizengek1/ViTune/assets/103368536/20012423-b997-4e9f-b8c6-4d5c9c019ff0)

**Comment by SiddhantRakh** [comment]
I think this is a good change that should be made.I thought to open the same issue earlier. This makes more sense to me.

**Comment by 25huizengek1** [comment]
To keep a consistent design, I'll keep the previous button where it was when the like button is turned off. Will push this in a sec

**Comment by 25huizengek1** [comment]
It looks like this now:

<img src="https://github.com/25huizengek1/ViTune/assets/50515369/0a1b700e-7677-402e-b320-3fc7a80b7c50" width="30%" />

**Comment by siggi1984** [comment]
> It looks like this now:
> <img alt="" width="30%" src="https://private-user-images.githubusercontent.com/50515369/309487410-0a1b700e-7677-402e-b320-3fc7a80b7c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTc5MDQsIm5iZiI6MTcwOTM5NzYwNCwicGF0aCI6Ii81MDUxNTM2OS8zMDk0ODc0MTAtMGExYjcwMGUtNzY3Ny00MDJlLWIzMjAtM2ZjN2E4MGI3YzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE2NDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDBjM2U4MTBjNTkzOTUzZGMwNjdlOTkwZjNlMGFkMmU2YzEwNmQ2MWUxMmQ3YTViZmY4YmIyYjc0NDhhMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3rTfur09pyerJW5toq4sxHvYapAYeDYA3DZV4TNJDHQ">

Perfect, thank you
