### ISSUE TITLE
Backup cannot be restored in other forks

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#141]
### Steps to reproduce the bug

A backup that I have created with ViMusic/ViTune cannot be restored in other forks. It would be nice if this would work. Not because I want to switch or anything. Just in case (which I hope not) this project is no longer maintained for whatever reason, it would be easier to switch.

### Expected behavior

*

### Actual behavior

*

### ViMusic version

0.6.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 12

### Device info

Samsung Galaxy a21s

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
Not a bug, but also not possible: this entirely depends on how the other app handles Room's database backups, so I can't influence this at all.

**Comment by siggi1984** [comment]
> Not a bug, but also not possible: this entirely depends on how the other app handles Room's database backups, so I can't influence this at all.

Okay, but why can I restore the data backup from ViMusic, RiMusic, MusicYou (all forks of ViMusic) in Vitune, but the data backup from Vitune cannot be restored in the forks or in the original ViMusic? Just an informative question.
