### ISSUE TITLE
Material You AMOLED

### ISSUE THREAD

**Issue by jojobozo** [25huizengek1/ViTune#142]
Is it possible to add the feature to use AMOLED mode and Material You at the same time like in the app Obtainium for example:

<img alt="Screenshot of Obtainium" width="300" src="https://github.com/25huizengek1/ViTune/assets/51440893/6cdb879b-509a-433c-ada6-39aab4a0f8c2" />

**Comment by 25huizengek1** [comment]
I’ll look into this. Good suggestion.

**Comment by 25huizengek1** [comment]
Probably putting the theming on low priority for now, I'll post an update on this later.

**Comment by dtomvan** [comment]
I'll get on it, should be kindof simple.
