### ISSUE TITLE
Better Simplified Theme Settings

### ISSUE THREAD

**Issue by SiddhantRakh** [25huizengek1/ViTune#143]
I think there should only be 3 theme options for the app : 
Default
Dynamic
Material You
And under the theme option there should be a toggle for enabling Amoled Black Background like this : ![20240303_012119.jpg](https://github.com/25huizengek1/ViTune/assets/42494931/0dd806c1-cd9b-4068-954b-ca4d87e309aa)

**Comment by dtomvan** [comment]
If anything, a dup of #142

**Comment by SiddhantRakh** [comment]
> If anything, a dup of #142

Yes but this will greatly simplify the theme options rather than adding a new Amoled varient of each theme.

**Comment by SiddhantRakh** [comment]
> > If anything, a dup of #142
> 
> Yes but this cosmetic change will greatly simplify the theme options rather than adding a new Amoled varient of each theme.

**Comment by SiddhantRakh** [comment]
> > If anything, a dup of #142
> 
> Yes but this cosmetic change will greatly simplify the theme options rather than adding a new Amoled varient of each theme.

**Comment by SiddhantRakh** [comment]
Also PureBlack can be replaced by the 'default theme with Pure Black option turned on' in this new implementation.

**Comment by SiddhantRakh** [comment]
> That actually kind of makes sense. The way the theme selector is implemented right now doesn’t particularly allow this behavior but I’ll work something out.
Great. 👍

**Comment by 25huizengek1** [comment]
Continuing the conversation in #142
