### ISSUE TITLE
Bug system font not working 

### ISSUE THREAD

**Issue by JustRandomboy** [25huizengek1/ViTune#146]
### Steps to reproduce the bug

.

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/162049472/66f898f2-39a4-4682-b873-82ed55abfc20

### Logs

.

### ViMusic version

v0.6.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

14

### Device info

Poco f5 Indian varient 

### Additional information

.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [X] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by SiddhantRakh** [comment]
Same here. Even 'Apply Font Padding' is not working too. (ViMuisc v0.6.6)

**Comment by Syntax-Err5** [comment]
I think this is the same problem as #144, where changing the theme mode doesn't work. If you want a temporary workaround, just toggle the setting and restart the app (swipe it away in the app switcher).

**Comment by JustRandomboy** [comment]
Na bro tried all ready not working your is yours works ?

**Comment by Syntax-Err5** [comment]
Huh, I really don't know what's wrong then... 

https://github.com/25huizengek1/ViTune/assets/123362106/c4996493-2bc1-400b-88c2-a17082792a27

**Comment by Enigma1309** [comment]
i've also tested it and it is a problem with me too

**Comment by 25huizengek1** [comment]
I forgot the reactivity while refactoring, an embarrassing mistake…

> I think this is the same problem as https://github.com/25huizengek1/ViTune/issues/144, where changing the theme mode doesn't work. If you want a temporary workaround, just toggle the setting and restart the app (swipe it away in the app switcher).

Yes, it is, you can also rotate your screen to make it work.

**Comment by dtomvan** [comment]
Nah, not embarrassing at all, stuff happens. Just a shame that it got caught in the release, albeit still in zerover (I suppose for the full ViTune release we will go 1.0?). I'll try to bisect it this afternoon.

**Comment by dtomvan** [comment]
Got through with the bisect, reporting back soon here, then writing up a PR for the fix if I can get it fixed. Seems trivial enough though. For reference: [bisect-#144-2024-03-05.txt](https://github.com/25huizengek1/ViTune/files/14495671/bisect-.144-2024-03-05.txt)

**Comment by dtomvan** [comment]
After further investigation I found that this should have been fixed after some refactorings in cef2cd85646. Currently trying the latest commit on master as well as the aformentioned one. Since the appearance code has been changed a lot since the "culprit commit" I turned up with a couple of hours ago, we can disregard it...

**Comment by JustRandomboy** [comment]
So when it will be fixed in the upcoming update?

**Comment by dtomvan** [comment]
Yes, probably. Me and @25huizengek1 are still looking into it, but after the refactorings 1af04d2 seems to be the issue.
