### ISSUE TITLE
Increase padding between Artist and Duration labels

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViTune#149]
### Steps to reproduce the bug

- Open any tab/playlist/playing queue having long/multiple artist names
- The padding between the artist name and song duration is not enough for the separation of the latter labels.

### Expected behavior

There should be enough padding between the artist name and song duration labels,.

### Actual behavior

 There's no padding between the artist name and song duration labels.

### Screenshots/Screen recordings

![Screenshot_20240305-125444~2](https://github.com/25huizengek1/ViTune/assets/87353286/b3f70dbf-b5e8-4aff-ac69-47062368f342)
---
![Screenshot_20240305-125515~2](https://github.com/25huizengek1/ViTune/assets/87353286/1b71875e-f411-40ef-99f9-8c9dd925c87a)

### ViMusic version

0.6.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Motorola Moto G54 5G with stock Android

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
Not a bug, good suggestion though, will consider. Next time you can just fill out the suggestion form, because that one is more suitable for these issues.

**Comment by 25huizengek1** [comment]
Added 12 dp of padding between title and trailing content, as well as between the artists and the duration:

![image](https://github.com/25huizengek1/ViTune/assets/50515369/ba8ed640-ad79-47e5-aaf4-44f4d1fb3208)
