### ISSUE TITLE
Inconsistent Artist order

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViTune#150]
### Steps to reproduce the bug

- Play any song having more than one artist
- Notice the order of the Artists
- Switch to miniplayer (swipe down)
- The order of the Artists is different 

### Expected behavior

Artists label should be the same in both the views.

### Actual behavior

The order of the Artists label in Player UI and miniplayer is not consistent.

### Screenshots/Screen recordings

![Screenshot_20240305-125652](https://github.com/25huizengek1/ViTune/assets/87353286/2334b5dc-313a-44f3-84a6-3e93421347a4)
![Screenshot_20240305-125638](https://github.com/25huizengek1/ViTune/assets/87353286/4a29bf0c-9e90-433b-bb81-67f57dcbcd53)
![Screenshot_20240305-140511](https://github.com/25huizengek1/ViTune/assets/87353286/e4a91bd8-d72a-4dd1-b75b-0acf27fe8a81)
![Screenshot_20240305-140507](https://github.com/25huizengek1/ViTune/assets/87353286/5f28fb2f-7292-49ec-9d0a-def6890ef66f)

### ViMusic version

0.6.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Motorola Moto G54 5G running stock Android

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
Subtle, but I'll look into it. Not a bug though.

**Comment by dtomvan** [comment]
Yea, this just depends on how YTM supplies the song metadata, which could vary between songs. There are many "duplicates" between YT and YTM, so sometimes different metadata is supplied. We could keep it "consistent" by sorting alphabetically, I suppose.

**Comment by 25huizengek1** [comment]
Keeping it as it is right now, as sorting does not make sense. The entire app uses YouTube's notation by default, which is not consistent at all and cannot be sorted (it is not a list of artists but rather a string that indicates the artists, separated with all kinds of different separators: ',' / '&' / 'x' etc.). The player on the other hand shows clickable artist names in their own order when the artist info is available during playback.
