### ISSUE TITLE
Various proposals to improve the user experience

### ISSUE THREAD

**Issue by asxhelr657** [25huizengek1/ViTune#151]
I would love for there to be an option to download songs to internal storage, being able to customize various parameters like audio quality and format, and play them within the app without needing to use the song cache. I would also love for there to be more options to customize the app, for example, an option to choose the audio quality of songs, select the app's language, and more options to customize the user interface, such as choosing colors and having more font options.

I love the app. I recently discovered it and I love that it has the ViMusic user experience, but improved. I send my best wishes to the developers and hope they continue to improve this amazing app they are creating.

**Comment by 25huizengek1** [comment]
Thank you for your suggestions, appreciate it! I've provided some feedback on every suggestion below.

- Downloading songs: beyond the scope of a music streaming app, won't implement this for now.
- Audio quality: this would cause inconsistent caching behavior, ViTune uses the highest available quality by default
- Language: I think you can already select the language in app info, I'll look into this
- Colors: already possible, or do you want a separate color picker?
- Fonts: what fonts do you suggest? They have to be free to use.

Thank you for your appreciation! I try my best to improve the already great experience of ViMusic, while maintaining a stable user experience and codebase.

**Comment by 25huizengek1** [comment]
![Screenshot_20240314-234221.png](https://github.com/25huizengek1/ViTune/assets/50515369/949d6419-96e2-4760-823b-43f294a0054a)

Added a font picker. Don't worry, the APK size hasn't been impacted significantly, the fonts get downloaded from Google Fonts, and your old settings automatically migrate to the new picker.

**Comment by asxhelr657** [comment]
> ![Screenshot_20240314-234503.png](https://github.com/25huizengek1/ViTune/assets/50515369/b69f40a1-1ab5-4f83-9215-ff6a9a1b7bfc)
> 
> Added a font picker. Don't worry, the APK size hasn't been impacted significantly, the fonts get downloaded from Google Fonts, and your old settings automatically migrate to the new picker.

Thank you very much for listening to my suggestions!

**Comment by XelXen** [comment]
I would really recommend you to check these fonts:

General Sans
Fixel
Switzer
Author
Montserrat
Cabinet Grotesk
Space Grotesk
Satoshi
Manrope
Pally

**Comment by 25huizengek1** [comment]
Closing this issue as resolved:

- The theming is being worked on in #228, tracking in #142
- Language picker is implemented
- Font picker is implemented
