### ISSUE TITLE
More Lyrics Customisation & Improvements

### ISSUE THREAD

**Issue by SiddhantRakh** [25huizengek1/ViTune#152]
## Feature request: Improving the Lyrics experience.

I think that the current implementation of lyrics is great. The recent addition of dynamic theming to lyrics is a nice subtle change. I have some more suggestions to make:

• **Thumbnail lyrics:**
   * Option to change alignment (center to left)
   * Slightly larger font size or adjustable font size with increased line spacing
   * Enhanced animations (e.g., zooming on current line)
 
• **Expanded lyrics:**
   * Alternative launch method (e.g., button at bottom left corner of thumbnail)
   * True full-screen mode 
   * Slightly blurred background art for better visibility
   * Reduced left/right padding

Example for reference:

https://github.com/25huizengek1/ViTune/assets/42494931/067b6808-3371-4d76-9d07-837cda7bf7bb

These are just suggestions, and I appreciate your ongoing development efforts. I would be equally happy if any of this gets implemented in the app.

**Comment by 25huizengek1** [comment]
> • **Thumbnail lyrics:**
> 
> * Option to change alignment (center to left)

Not going to do this, I'm sorry. The settings tab of the app is already filled with customization and is already in danger of getting too cluttered. This would only worsen this problem.
> * Slightly larger font size or adjustable font size with increased line spacing

You can increase font size/line spacing in your device's settings.
> * Enhanced animations (e.g., zooming on current line)

What do you mean with 'zooming on' current line?
> • **Expanded lyrics:**
> 
> * Alternative launch method (e.g., button at bottom left corner of thumbnail)

Great suggestion, I'll see if I can find an appropriate icon for this.
> * True full-screen mode

Why would we want 'true' full screen mode? I think this is a useless feature.
> * Slightly blurred background art for better visibility

I'll consider this. Android's built-in blur algorithm is not supported on all Android versions though, so I don't know if I can make it work on every device.
> * Reduced left/right padding

There currently is 32 dp of padding on both horizontal sides from the lyrics. In my opinion, this looks close to perfect. We could shave off a few dps?

Thank you for your appreciation. I've provided feedback on all of your suggestions above.

**Comment by SiddhantRakh** [comment]
> > • **Thumbnail lyrics:**
> > 
> > * Option to change alignment (center to left)
> 
> Not going to do this, I'm sorry. The settings tab of the app is already filled with customization and is already in danger of getting too cluttered. This would only worsen this problem.

> > * True full-screen mode
> 
> Why would we want 'true' full screen mode? I think this is a useless feature.

I agree to all. Please can you reconsider the full screen mode suggestion. The problem I face is that the pinching in gesture to full screen lyrics is a bit clunky and even after being full screened there is no perceivable increase in immersion it just feels very cramped. In the video I attached you can see that true full screen mode can looks and feels so immersive. 

About the lyrics alignment option if you are worried it would clutter the settings page you can put that option in the drop down menu which appears when enabling synchronised lyrics. It's a simple yet effective feature which can be really handy for those who need it. Also many players like Innertune have this feature since day one. 

About the zooming in on one line. I mean there should be more emphasis on the current highlighted line maybe a tinted background for the current line could help. But personally I think this is unnecessary as the current design language is great.

**Comment by SiddhantRakh** [comment]
> > > • **Thumbnail lyrics:**
> > > 
> > > * Option to change alignment (center to left)
> > 
> > 
> > Not going to do this, I'm sorry. The settings tab of the app is already filled with customization and is already in danger of getting too cluttered. This would only worsen this problem.
> 
> > > * True full-screen mode
> > 
> > 
> > Why would we want 'true' full screen mode? I think this is a useless feature.
> 
> I agree to all. Please can you reconsider the full screen mode suggestion. The problem I face is that the pinching in gesture to full screen lyrics is a bit clunky and even after being full screened there is no perceivable increase in immersion it just feels very cramped. In the video I attached you can see that true full screen mode can looks and feels so immersive.
> 
> About the lyrics alignment option if you are worried it would clutter the settings page you can put that option in the drop down menu which appears when enabling synchronised lyrics. It's a simple yet effective feature which can be really handy for those who need it. Also many players like Innertune have this feature since day one. Most conventional streaming apps have the left alignment as well. 
> 
> About the zooming in on one line. I mean there should be more emphasis on the current highlighted line maybe a tinted background for the current line could help. But personally I think this is unnecessary as the current design language is great.

**Comment by 25huizengek1** [comment]
All implemented.

**Comment by SiddhantRakh** [comment]
> All implemented.

Thanks I'm loving the blur for lyrics.
