### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by FaqatZubair1** [25huizengek1/ViTune#156]
## Feature request: [name]

I should be able to put sleep timer for any time I want. It has a minimum time for 10 min. And I should be able to stop queue after a particular song.

**Comment by 25huizengek1** [comment]
I like the idea, but what do you want this to look like?

**Comment by FaqatZubair1** [comment]
Well... I would like it to be like,
When I click on sleep timer, I get options like: end after this song or set a custom timer.
When custom timer is selected, I should be able to manually input the minutes and seconds.
I guess Spotify has this feature, you could check that also, it's been a long time since I used Spotify but I really liked that feature.

**Comment by 25huizengek1** [comment]
Steps of 10 minutes are fine in my opinion, you probably do not need more precision, so I'll keep it as it is right now for simplicity's sake. Spotify provides 5m, 10m, 15m, 30m, 45m, 60m and end of track. I guess I can add an end of track button.

**Comment by FaqatZubair1** [comment]
That'd be also good to me.

**Comment by FaqatZubair1** [comment]
Just another little request,
Is there anyway you can add a toggle to switch ui back to that of vimusic. Because some people like minimal things. Or you could just design something yourself (if you are interested), that is super minimal, because you have added a lot of visual elements in this. I am not saying that I don't like that, it is good, but keeping a minimal option would make it great. 
This is just my personal suggestion
