### ISSUE TITLE
Ghost files showing up in local music tab 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#163]
## Feature request: [Add a "hide song" button for local music]
Deleted music files shows up on my device, I've opened this issue before but it still persists.

It seems the app adds the local songs to the database and is unable to remove that data when the song gets deleted. I noticed the ghost songs shows up when you import a database that contained the previously deleted songs or when you delete a listed audio file on your device.

**Add a "hide" song button to remove unwanted songs from local library just like the way it's done for streamed songs. That way we can remove songs that we don't want showing up on local library.**

![Screenshot_20240314-092846](https://github.com/25huizengek1/ViTune/assets/140274753/0a762492-bac6-4174-a7de-8baf2f0eff8b)

![Screenshot_20240314-094933](https://github.com/25huizengek1/ViTune/assets/140274753/57050f50-f2e0-4767-bf80-6315f1051d4b)

**Maybe add a label to let users know: ”This does not delete the song from your device" 
to different between the two hide functions**

**Comment by 25huizengek1** [comment]
Good idea, I think I'm going to hide files that are unavailable in the first place, but I'll have to see what fits best.

**Comment by genericbetatester** [comment]
> Good idea, I think I'm going to hide files that are unavailable in the first place, but I'll have to see what fits best.

It'd be better to see the two implemented
