### ISSUE TITLE
Weird "close queue" button placement 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#164]
### Steps to reproduce the bug

1. Open queue menu

### Expected behavior

"close queue" button should be centered on device navigation bar

### Actual behavior

**It's off-center and leans slightly to the right**

![IMG-20240314-0003](https://github.com/25huizengek1/ViTune/assets/140274753/3ea16590-3043-4146-8a7b-462582677df5)
 side

### ViMusic version

v.0.6.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Tecno spark go (2021)

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Not a bug, but just inconsistent UI at most. It's actually perfectly centered, just not with respect to the screen, but to the buttons. This is intended.

**Comment by genericbetatester** [comment]
> Not a bug, but just inconsistent UI at most. It's actually perfectly centered, just not with respect to the screen, but to the buttons. This is intended.

If you say so. (It's just a pain to look at lol )
