### ISSUE TITLE
Song option menu won't close after hiding song 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#166]
### Steps to reproduce the bug

1. Long press song
2. Hide song

### Expected behavior

Option menu should close 

### Actual behavior

It won't close giving impression that the song wasn't removed when it has been removed. 

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/140274753/5f290c3c-c1fd-4b7a-9529-b48cfe996f7d

### ViMusic version

v.0.6.7

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Tecno spark go 2021

### Additional information

Btw, I like the new progress bar on the collapsed player.

Quick suggestion: I think It will be nice if the player screen on PureBlack theme had a place holder for the song duration since the time stamp is hidden
Something like this:
![Screenshot_20240316-010842](https://github.com/25huizengek1/ViTune/assets/140274753/3bb40100-814e-4470-ae0d-d54422f8331e)

![Screenshot_20240316-010923](https://github.com/25huizengek1/ViTune/assets/140274753/bbd2e536-85e5-4f49-80e3-241bc5a1c063)

EDIT: We can no longer swipe up to reveal song timestamp on modern layout, why is that??
### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Beyond the scope of this issue, but to reply to your questions:

> Btw, I like the new progress bar on the collapsed player.

Thank you! Maybe we should have a selector for both options but I'm not sure yet as it creates unnecessary complexity.

> Quick suggestion: I think It will be nice if the player screen on PureBlack theme had a place holder for the song duration since the time stamp is hidden
Something like this:

I'll consider this. Thank you for your suggestion.

> EDIT: We can no longer swipe up to reveal song timestamp on modern layout, why is that??

This was never intentional, I have fixed this bug in #138.

**Comment by 25huizengek1** [comment]
Fixed it, issue will close automatically.
