### ISSUE TITLE
Small Enhancement for Amoled Theme

### ISSUE THREAD

**Issue by SiddhantRakh** [25huizengek1/ViTune#168]
**Make action buttons to follow the dynamic theming as well when Amoled theme is active.**

Here's a visual representation of my enhancement:

Current implementation:
![Screenshot_20240316-155108](https://github.com/25huizengek1/ViTune/assets/42494931/2285139c-58df-4a7d-8a8f-f84809496428)

Required implementation:
![imageedit_2_9141848142](https://github.com/25huizengek1/ViTune/assets/42494931/3675680a-7983-46d5-9bb6-9c22eeba3c1c)

This will make the amoled theme to be more in line with the dynamic theme rather than just a modified PureBlack theme.

**Comment by 25huizengek1** [comment]
Good suggestion, I'll consider it.

**Comment by 25huizengek1** [comment]
In my opinion, it doesn't look that good on a black background. The gray color as it is right now is more suitable. Otherwise, the button would either stand out too much or won't look like a primary button anymore. I'll have to reject the request for now, I'm afraid.

**Comment by SiddhantRakh** [comment]
> In my opinion, it doesn't look that good on a black background. The gray color as it is right now is more suitable. Otherwise, the button would either stand out too much or won't look like a primary button anymore. I'll have to reject the request for now, I'm afraid.

No problem. I totally respect your decision. Just noticed the new rebrand. Congratulations and hope you keep improving this app. 👍
