### ISSUE TITLE
Change seek bar & next previous button color

### ISSUE THREAD

**Issue by Nikks84** [25huizengek1/ViTune#173]
![IMG_20240319_091112](https://github.com/25huizengek1/ViTune/assets/160481076/9a24cf4b-d014-4c2f-ad6f-8db324e629a7)

Change the colors seek bar & next previous button in dynamic & amoled theme according to the song are listening just like button color change when you change the song on dynamic & amoled theme.

**Comment by Nikks84** [comment]
> ![IMG_20240319_091112](https://private-user-images.githubusercontent.com/160481076/313915861-9a24cf4b-d014-4c2f-ad6f-8db324e629a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjE4MDQsIm5iZiI6MTcxMDgyMTUwNCwicGF0aCI6Ii8xNjA0ODEwNzYvMzEzOTE1ODYxLTlhMjRjZjRiLWQwMTQtNGMyZi1hZDZmLThkYjMyNGU2MjlhNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNDExNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Njc5NGU1ZWI2YjJmZTYyMWY2MjU0ZjdmMTI2MmQzMWZlZGRjYTRiYzg3Y2U1NDI2MTEwZTUyNDQ5MzViMmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N6iBG62eQUcjPpjd-ycgVfrNRXTrPsGCKNDjLEIMgeA)
> 
> Change the colors seek bar & next previous button in dynamic & amoled theme according to the song are listening just like button color change when you change the song on dynamic & amoled theme. Or yes play pause button also.

**Comment by 25huizengek1** [comment]
I don’t understand, these UI elements are already responding to dynamic theming.

**Comment by Nikks84** [comment]
> I don’t understand, these UI elements are already responding to dynamic theming.

Yes you are right But I mean that the color of seekbar or song timeline and play pause and next previous button is black, I want to say that their color should also change according to the dynamic theme, as the colors keep changing in the dynamic theme, I want this also to keep changing. 
Ex. Just like the SS
![IMG_20240319_162523](https://github.com/25huizengek1/ViTune/assets/160481076/360fc657-22d8-428d-847d-760e09aae957)

**Comment by 25huizengek1** [comment]
I understand, but I will not make it look like that, as the buttons are essential buttons that should have a significant contrast between the icon and the background of the button. To improve consistency, the seek bar is also colored like that.
