### ISSUE TITLE
[Feature Request]: Add Ability to make a playlist of offline songs..

### ISSUE THREAD

**Issue by Enigma1309** [25huizengek1/ViTune#174]
Just a simple solution that came into my mind,
Since there's going to be an rebrand of the app, a lot of people will be stuck to old version because of their cached songs,

So it's my proposal to add an option to save the current offline songs as a playlist..

Why??

Since we can export it in backup as an regular playlist (also this will still be cross compatible) and when user will restore it to the new app, they can recache the whole playlist at one click , since caching a playlist is already an existing feature, and user may delete the playlist and still have thier songs cached :D

Thanks

**Comment by genericbetatester** [comment]
Isn't it already possible? Just play all your offline songs and add the queue to a playlist

**Comment by Enigma1309** [comment]
how to do so? i enqueued offline songs playlist and chose add to playlist, but it seems to add the specific song to playlist rather than the whole queue

**Comment by 25huizengek1** [comment]
@genericbetatester is right. You can add the entire queue by clicking on the song count in the queue sheet, so I won’t add a separate offline playlist for simplicity.

**Comment by genericbetatester** [comment]
> how to do so? i enqueued offline songs playlist and chose add to playlist, but it seems to add the specific song to playlist rather than the whole queue

1.Make sure all your songs are on queue
2. Tap on open queue button to open queue
3. On the bottom right hand of the screen see the button that reads ”X songs" (e.g 12 songs, initiating number of songs on queue)
4. Clicking on that button opens up an option that allows you to add your queue to a playlist
