### ISSUE TITLE
Suggestions to prevent accidental queue Clearing 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#177]
Accidental queue Clearing has always been an issue in most music players and I think we should take steps to stop that. I have some ideas and other suggestions are welcome.

1. Undo button: seems to be the safest option, provide a snacker bar to undo the action, maybe 5 seconds countdown.

2. Ask for confirmation before clear queue: not that clean imo but it's an option. I think it's useful when you swipe on the mini player. Because accidental swipes occur. 

3. Lock/Unlock queue: when queue is locked, only song enqueue or dequeue is allowed. Tap on song plays it immediately but adds it to the existing queue instead of clearing. This one is my favorite, single tap allows easy enqueue of songs. But I fear some users might find it unintuitive.

5. Queue history: saves recently deleted queue to history for some hours/minutes.

6. Gestures: i.e when queue is active single tap plays songs but adds it to existing queue double tap on song will create new queue. (Not intuitive because new users might find it difficult to adapt) 

I hope I've raised strong points to allow for the implementation of one of this suggestions. You know it's annoying curating a queue only to have it cleared by accidentally tapping a song especially when the songs are not in your library. 

Edit: I thinks option 1 and 2 works best for mini player and I think it should be implemented alongside one other suggestions for accidental clearing resulting from tapping on a song in library

**Comment by 25huizengek1** [comment]
Great suggestion, thank you! I guess the most intuitive is the possibility for users to enable a confirmation dialog before closing the player, alongside a 'restore latest queue' somewhere in the settings. I'll look into this.

**Comment by genericbetatester** [comment]
> Great suggestion, thank you! I guess the most intuitive is the possibility for users to enable a confirmation dialog before closing the player, alongside a 'restore latest queue' somewhere in the settings. I'll look into this.

Great!

**Comment by dtomvan** [comment]
Or (maybe fantasizing here a bit) we don't need queues to be closed at all? If you want a new queue, you can tap a song?

**Comment by genericbetatester** [comment]
> Or (maybe fantasizing here a bit) we don't need queues to be closed at all? If you want a new queue, you can tap a song?

I don't think that's a good idea because the real reason why I made this suggestion is because of queue closing as a result of accidental tapping on songs

**Comment by Geigerkind** [comment]
I also found this one very weird in most apps.
I think an option (that could be disabled in the settings) is to just prepend a song to the queue if a song is "forcefully" played. After that, its just business as usual.

**Comment by dtomvan** [comment]
A sort-of solution to this I find to be [Musicolet](krosbits.in/musicolet). It is way too complicated for an app like Vitune imo, but here goes: it works with multiple queues. Each time you tap a song, you get a new queue, but you can always switch to a previous one.

**Comment by 25huizengek1** [comment]
It's always possible to recreate your queue if you accidentally closed it. Combined with the [history playlist](https://github.com/25huizengek1/ViTune/commit/983255a19fdb76403c9f87f313acabe42278d22b) I think this can be closed.
