### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by senolfndk** [25huizengek1/ViTune#179]

**Comment by 25huizengek1** [comment]
Those are four completely different designs. What is it exactly what you want to have changed about the current design? Please elaborate.

I do see a voice input button, is that something that you want?

**Comment by senolfndk** [comment]
play button square curved circle
progress bar wavy thick bar

**Comment by senolfndk** [comment]
![20240321_232456](https://github.com/25huizengek1/ViTune/assets/52818836/69932eaf-b79d-4dd8-ab79-bdad87708d20)

**Comment by senolfndk** [comment]
suggestion: player and progress bar
![Screenshot_20240321-232820_AIMP](https://github.com/25huizengek1/ViTune/assets/52818836/4e01fa4a-2852-40dd-b781-9183aa7500d5)

**Comment by Enigma1309** [comment]
This isn't an issue, please post these types of things in Discussion panel


![image](https://github.com/25huizengek1/ViTune/assets/94917588/1500f9d3-89de-4d8c-94ce-e77ce756c7cc)

also it's my request to @25huizengek1 to update the issue template, for only bugs/issues and remove the feature request from template or make them redirect to discussion page instead (if it's possible)
![image](https://github.com/25huizengek1/ViTune/assets/94917588/1a51cb24-e5f1-4042-b137-ab36bc493934)

Thank You

**Comment by 25huizengek1** [comment]
I'm keeping it this way. Feature requests are definitely issues, but discussions are more suitable for ideas for possible feature requests. @Enigma1309

**Comment by 25huizengek1** [comment]
@senolfndk Why is this closed? I did not 'reject' your request or something like that?

**Comment by senolfndk** [comment]
> @senolfndkBu neden kapalı? İsteğinizi veya buna benzer bir şeyi 'reddetmedim' mi?

I closed it because you robbed it like that. I shared the topic in discussions

**Comment by 25huizengek1** [comment]
@senolfndk That was not my reply, the only thing I asked was this

> Those are four completely different designs. What is it exactly what you want to have changed about the current design? Please elaborate.
> 
> I do see a voice input button, is that something that you want?

**Comment by senolfndk** [comment]
> @senolfndkCevabım bu değildi, sorduğum tek şey şuydu
> 
> > Bunlar tamamen farklı dört tasarım. Mevcut tasarımda değiştirmek istediğiniz şey tam olarak nedir? Lütfen detaylandırın.
> > Bir ses girişi düğmesi görüyorum, bu sizin istediğiniz bir şey mi?

No, there is nothing I want, I just shared it as a suggestion or idea.
