### ISSUE TITLE
Time left

### ISSUE THREAD

**Issue by FaqatZubair1** [25huizengek1/ViTune#180]
## Feature request: [Should be able to see how much time is left for a song to end]

There should be a small label that showed how much time is left for a song to end.

**Comment by 25huizengek1** [comment]
I personally disagree. What is an appropriate placement for this label, according to you?

**Comment by FaqatZubair1** [comment]
![Screenshot_20240322-051852](https://github.com/25huizengek1/ViTune/assets/161596117/e9bbb2fa-5bd9-48ee-a7a7-0f694a1670a3)
The place where I've added the "time left" text would be great. Actually this feature helps in case I'm in hurry and have to see if I need to wait for the song to end or it'll end just on time ( it's not very common but I'm like this).

Also, thanks for adding sleep timer for individual songs

**Comment by FaqatZubair1** [comment]
![Screenshot_20240322-054409](https://github.com/25huizengek1/ViTune/assets/161596117/f21ab4bd-1a8c-4d43-8520-9d0fd788cc76)
Or like this (I wanted to make sure that this time it looks good too).

**Comment by Enigma1309** [comment]
modern design is meant to be minimal, also we can see the time by moving seekbar...
If you want to (always) see time for the song, you can also use Classic layout which has all those things.

**Comment by FaqatZubair1** [comment]
> modern design is meant to be minimal, also we can see the time by moving seekbar... If you want to (always) see time for the song, you can also use Classic layout which has all those things.

The things you said have the total duration of the song and not the time left. Also, this doesn't reduce the minimalist design, and if it does, dev can add a toggle in the settings for it. Afterall it's upto dev, I just gave a suggestion.

**Comment by Enigma1309** [comment]
okay i can't beat you 😅

**Comment by NeeRaj-2401** [comment]
I would like to suggest a behaviour, which could result in showing the time left  keeping the minimalist design.

we alredy can see song duration while we try to seek , 
<img src='https://github.com/25huizengek1/ViTune/assets/88180887/fa45161e-2ab3-4447-8dfb-3abc873b3000' width='25%'>

but the catch is, the duration is only visible until we are scrubbing the seekbar,

I would suggest to implement a swipe up / swipe down behaviour to show / hide the duration respectively,

and then clicking on current duration would toggle between time left or current duration (we have this behaviour in official YT app).

PS: no need to add extra settings option for this :)

**Comment by FaqatZubair1** [comment]
Yeah, that is a brilliant idea

**Comment by FaqatZubair1** [comment]
> I would suggest to implement a swipe up / swipe down behaviour to show / hide the duration respectively,
> 

As of now, nothing happens when we swipe up on ablbum cover, so, dev can add a feature where swiping up on album cover reveals the same

**Comment by NeeRaj-2401** [comment]
> > I would suggest to implement a swipe up / swipe down behaviour to show / hide the duration respectively,
> 
> As of now, nothing happens when we swipe up on album cover, so, dev can add a feature where swiping up on album cover reveals the same

my idea was to swipe up / down on SEEKBAR, cause swipe over the album to reveal the duration doesnt shows much relation between them

**Comment by FaqatZubair1** [comment]
> > > I would suggest to implement a swipe up / swipe down behaviour to show / hide the duration respectively,
> > 
> > 
> > As of now, nothing happens when we swipe up on album cover, so, dev can add a feature where swiping up on album cover reveals the same
> 
> my idea was to swipe up / down on SEEKBAR, cause swipe over the album to reveal the duration doesnt shows much relation between them

I think it would make it difficult to seek (which is the actual function of it) because sometimes when we need to see the duration, we might seek through the song.

**Comment by NeeRaj-2401** [comment]
> we might seek through the song.

thats what i asked dev to resolve in #138

**Comment by FaqatZubair1** [comment]
A small arrow near the end of seekbar would also do the job. Let's wait for dev to reply, then we can brainstorm the ideas further, because he might not even like the idea of duration in the first place.



> 
> thats what i asked dev to resolve in #138

That will lead to an issue, where if we want to seek, it won't be as quick or in some cases it might not respond at all.

**Comment by genericbetatester** [comment]
Afaik we were able to swipe up on the seek bar to view timestamp, and it worked well without seeking through the song. The bar will jump visually to where you swiped but it won't seek the song, closing and reopening the mini player resets it to normal. But an update broke that feature iirc 0.6.7 dev said it was fixed. I quote: ”This was never intentional, I have fixed this bug in #138”

**Comment by FaqatZubair1** [comment]
Idk why the dev removed the feature then, if it worked well. Because I started using this fork from a week or so, and didn't know this kind of feature already existed.

**Comment by genericbetatester** [comment]
> Idk why the dev removed the feature then, if it worked well. Because I started using this fork from a week or so, and didn't know this kind of feature already existed.

I don't think He broke it intentionally. It's usually one of the hassles that comes with app development.

**Comment by 25huizengek1** [comment]
It was not a feature at all, it was a remnant from Colorata's implementation of the wavy seek bar. I guess you could just turn on the classic player layout? If you really want the time remaining, I guess I could implement it so when you click on the time, it toggles 'time remaining'. I'll look into this.

**Comment by 25huizengek1** [comment]
Added, it looks like this now when you click on the position:

![Screenshot_20240324-214252.png](https://github.com/25huizengek1/ViTune/assets/50515369/79d16a4e-47e2-4360-92bf-e501eb96576c)
