### ISSUE TITLE
Feature Request: Lyrics for songs on device

### ISSUE THREAD

**Issue by VixtoryHax** [25huizengek1/ViTune#182]
I have quite a large library of songs on my phone (900+), and a lot of them have lyrics in the form of .lrc files. I was wondering if it's possible to use them in ViTune, or even using the lyrics for online songs instead?

Thanks for reading

**Comment by Enigma1309** [comment]
afaik lyrics in offline mode is not a feature yet, i hope we'll see it in future

also i can't use use external app to open vi music to play files

**Comment by VixtoryHax** [comment]
> also i can't use use external app to open vi music to play files

Yeah neither can I but I don't think it's that important of a feature
Do you use it regularly

**Comment by Enigma1309** [comment]
i do have a long music playlist of offline music but i rarely find myself using it, rather i prefer using the ViTune official one's this may be because i like to see lyrics sometimes, so yeah lyrics may come in handy in alot of situations

> Do you use it regularly

there isn't an option to play external music with vi music, though i think it won't be too complicated to implement..
my most of the mobile screen time goes to using ViTune  so i think that counts :)

**Comment by VixtoryHax** [comment]
> there isn't an option to play external music with vi music, though i think it won't be too complicated to implement.. my most of the mobile screen time goes to using ViTune so i think that counts :)

Fair enough I'm juggling a few music players so I don't really have a point 
Let's just hope the dev sees this and adds both features

**Comment by 25huizengek1** [comment]
Good suggestion. I guess it's fairly easy to implement/get right, so I'll look into this.

**Comment by VixtoryHax** [comment]
This is off topic but another thing I've noticed is all the songs I have downloaded end up being sorted alphabetically when I choose age order. Time played does work but I think it's something to do with metadata?

**Comment by Enigma1309** [comment]
> Time played does work but I think it's something to do with metadata?

this only happens in local music, idk the cause but this probably isn't any metadata issue, since i've almost all metatdata (artist name, thumbnail,etc)  in the offline music but it don't sort...
