### ISSUE TITLE
Can we get backwards compatibility for database 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#193]
I wanted to export my current database to an old version of vimusic but it didn't work, the target app kept crashing, so I'm requesting if is possible to make vitune database work with vimusic.

**Comment by 25huizengek1** [comment]
ViMusic doesn't have a backwards compatible database, so unfortunately no, ViTune won't be able to support older versions of ViMusic, unless I create an export button for every database version of every ViMusic version individually, but there is no point in doing that.
