### ISSUE TITLE
Changing the songs area

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#196]
Would it perhaps be possible to change the song section a little?

At the moment, every song you listen to is added to the song section (library) whether you like it or not. Over time, a lot of songs accumulate there that you don't like.

Would it be possible to choose which song is added to the song section (library), like with 'Innertune', to have a little more order in it?
Thank you very much for your hard work and time you invest in this project.

**Comment by dtomvan** [comment]
There's already a sorting button, you can discard songs you don't like and you can make use of the like system. I don't really understand your problem. Could you clarify? IE Maybe show a key difference with innertune?

**Comment by siggi1984** [comment]
> There's already a sorting button, you can discard songs you don't like and you can make use of the like system. I don't really understand your problem. Could you clarify? IE Maybe show a key difference with innertune?

I would like to decide for myself which song is added to my library and not automatically just because I have listened to it.

**Comment by dtomvan** [comment]
I'm sorry, but you can already do that; by pressing the like button on songs you like.

**Comment by siggi1984** [comment]
> I'm sorry, but you can already do that; by pressing the like button on songs you like.

The Like playlist is not the same as the entire music library.

**Comment by 25huizengek1** [comment]
@siggi1984 You already have multiple ways of managing your songs: you can like songs, hide songs, use the top playlist or just sort the songs tab differently, so there's no reason to complicate this even further
