### ISSUE TITLE
Newly added search bar in songs, local etc tabs

### ISSUE THREAD

**Issue by RAjBiYgitHubNF6q** [25huizengek1/ViTune#197]
### Steps to reproduce the bug

1.Open Vitune
2.Navigate to 'songs' or 'Local' tab
3. Click on the newly added search icon where also shown the number of songs I have in that very tab
4. This is the bug

### Expected behavior

After a successful search the search bar should collapse and stop blinking the cursor on a outside tap or back action

### Actual behavior

After a successful search , the search bar isn't collapsing and keep blinking the cursor despite you tap outside or perform a back action(on performing a back action the app closes but the search still remains activated🙁) and open the keyboard whenever I come back to the app's very section

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/134761017/2ad9ceae-fddb-42c9-81f9-5485eea0d13f

### ViTune version

1.0.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

13

### Device info

I am using Motorola moto g72 with a near to stock android 13

### Additional information

Please as fast as possible fix these issue

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by dtomvan** [comment]
I think this is intentional, on android keyboards are closed with the down arrow or a back gesture. In browsers, when focus changes, the keyboard may be discarded by the "host app", ie the browser.

**Comment by 25huizengek1** [comment]
> I think this is intentional, on android keyboards are closed with the down arrow or a back gesture. In browsers, when focus changes, the keyboard may be discarded by the "host app", ie the browser.

It is, so this is not a bug, just an inconvenience at most.
