### ISSUE TITLE
ViTune app label

### ISSUE THREAD

**Issue by Malgotra** [25huizengek1/ViTune#198]
### Steps to reproduce the bug

Install the app and check ViTune app label/Name in app drawer or home screen. Fonts are collapsed with eachother

### Expected behavior

Fonts should be Normal

### Actual behavior

Fonts collapsed

### Screenshots/Screen recordings

![Screenshot_20240329-211327](https://github.com/25huizengek1/ViTune/assets/122884037/4c1074a6-eb50-49d7-81a2-0140f5ef84c0)

### ViTune version

v1.0.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Motorola Moto G52 and also Moto G72. Both running Android 13.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Malgotra** [comment]
Check closely. i and T are collapsing with each other

**Comment by 25huizengek1** [comment]
I can't influence your phone's launcher's font, I'm sorry.

**Comment by Malgotra** [comment]
@25huizengek1 but it's default Android fonts. Not custom fonts.

**Comment by 25huizengek1** [comment]
No it is not, your phone's launcher specifies the font of the app drawer, and each vendor can specify the 'system font'

![Screenshot_20240330-084645.png](https://github.com/25huizengek1/ViTune/assets/50515369/1362e4e3-a9b6-42c2-bba1-0f3ad3e7d213)
