### ISSUE TITLE
Gradient Player Background 

### ISSUE THREAD

**Issue by albinxshiby** [25huizengek1/ViTune#204]
## Feature request: ...

@25huizengek1 
@dtomvan 
I'm keeping it simple and adding some images below and I think it will help understand my suggestion.
![Screenshot_2024-04-01-16-33-16-81_91b67804b5fb3353a77fb824d6bb0b50.jpg](https://github.com/25huizengek1/ViTune/assets/145864271/2e281e5c-6f48-4fe3-88c9-d92db19ae15d)

I just took this screenshot from RiMusic a fork from ViMusic and I think many people like this type of player background including me.
Many other apps like blackhole or Simpmusic(default) have a feature similar to this.
I want this feature not to be default but just an option.
ThankU 🍻

**Comment by 25huizengek1** [comment]
That background already exists, I'll release it somewhere this week.
