### ISSUE TITLE
Allow Users to Control Auto-Caching

### ISSUE THREAD

**Issue by creuserr** [25huizengek1/ViTune#205]
Given that this branch of ViMusic offers an option to pre-cache songs, I believe users should have the ability to control auto-caching, including the option to disable it when playing a song. It undeniably consumes memory, and providing control over it is essential.

Additionally, I suggest implementing a feature where pre-caching (or downloading for offline use) bypasses the auto-caching control. For example, if a user disables auto-caching to prevent caching while listening to music, downloading a song should still cache it regardless of the auto-caching setting.

**Comment by Enigma1309** [comment]
also it would be better if thumbnails of music gets auto-cached too while manual caching the playlist

**Comment by dtomvan** [comment]
Yes, I hear you. I wonder what @25huizengek1 thinks of it though, since this isn't really an issue on any modern device nowadays. ViTune can hold my past year of music consumption through just 3 Gibibytes so I wonder why we'd need a big "cache overhaul"...

**Comment by 25huizengek1** [comment]
I agree with @dtomvan. Also, this would unnecessarily overcomplicate the app, while cluttering all of the UI around caching even further, making it even harder for new users to wrap their head around.
