### ISSUE TITLE
Enable Direct Song Downloads as MP3

### ISSUE THREAD

**Issue by creuserr** [25huizengek1/ViTune#206]
Implementing the capability for users to directly download songs as MP3 files would be a significant game changer.

**Comment by Enigma1309** [comment]
not gonna implement soon https://github.com/25huizengek1/ViTune/issues/151#issuecomment-1997915830

**Comment by dtomvan** [comment]
Yes, just as enigma said. You can use an app like Newpipe, Seal, YTDLnis or even termux with yt-dlp to download songs manually as mp3. Then you could use any old local audio player (or ViTune) to listen back to them. Closing this as out of scope.
