### ISSUE TITLE
Will this app ever be added to the main Fdroid?

### ISSUE THREAD

**Issue by devika15** [25huizengek1/ViTune#216]
A couple of people I know tried to get this but then gave up the plan when they realised that it's not on the main Fdroid repository.

**Comment by dtomvan** [comment]
Probably not, since we have our own FDroid repo, and the main repo is stricter on 2hat can and cannot be added to their repo. Also release builds will be worse because we can only include free (as in beer) services.

**Comment by 25huizengek1** [comment]
F-Droid is not that permissive, indeed, and since F-Droid can't even keep up with weekly releases (they build everything on a centralized F-Droid build server, so it takes a long time before your app is queued) I guess sticking with our own repository for now is good enough for now.
