### ISSUE TITLE
Dynamic color theme only for Player screen

### ISSUE THREAD

**Issue by Shinichi-Here** [25huizengek1/ViTune#218]
Option to set Dynamic color theme for Player screen while having Material you theme for the whole other parts of the app.

**Comment by dtomvan** [comment]
Yeah, that seems way too complicated to do. Why would you even need a multi-theme setup? It raises confusion and doesn't seem to improve the user experience in any way. We already have an AMOLED theme though, so you can use that if you want the player to stay dynamically colored.

See also my PR which introduces more flexibility on the PureBlack theme. Hope that does the trick: #214 

Let's close this as wontfix...
