### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by peat80** [25huizengek1/ViTune#219]
## Feature request: ...

"User interface that fully supports non touch devices"

Since the original vimusic also partially supports android tv what are the plans for this project?

It also works, like the original to some degree.
Some things are hard or not reachable with just the remote the rest of the app works fine.

Is it going to be improved in future releases or is it not officially supported and would stay as it is?

Would be awesome if the ui could become fully compatible with non touch devices one day. 😎

**Comment by dtomvan** [comment]
Yeah, this isn't viable for various reasons:
- We aren't a streaming service, so we aren't of any use on an Android TV. It would be a waste of time, money and other resources.
- We are directly competing with the YT Music app, so it wouldn't even be allowed to be distributed on Android TV.
- We aren't and will never be on the Play Store, F-Droid or any other major app store on android. So installing and updating this on F-Droid would be a pain.
- Implementing an Android TV UI/UX would be added complexity (once again) in the code base.
- We do have Android Auto / Default Media Receiver support, which would have to and probably will suffice.

See: #217
