### ISSUE TITLE
An option to change the style of the progress bar in collapsed mode

### ISSUE THREAD

**Issue by sidsharths1245** [25huizengek1/ViTune#220]
## Feature request

I was wondering if we can add an option to change the style of the progress bar in the collapsed mode. I do like how it looks currently but I feel if we add the wiggly line animation to show the progress it will look better. We can also add an additional functionality where we touch the wiggly line to change the progress of the song.

**Comment by sidsharths1245** [comment]
![Screenshot_20240409-204658](https://github.com/25huizengek1/ViTune/assets/64619769/7ac5b42b-1447-4539-b500-48e85facbe85)
Something like how it looks in this screenshot (ignore everything else I'm just referring to the progress bar). Instead of the straight line we can incorporate the wiggly line or even straight line will be great.

**Comment by 25huizengek1** [comment]
@sidsharths1245 What do you mean exactly? You want to be able to choose between a straight line or a 'wiggly line'? I don't entirely understand what you mean by 'wiggly line', and I don't get why we would want to be able to customize this.
