### ISSUE TITLE
Hide left control/navigation bar

### ISSUE THREAD

**Issue by surajak** [25huizengek1/ViTune#225]
## Feature request: ...

The left control bar, from where we can navigate to different section. Can we have a setting to hide it or get it at bottom or top side, as mobile screen is portrait mode and it's taking up lots of space, making remaining useful space even more narrow.

**Comment by genericbetatester** [comment]
Useful space?? What do you want to fit in there? I think the vertical navigation is what sets the app apart from others and I think it's brilliant. Maybe you're new to the app, you'll get used to it.

**Comment by 25huizengek1** [comment]
@genericbetatester, thank you for your explanation. I guess we could implement it but it would result in inconsistent design with the player etc. Closing this for now.
