### ISSUE TITLE
Album doesn't fully load after being saved on database

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#229]
### Steps to reproduce the bug

With my current database:
-Import the database
-Search: Day 69
-Look for the album
-Open the album and wait.

### Expected behavior

It should load the album correctly.

### Actual behavior

The album never loads.

### Screenshots/Screen recordings

![image](https://github.com/25huizengek1/ViTune/assets/1917871/d4146dc5-7f35-41be-ac83-4728c2fc90b0)

### Logs

[data.zip](https://github.com/25huizengek1/ViTune/files/14953130/data.zip)
This is my database that could be imported

### ViTune version

1.0.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Using Pixel 3a XL running Android 10

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [x] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Fixed in 26f61da986bc21b0438ccce439a3665637c1606e

Also, it seems like YouTube apparently removed album descriptions, so if the description that is showing in your screenshot dissappears that's why.

**Comment by 25huizengek1** [comment]
YouTube broke this again :(

**Comment by 25huizengek1** [comment]
Let's hope we can keep this closed forever 😅

**Comment by 25huizengek1** [comment]
Apparently there are even more edge cases, *sigh...*

**Comment by 25huizengek1** [comment]
Fixed in 164a5ede7c6a16c0f61cf5c44c29aabede1fc0b1

**Comment by senolfndk** [comment]
albums are not saved or displayed ![Screenshot_20240731-001959](https://github.com/user-attachments/assets/80807cc3-5960-4119-9276-136babad3cf6)

**Comment by 25huizengek1** [comment]
Forgot to respond here, but resolved by commits like b88f30c706da8c088336c474d67e76a1d4b782ca
