### ISSUE TITLE
Infinite Loading over Artist Screen

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#230]
### Steps to reproduce the bug

Go to any artist
Wait until load and move below

### Expected behavior

Loading elements should dissapear or at least show the whole info

### Actual behavior

Squares are being shown and never dissapear

### Screenshots/Screen recordings

![image](https://github.com/25huizengek1/ViTune/assets/1917871/f0658b84-b7b2-4804-90ac-3a20ea3acf85)

### ViTune version

1.0.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Using Pixel 3a XL Running Android 10

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Fixed in 5ea635d09770eb98531405ef5202cc7f1c5fade1

**Comment by 25huizengek1** [comment]
https://github.com/25huizengek1/ViTune/commit/5ea635d09770eb98531405ef5202cc7f1c5fade1#diff-451509b57e468a04da181674898c0a100365afb072bad39f6df28449226fe74cR253 Thank you, Kotlin (a simple `Unit` did the trick)
