### ISSUE TITLE
Songs missing in imported playlist

### ISSUE THREAD

**Issue by Kptomy** [25huizengek1/ViTune#236]
### Steps to reproduce the bug

1.Go to youtube music [web or app]
2.Share a playlist to vitune
3.Playlist imported and 210 songs were shown before importing but if I scroll down I can see only about 90 songs and only 90 songs are present even after importing.
4.Retried several times but failed...same problem

### Expected behavior

All songs should be imported

### Actual behavior

Only old songs are missing i.e, the songs which I added to the playlist first

### Screenshots/Screen recordings

Uploading New Project 5 [FE89C55].mp4…

### ViTune version

1.0.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android  12

### Device info

Samsung a12, one ui 4.1

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
When songs are not available (anymore/in your country), ViTune simply ignores them...
Can you please provide me an example of a playlist that fails to load correctly, because there is probably an edge case that I/ViTune doesn't know about, which causes this issue.

Side note: the screen recording didn't get uploaded correctly, so I can't view it.

**Comment by Kptomy** [comment]
I will give you the link for the playlist below 👇

https://music.youtube.com/playlist?list=PLT0GrZ-Vry6j3MqHtl-5ozTfKv8MZUcRL&si=Hxv5zJ2gkHw0kJ9V

And I also attached the screen recording here

Note:The songs are available in my country cause I searched for the song one by one and added to the playlist in Vtune...
If U can't view the screen recording,try drive links

https://drive.google.com/drive/folders/1sgLoqpd0eDbnUIA1A8ZJnRfxlCKq02zc

Uploading ced0d4ef-dead-4bef-bbce-4c588d282893.mp4…
![20240414_220852](https://github.com/25huizengek1/ViTune/assets/152653149/02b145fe-9452-4199-abc8-02f9328b2f6e)

**Comment by 25huizengek1** [comment]
Fixed it, will include in today's nightly build if you want to check it out for yourself.
