### ISSUE TITLE
Video player implementation 

### ISSUE THREAD

**Issue by MyNameIsAnujRanjan** [25huizengek1/ViTune#240]
Can you make video player implementation from YouTube in videos section like yt music different in your style maybe apk.size increased 

_**atleast you can try like beta maybe people like**_

**Comment by 25huizengek1** [comment]
I have no idea what you are requesting here. Can you please elaborate?

**Comment by MyNameIsAnujRanjan** [comment]
I mean YouTube video playback instead like seeing video 
Example searching song 
going to videos section clicking on official music song you can give option instead of playing in audio seeing videoplay

**Comment by MyNameIsAnujRanjan** [comment]
https://github.com/25huizengek1/ViTune/assets/101593194/898b18be-4baf-4047-9c71-0cbdf891193d

You can option to see video in the apk in the more options

**Comment by 25huizengek1** [comment]
ViTune is about _playing_ music, so I won't implement this. I suggest you can just use the 'watch on youtube' button if you want to watch the music video.

**Comment by MyNameIsAnujRanjan** [comment]
> ViTune is about _playing_ music, so I won't implement this. I suggest you can just use the 'watch on youtube' button if you want to watch the music video.

Ok no issues problem I like yt music video feature thatswhy
