### ISSUE TITLE
More lyrics sources (For static/unsync lyrics)

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#242]
Since ViMusic, the app fetch the static lyric from Youtube. But sometimes the lyric its missing, so you are forced to use synced lyrics (From 3rd sources)
Can ViTune has more options to choose for static lyrics in case youtube lyrics are missing? (So it can be loaded automatically in case youtube can't provide it)

**Comment by genericbetatester** [comment]
A very simple option is to copy paste it yourself

**Comment by 25huizengek1** [comment]
I'll add it, it should take a few lines of code.
