### ISSUE TITLE
Add 'Explicit' or 'Uncensored' icon version

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#243]
I found that now its easily to choose a censored song that can't be recognized. Way before those censored songs didn't appear (As far i remember)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/b5c3174d-c43a-4410-b0fb-cbcb6846aea5)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/70eabd9b-49cc-4dc3-8966-1997c4e26886)

**Comment by 25huizengek1** [comment]
Great idea, will implement later.

**Comment by 25huizengek1** [comment]
Implemented. It unfortunately doesn't show for songs that you've cached already, since the app simply didn't know about the explicit badge before, so it'll only show up for new songs, but that shouldn't be a big deal.
