### ISSUE TITLE
[Feature Request]: Offline mode toggle + skip song when not found

### ISSUE THREAD

**Issue by Enigma1309** [25huizengek1/ViTune#244]
## Offline mode

There should be an toggle in settings to change mode to offline when listening to music so that it doesn't fetches data from yt.
 
use case :- 

- when having limited data connectivity but can't disconnect from internet (ex:- on mobile data but someone told to signal call you in a moment)
- using other's WiFi at the moment ...

#### Implementation:-

you may show an top strip at the homepage when this mode is enabled

for ex:- in tachiyomi/mihon
Offline Mode             |  Online mode
:-------------------------:|:-------------------------:
![image](https://github.com/25huizengek1/ViTune/assets/94917588/b1e3fb59-041a-4d57-853c-7426fec90d74) | ![image](https://github.com/25huizengek1/ViTune/assets/94917588/20445ce6-2dab-43bf-85fb-b48c07a24977)

- When this mode enabled the app should not consume any data in any-form (like fetching queue, caching song,getting thumbnail,etc). 

---

## Skip song if not found 

- Sometimes the song cache isn't found and the playback stop , add an feature that skips to the next song, if any exception raise, after the `x` second  (preferably 3 or 5 second)
- Shis feature will work very well in hand with offline music playback and the normal music playback in general.

current exceptions are :-

- `An unknown playback error occurred`
- `Requested video id not found`
- Sometimes the song isn't cached fully, this results in player stopping the music and not skipping to next song in queue (after `x` seconds)
- There may be others i am not aware of..

Thanks

**Comment by 25huizengek1** [comment]
Great suggestions, will put this on low prio for now though.

**Comment by Monoxide8969** [comment]
+1 to skip song if not found, I hate when I have a playlist going and it stops because there's a playback error with one track that needs to be skipped manually

**Comment by Enigma1309** [comment]
i guess i was clear enough 

> 
> There should be an toggle in settings to change mode to offline when listening to music so that it doesn't fetches data from yt.
> 
> use case :-
>
> -  when having limited data connectivity but can't disconnect from internet (ex:- on mobile data but someone told to signal call you in a moment)
> -  using other's WiFi at the moment ...
> 


offline mode means that it doesn't fetches data from the internet when mobile data(or wifi) is turned on ( it will help users with limited data plans).

**Comment by Monoxide8969** [comment]
I understand that much, what I don't understand is why you think the offline playlist is not good enough for your use case?

If you are only playing pre-cached songs from your offline playlist or songs downloaded to your device from the "local" section, the app should not consume more than a few kbs of internet, if any.

**Comment by Enigma1309** [comment]
yes you're correct but the app fetches the thumbnails of the offline songs( if i don't have them), tries to re fetch the music source if it's missing also generates a radio playlist when i'm specifically playing a song by searching (this is one of the biggest reason and consumes a lot of data)

> the app should not consume more than a few kbs of internet, if any.

well that's what i initially thought, but one day this happened :(

![image](https://github.com/25huizengek1/ViTune/assets/94917588/0ed0ba9e-a7ce-4bfb-a684-b3bcf340c276)

i had an limited data plan and it took almost half of it...
well i'm not blaming app or devs but i want this as a feature so that it won't happen next time to anyone

**Comment by Enigma1309** [comment]
thanks for that info but i don't necessarily want to add another app load into my device (it's almost 8 years old so you may understand...)

> they don't feel pressured to implement a feature that 99% of the users won't ever need.

i quite agree with that point but being an open source app i came with proposal now it's up-to maintainers to consider it or not...

also there's no pressure from my side to implement this asap, but i would surely love to see this as a feature coming in the near future <3

**Comment by Monoxide8969** [comment]
Do note that netguard only weights 2.7mb!

I respect your position on the rest though. Godspeed!

**Comment by 25huizengek1** [comment]
I could've closed this way earlier, I suppose. I'm sorry for the delay. ViTune is the side project that gains the most attention from the public, yet has the lowest priority in my life, and I'm afraid there is nothing I can do about it right now.

I agree with @Monoxide8969 (https://github.com/25huizengek1/ViTune/issues/244#issuecomment-2092935066) on this one. Offline mode should do just fine. I've implemented 'skip song when not found' a while ago as 'skip on error' (Settings --> Player), so be sure to check that out.
