### ISSUE TITLE
Can't import my database into the new version

### ISSUE THREAD

**Issue by NXTler** [25huizengek1/ViTune#250]
### Steps to reproduce the bug

Export:
1. Settings
2. Database
3. Save or Export (Sicherung in German)
4. Select Download folder
 
Import:
1. Settings
2. Database
3. Restore
4. Selectdatabase in Download folder

### Expected behavior

The saved songs and playlists should be seen in the overview.

### Actual behavior

The app immediately crashes.

### Screenshots/Screen recordings

I don't think a Video is necessary

### ViTune version

Export from: v0.6.7 Import to: v1.0.2

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I used my Google Pixel 4a with GrapheneOS to Export and Import my database.

### Additional information

Here is my database file: 
[vimusic_20240422133630.db.tar.gz](https://github.com/25huizengek1/ViTune/files/15062224/vimusic_20240422133630.db.tar.gz)

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
It works for me. You should untar your archive of the database file before importing though.

**Comment by NXTler** [comment]
Yeah, I did that. I just needed to tar it for github.

**Comment by dtomvan** [comment]
Also, just so you know, single-file compression doesn't need tar. You can just use gzip2 and gunzip2

**Comment by NXTler** [comment]
Weird, after a few tries it randomly worked. I did nothing different. Anyway I will close this now.
