### ISSUE TITLE
Local Files Reads Metadata

### ISSUE THREAD

**Issue by DrNoob21** [25huizengek1/ViTune#253]
## Feature request: ...

ViTune already does a great job handling local files. However, it would be nice if the app could fully read metadata for songs instead of only three thumbnail. I'd like to see the title of the song rather than the file name + extension. 

![Screenshot_20240426_070206](https://github.com/25huizengek1/ViTune/assets/80936517/28b64fc2-089f-4cca-9fdf-c51cd8c21b2a)

This is ViTune's current local files screen. It serves its purpose

![Screenshot_20240426_070123](https://github.com/25huizengek1/ViTune/assets/80936517/aea8f537-d487-4f19-98a2-dd2717f05424)

This is RiMusic's local files screen. If possible, I'd like something similar to be integrated into this project.

**Comment by DrNoob21** [comment]
Closing this. Clearing cache made it work as expected

**Comment by 25huizengek1** [comment]
@DrNoob21 No problem, RiMusic initially copied my code (without credit) for handling this, so I was wondering why RiMusic handled this better.

I guess clearing the cache refreshed Android's MediaStore index, so that explains why it works properly now.

**Comment by xxuchuujin** [comment]
I'm having this issue right now, clearing the cache did nothing for me :(
