### ISSUE TITLE
Automatically pause a song when volume is set to 0

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#259]
Not much to add to the title. This helps save battery and not screw up listen hours count by keeping the songs play indefinitely if you lowered the volume and forgot about it.

I also thing the song should NOT start playing again automatically when volume is up again, since the user could have forgot about it and the song could restart playing in contexts where it's not appropriate.

Should be easier to implement too this way. Let me know what you think!

**Comment by 25huizengek1** [comment]
Implemented.
