### ISSUE TITLE
Podcast Support?

### ISSUE THREAD

**Issue by JMPesce** [25huizengek1/ViTune#260]
Given Google Podcasts is going away and YouTube Music is where they are migrating podcasts to, I think it would be a good idea to try and incorporate Podcasts into ViTune.

Is that something that can be accomplished at all?

**Comment by 25huizengek1** [comment]
It is possible, yes. I'm aware that Google is changing the way that podcasts work, and the way I've dealt with the fact that they are migrating in the past is by just entirely disabling podcasts, but it looks like it's now a good time to start looking into an implementation.

I guess a separate tab for podcasts is overkill, but incorporating podcasts into ViTune shouldn't be too hard.

**Comment by JMPesce** [comment]
I think it could be a cool little addition for this app, it'll be an all-in-one and replace a lot of apps for people!

Additionally, just a question, do listens on ViTune count towards streaming numbers for the songs?

**Comment by 25huizengek1** [comment]
It seems YouTube Music doesn't have full support for this (yet) and we'll have to wait a bit until we could turn this into a usable thing in ViTune.

Closing for now.
