### ISSUE TITLE
Stop sleep timer after song ends UX/UI rework

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#261]
I was reading #210, and people pointed out that the "Stop sleep timer after song ends" feature is very hidden and could use some better implementation.

I mad a quick mockup to make it more visible to the end user, let me know what you think!

![Screenshot 2024-05-02 at 20-25-26 Group jpg (immagine JPEG 574 × 1280 pixel) - Riscalata (72%)](https://github.com/25huizengek1/ViTune/assets/108904135/fccb81e3-2b7e-4b6d-ab27-fc83e724435b)

After clicking the "Stop after song ends" button there is no need to confirm, the popup closes and the menu remains open with the time left.

**Comment by 25huizengek1** [comment]
Great suggestion, I'll add it.
