### ISSUE TITLE
Some generated playlists won't open in QuickPicks &/or related

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#262]
### Steps to reproduce the bug

1 - Choose Quick Picks
2 - Select the related playlist (generated)
3 - Wait until it load

### Expected behavior

Playlist should load

### Actual behavior

Infinite loading and never load the information

### Screenshots/Screen recordings

![image](https://github.com/25huizengek1/ViTune/assets/1917871/689bd8a5-7586-46f0-b4f5-da75b4b1ee9e)

![image](https://github.com/25huizengek1/ViTune/assets/1917871/88253c1b-0a9a-461f-8216-e3aa7a06bac9)

### ViTune version

1.0.3

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Running ViTune on Pixel 3a XL | Android 10

### Additional information

Attaching database to pick the related generated playlist 
[ViTune_backup_20240503060218.zip](https://github.com/25huizengek1/ViTune/files/15196634/ViTune_backup_20240503060218.zip)

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Fixed in af7987a2a9949a7cdf36ba10ece181c95d3cd850

**Comment by 25huizengek1** [comment]
Thank you for the suggestion though. I actually overlooked the fact that I initially set `shouldDedup` to `false` here.
