### ISSUE TITLE
Automatic horizontal scrolling for long playlist/song titles

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#263]
As of now, it's not possible to see the full name of an open playlist if the name is too long.

Similar situation inside the player, long artist and song names are only partially visible, unless the user scrolls them horizontally by hand.

I think implementing an auto scroller would improve the UX

**Comment by 25huizengek1** [comment]
Implemented.

**Comment by Monoxide8969** [comment]
Great stuff, thank you!

**Comment by Monoxide8969** [comment]
I must ask you to reopen this because the feature does not seem to work in v1.0.5 sadly

**Comment by 25huizengek1** [comment]
> I must ask you to reopen this because the feature does not seem to work in v1.0.5 sadly

I added the scrollable fading edges. There is no auto scroll
