### ISSUE TITLE
Getting video/song description for timestamps

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#273]
Since youtube api v1 doesn't provide description. And someone recently requested a feature related to podcast.

Youtube generated a linked timestamp if you do a correct description for songs/video compilations 
![image](https://github.com/25huizengek1/ViTune/assets/1917871/f95df1d6-141f-4d90-aac4-56cc634355e0)

It would be a next step (Also for podcast) to include a button where the user can pick the section (timestamp) to navigate through the song/video

Concept (In case the description match with the timestamp format)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/c7d7f885-f768-4993-b64c-face40f09eb8)

The user could choose the timestamp, and jump the right second.

**Comment by 25huizengek1** [comment]
I'll look into this. YouTube Music probably doesn't want you to do this, but it's worth a shot.

**Comment by 25huizengek1** [comment]
I understand the concept, thanks.

**Comment by 25huizengek1** [comment]
Not going to add as YouTube Music doesn't provide video descriptions.
