### ISSUE TITLE
Switching apps while lyrics are open, makes them stuck.

### ISSUE THREAD

**Issue by DavidRLTG** [25huizengek1/ViTune#274]
### Steps to reproduce the bug

1. Play a random song
2. Tap the album cover (To open lyrics, Synced lyrics)
3. Switch apps
4. Go back to ViTune

### Expected behavior

The lyrics keep moving, after I switch back to ViMusic.

### Actual behavior

They're stuck!

### ViTune version

v1.0.3

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14 GrapheneOS

### Device info

Google Pixel 8, GrapheneOS Latest, Android 14

### Additional information

This only happens *sometimes*, hence why I couldnt capture a screenshot. It's very odd.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
This makes no sense to me, because there is not a single clue in the codebase of why this could ever happen. Maybe it has to do with your vendor's lifecycle specifics, which is something I cannot influcence.

When you do have the opportunity to record it, please do so, because that way I at least have something to work with. I can't reproduce it, and I've never encountered anything like this, even when I'm using the app (and lyrics) every day.

**Comment by DavidRLTG** [comment]
> This makes no sense to me, because there is not a single clue in the codebase of why this could ever happen. Maybe it has to do with your vendor's lifecycle specifics, which is something I cannot influcence.
> 
> When you do have the opportunity to record it, please do so, because that way I at least have something to work with. I can't reproduce it, and I've never encountered anything like this, even though I'm using the app (and lyrics) every day.

I will try, sorry if I am confusing you or if the bug seems to not be real, but I can swear it really did happen once.

I assume its caused by GrapheneOS, then?
GrapheneOS is a bit special, as it optimizes the shit out of apps, Which broke one very much for me (Aliucord - it's only ~85% functional)
Maybe this could be it?

I was told its caused by GrapheneOS's Just In Time compilation or whatever
on first install / first boot after update, it does something like that to the apps or whatever..
I'm not a coder, so I really have no idea what to say of it

I doubt it's much help, but I could link there if it matters
You mentioned it could be caused by my ROM, so I am theorizing here, haha

The bug is quite rare, if I catch it again, I'll record the screen.

**Comment by 25huizengek1** [comment]
Thank you, I guess this could actually be the cause of this issue. It could of course still be something on my part, but this is definitely something to consider.

**Comment by DavidRLTG** [comment]
> Thank you, I guess this could actually be the cause of this issue. It could of course still be something on my part, but this is definitely something to consider.

I'll admit-
it only happened like once or twice, so it's a very rare bug for me
Ever since, I tried to replicate it, but it's so hard, my god xD
If I don't have it again, I may just close the issue myself in a few days and write it off as a rare small bug
This issue was oppened right when it happened, but I sadly did not record it

*Also, You're welcome!*

**Comment by DavidRLTG** [comment]
Captured the video! I am not schizophrenic after all xD
Just be warned, its an explicit song (unfortunately that is where I caught the bug so)
The video is 22mb, cant send on github.
Uh, how should I go about this?

**Comment by DavidRLTG** [comment]
Ah here, take this shady site that let me upload it xD
I hope it works:
https://ufile.io/7ljugcmd

**Comment by Enigma1309** [comment]
+1 
sometimes happens to me too, but switching song/collapsing the player makes this bug disappear
