### ISSUE TITLE
Including a solver n-parameter to avoid download throttling

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#277]
Since we can't still pre-cache large audios really fast (It takes a lot of time and sometimes they stuck at 97%-99%) it could be a good idea to implement the n-parameter solver to enable the fast download without throttling

There are some useful links
[YoutubeExtractor | Kotlin](https://github.com/maxrave-dev/kotlin-youtubeExtractor/blob/master/kotlinYoutubeExtractor/src/main/java/com/maxrave/kotlinyoutubeextractor/YTExtractor.kt)

[Go Unthrottle streams for all formats](https://github.com/kkdai/youtube/pull/244/commits/7f715155708a3445218c395393a17fd0fe781ae7)

**Comment by 25huizengek1** [comment]
I don't understand, I don't use an `n`-parameter.

This has something to do with working around rate limiting? I don't think that is a good idea...

**Comment by 25huizengek1** [comment]
Won't implement something that avoids ratelimits. I highly doubt whether that is legal, and if it is, it's still something that could get you blocked from the platform.
