### ISSUE TITLE
Ear rape or no sound in some scenarios

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#278]
### Steps to reproduce the bug

1. Go to some video result (There's no specific result video)
2. Play

### Expected behavior

Should be playing normally

### Actual behavior

Ear rape that could makes your ears bleed or simply no sound 

### Screenshots/Screen recordings

![image](https://github.com/25huizengek1/ViTune/assets/1917871/be6c1a19-47a6-4511-ae29-8364ec603b5d)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/7ea6b20a-fe94-4f49-a4e8-d79905037e2e)

### ViTune version

v 1.0.3

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Using Google Pixel 3a Xl running android 10

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
![Screenshot_20240509-185928.png](https://github.com/25huizengek1/ViTune/assets/50515369/38c954e4-54ec-4747-b611-8d597d5d84f4)

Found the culprit...

I guess we should just cap the loudness boost?
Or maybe YouTube just randomly changes the way this works for some specific videos and there's something else that causes this.

**Comment by 25huizengek1** [comment]
For now I guess you can just temporarily turn off loudness normalization

**Comment by 25huizengek1** [comment]
Fixed.
