### ISSUE TITLE
Question: How do I login through piped?

### ISSUE THREAD

**Issue by sidsharths1245** [25huizengek1/ViTune#279]
Do I need to create an account somewhere? I know it might be a dumb question but I've never used it before.

**Comment by Logan7899** [comment]
> Do I need to create an account somewhere? I know it might be a dumb question but I've never used it before. 

Yes u have to create an account

**Comment by Syntax-Err5** [comment]
>Yes u have to create an account

To add, you can create an account here:
https://piped.video/register

Then use those details to login using ViTune
