### ISSUE TITLE
New update has messed up a lot in stable version 

### ISSUE THREAD

**Issue by FaqatZubair1** [25huizengek1/ViTune#281]
### Steps to reproduce the bug

First bug I saw was in sleep timer
1) Hold the sleep timer
2) It won't show that it started a sleep timer 
3) Then, click on the sleep timer
4) It'll show if I want to remove my sleep timer 

### Expected behavior

It should start a sleep timer and show that the sleep timer has started

### Actual behavior

It doesn't show that sleep timer has started

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/161596117/c1f9eb7b-b628-4890-aae8-0eea8805011e

### ViTune version

1.0.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Moto

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by FaqatZubair1** [comment]
Second thing I noticed was while loading albums, it kinda keeps refreshing the content for a while even after loading it, which makes it unusable for some.

https://github.com/25huizengek1/ViTune/assets/161596117/d9ceede3-71e4-4f65-8a29-fc4fcea6fa40

**Comment by FaqatZubair1** [comment]
Just noticed #229
So, it seems the album problem is on YouTube end.

**Comment by 25huizengek1** [comment]
> Second thing I noticed was while loading albums, it kinda keeps refreshing the content for a while even after loading it, which makes it unusable for sometime.
> 
> https://github.com/25huizengek1/ViTune/assets/161596117/d9ceede3-71e4-4f65-8a29-fc4fcea6fa40
> 
> 

See #229

**Comment by 25huizengek1** [comment]
The sleep timer is something I'm still working on, I thought vfsfitvnm's impl doesn't make a lot of sense (at least anymore) and I tried to improve it. This is stuff that is still on my list, so not new to me, still thanks for reporting.

**Comment by Logan7899** [comment]
> Second thing I noticed was while loading albums, it kinda keeps refreshing the content for a while even after loading it, which makes it unusable for sometime.
> 
> https://github.com/25huizengek1/ViTune/assets/161596117/d9ceede3-71e4-4f65-8a29-fc4fcea6fa40
> 
> 

Yes i also faced that
