### ISSUE TITLE
Featured Section in Artist Page

### ISSUE THREAD

**Issue by anxiouslelimo** [25huizengek1/ViTune#287]
## Feature request: ...

In Artist Page a "Featured in" Tab. In this way a curated collection by Youtube is available in Artists Page. Requesting this as there is no current plans to implement Featured Playlists Tab in Search (https://github.com/25huizengek1/ViTune/issues/78)

**Comment by 25huizengek1** [comment]
I deliberately chose to remove Featured from Search, please read the issue.

As for the "Featured in" tab, there is no way for me to query something like that from YouTube, so I can't exactly add that. Thanks for your suggestion though!
