### ISSUE TITLE
Cache `quick picks` content

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViTune#288]
## Cache `quick picks` content

Caching the contents of `quick picks` and `discover` (optional) tabs will make the contents of the latter load faster. 

Additionally, it'll also be useful when there's no internet connection as it shows an empty page as of now.

<details>
<summary>Reference screenshots 👆</summary>

> ![Screenshot_20240514-140050](https://github.com/25huizengek1/ViTune/assets/87353286/f9cf153a-7ebc-4a4a-9446-165854d9fd30)
> ![Screenshot_20240514-140051](https://github.com/25huizengek1/ViTune/assets/87353286/257e1c2f-65ff-4bd5-8b4e-ac5d271ad8e9)

</details>

---

> [!TIP]
> The same feature is present in [Harmony Music](https://github.com/anandnet/Harmony-Music)
> 
> ![Screenshot_20240512-235522~2](https://github.com/25huizengek1/ViTune/assets/87353286/7adc7543-1c8c-46ff-bc3b-44893ff44478)

**Comment by genericbetatester** [comment]
Idk but is this really necessary?  Afaik it loads quite fast already. Imo it's okay already it doesn't need fixing

**Comment by vedxp** [comment]
> Idk but is this really necessary? Afaik it loads quite fast already. Imo it's okay already it doesn't need fixing

- Additionally, it'll also be useful when there's no internet connection as it shows an empty page as of now.

It'll be useful for those (including me) who use/browse the app without internet more frequently.
