### ISSUE TITLE
importing playlist

### ISSUE THREAD

**Issue by ansarimohammed422** [25huizengek1/ViTune#289]
## Feature request: ...

Importing playlisr from youtube music will be a great addition in this app as we cant do that roght now

**Comment by genericbetatester** [comment]
Simply "share" playlist from YT music to vimusic and you can add it from there

**Comment by ansarimohammed422** [comment]
No i have csv file of playlist
And that csv is from RIMusic

**Comment by genericbetatester** [comment]
I don't use rimusic but I believe that process should work for it. Don't export it to csv, Try sharing the playlist directly from Rimusic

**Comment by ansarimohammed422** [comment]
We cant share the playlist from RiMusic

**Comment by 25huizengek1** [comment]
Sorry, I'm not going to add support for another music app, that literally copies all non-ui code from me without credit (or consent to do so without credit)

If you want to import a playlist, share a playlist with ViTune or use Piped.

**Comment by ansarimohammed422** [comment]
The thing is that i am moving to ViTune from rimusic but i cant get my playlists on vitune

**Comment by 25huizengek1** [comment]
@ansarimohammed422 I understand. What I can do is make some dodgy import tool, but I'd have to maintain it and I don't know if that is feasible.
