### ISSUE TITLE
Pre-cache large songs in chunks

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#290]
Would be interested, based on podcast and large video music, that these elements could be pre-cached in chunks, since there's a limit of 10MB of download, using &range=x-y in chunks could help to accelerate the process, instead of waiting an eternity:

So, if the video is more than 10MB, ie: 30 MB, the precache should download it in 3 chunks
&range=0-10000000
&range=10000001=20000000
&range=20000001=30000000

Of course there should be limit (Not gonna download 200MB of precache single video)
More info at [reverse-engineering-youtube-revisited](https://tyrrrz.me/blog/reverse-engineering-youtube-revisited)

**Comment by 25huizengek1** [comment]
> What makes this behavior more useful is that the threshold doesn't actually apply to the overall size of the stream, but rather to the size of the requested part. In other words, if you try fetching only a portion of the data — using the Range HTTP header — YouTube will serve the corresponding content at full speed, as long as the specified byte range is smaller than 10 megabytes.

I actually did not know about this. I'll take a look.

**Comment by 25huizengek1** [comment]
There was already some chunking going on, but I added the `Range` header as specified in the blog, shouldn't harm anyone, right?

Interesting blog post though, maybe it's a good idea to revisit the way ViTune gets data from YouTube because they seem to approach it in a way that cleverly bypasses some restrictions (currently, we rely on Piped for that)

**Comment by 25huizengek1** [comment]
https://github.com/25huizengek1/ViTune/commit/6f1d8d68f3025cf5777d46693f3b9a1322fb348e#commitcomment-142163297

**Comment by 25huizengek1** [comment]
Added the parameter, along with some other changes: https://github.com/25huizengek1/ViTune/commit/b8da030b723978fe43e5a3a91111b62bf5de768f#diff-1c2a8756a2e5c82056fec3c2ca40bb6b28bdb332254ed1aaffc84e0eda41375fR1270-R1275
