### ISSUE TITLE
Play video for video track instead of audio only 

### ISSUE THREAD

**Issue by Sensex00** [25huizengek1/ViTune#291]
## Feature request: ...

Play video for video track instead of audio only such as music video, lyrics video
There same video player simpmusic on GitHub who uses same yt api . You can same thing to this app maybe the size of the app will be increased but you make as nightly build see what can think 
Here's an example 
![Screenshot_2024-05-17-06-13-16-549_com maxrave simpmusic](https://github.com/25huizengek1/ViTune/assets/168848690/fa93d751-5b84-4e34-8758-c9eeb39b716d)

**Comment by Sensex00** [comment]
Also It not provide all videos playback some are not played as video Please check the app once
Also you have included piped in your app does that anyway help to do this

**Comment by 25huizengek1** [comment]
I have already decided I'm keeping ViTune music-only.

See #240.
