### ISSUE TITLE
Bug on equalizer 

### ISSUE THREAD

**Issue by ninoashly** [25huizengek1/ViTune#293]
### Steps to reproduce the bug

bug on equalizer in playing music

### Expected behavior

unable to press

### Actual behavior

unable to use

### Screenshots/Screen recordings

![Screenshot_20240517-101538](https://github.com/25huizengek1/ViTune/assets/170062240/59e72bd8-dd65-4988-88e3-276c1982dd82)

### Logs

pls fox the bug soon thank you so much 🫡
![Screenshot_20240517-101538](https://github.com/25huizengek1/ViTune/assets/170062240/35f67986-f7db-4fa2-9924-7592885b621f)

### ViTune version

v1.0.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Nothing Phone 1

### Additional information

no more thanks

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Can reproduce (Nothing Phone 2a), so I'll look into this ASAP. I don't remember altering the equalizer code, very strange...

**Comment by 25huizengek1** [comment]
Fixed.
