### ISSUE TITLE
Some Suggestions - UI & Features

### ISSUE THREAD

**Issue by at-pyrix** [25huizengek1/ViTune#295]
## Feature request: ...

First of all, thank you for developing this app! It's very fast and smooth, however it does have it's imperfections.

### General Features

1. Ability to individually download songs.

2. Importing playlists and artists from YouTube Music (through Google Takeout). This is how NewPipe and LibreTube do it.

3. If possible, store the downloaded songs to local storage (e.g. the /Music folder).

### UI/UX

So, let me start off by saying that the UI is pretty neat and consistent. However, it's not perfect and there are some minor adjustments that could be made.

1. The icons are too small. Specially the icons in the now playing menu (3 dots). This is both from a UI and UX point of view.

2. When you 'like' a song through the Android notification, the heart stays the same. Ideally, it should have a white fill (like spotify). It would be nice to check if a song is in the Favourites and then use the icon accordingly.

4. Now I'm not sure for this one, but I don't think the dynamic colors are according to the Material You 3 color pallate. What I mean, is to "dim down" the colors to improve contrast. For some colors, there's barely any contrast between the background (especially amoled) and the text.

**Comment by 25huizengek1** [comment]
Thank you for your suggestions and appreciation. I do have some feedback though:

1. Already exists
2. Never thought about supporting Google Takeout, I'll look into this.
3. Not going to implement this, see #206

1. I think this is subjective. If the user experience is actually degraded because of this, you can always scale the UI in system settings. What size do you propose for the icons?
2. This is already implemented
3. I'm not implementing Material 3, I'm only using dynamic colors to fit in with ViTune's theming. You can change the darkness in the theme settings if you want.

**Comment by at-pyrix** [comment]
Thanks for taking the time to respond.


2. Yeah, and I think it's relatively easier to implement than Google Account Sync as a whole.

4.The icons aren't in good ratio to the text size. Here's what I mean:

   ![20240521_162721](https://github.com/25huizengek1/ViTune/assets/90166733/7acf04a2-aac5-4ae1-8f19-d4ae18a2c5a4)

   _They are hard to click on small devices_ 

   ![Screenshot_20240521-162229](https://github.com/25huizengek1/ViTune/assets/90166733/003b1eeb-25d3-4063-8929-ecdb3c049ff3)

  Other apps have a good `font-size : icon-size` ratio (iykwim)


![Screenshot_20240521-162802_ReVanced Extended Music](https://github.com/25huizengek1/ViTune/assets/90166733/5edd4867-7e5c-4f41-a489-50c2eedefc6e)

_From YouTube Music_

![Screenshot_20240521-162932_Gramophone](https://github.com/25huizengek1/ViTune/assets/90166733/619712e8-37d3-44a3-a418-a54c1efc8dd2)

_From [Gramophone](https://github.com/AkaneTan/Gramophone)_

> Also another suggestion, please change the position of the icons as follows:

   ![Screenshot_20240521-165230](https://github.com/25huizengek1/ViTune/assets/90166733/430123f3-e206-41b6-91db-bbe64400fca3)

my suggestion 😂

   ![20240521_165448](https://github.com/25huizengek1/ViTune/assets/90166733/b0630bde-3c71-4cc6-aa29-b1ff06a3842a)


  


5. NVM it was just a bug and got fixed once I restarted the device.


6. Hmm... understandable.

**Comment by 25huizengek1** [comment]
I think adding Google Takeout would be way too niche, since not many users are familiar with it. Anyways, let's continue the conversation in #199.
