### ISSUE TITLE
(Question) Has the KWGT support been removed? 

### ISSUE THREAD

**Issue by dainvincible1** [25huizengek1/ViTune#297]
The KWGT app is not recognizing ViTune as a music player.

**Comment by 25huizengek1** [comment]
There is no such thing as "KWGT support", but idk, KWGT recognizes ViTune for me.

If you are below Android 13, you have to enable "show thumbnail on lock screen" for KWGT to recognize the album art though.

**Comment by dainvincible1** [comment]
> There is no such thing as "KWGT support", but idk, KWGT recognizes ViTune for me.
> 
> If you are below Android 13, you have to enable "show thumbnail on lock screen" for KWGT to recognize the album art though.

Thanks for replying. Then perhaps something is wrong with the phone. Thanks.

**Comment by 25huizengek1** [comment]
Apparently KWGT assumes media players are `MediaBrowserService`s or something like that.

What Android version are you on?

**Comment by dainvincible1** [comment]
> Apparently KWGT assumes media players are `MediaBrowserService`s or something like that.
> 
> What Android version are you on?

My phone is on android 11. The other phone I tried is on android 14.

**Comment by Syntax-Err5** [comment]
I am having the same problem on Android 13. Before the rebrand to ViTune, KWGT would recognise it as ViMusic.

**Comment by 25huizengek1** [comment]
Fixed in f66f12d05bba745aa512b9e89bd0345028fcc176
