### ISSUE TITLE
Sometimes when i click on "other versions" of albums, it keeps on loading

### ISSUE THREAD

**Issue by dainvincible1** [25huizengek1/ViTune#305]
### Steps to reproduce the bug

Go to "The Weeknd" then click on "albums" then go to "Dawn FM" then go to "other versions"
It keeps on loading

### Expected behavior

it should not keep on loading, it should show contents if there's any. 

### Actual behavior

It kept on loading

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/127825700/a60540a0-f5a6-4330-92b5-8ce3012ee50e

### ViTune version

1.0.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 11

### Device info

Realme 5 pro

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Monoxide8969** [comment]
This happens to me too, I tested it on albums I know have alternative versions

**Comment by 25huizengek1** [comment]
#229, once again :(

**Comment by dainvincible1** [comment]
this issue is a bit different since the album loads for me but the "other version" page keeps on loading
