### ISSUE TITLE
[Bug] Song player not popping up after tapping on a song

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#309]
### Steps to reproduce the bug

1. Go on any section of the app that has songs
2. Tap on a song

### Expected behavior

The song player should appear

### Actual behavior

The song starts, but the player does not open. The minimized player only appears when the back button is pressed (the video ends a bit abruptly but you can still see it)

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/108904135/3c635a96-40ad-4be6-a04b-b4cd7d0d597a

### ViTune version

v1.0.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Samsung Galaxy A22 5G

### Upstream reproducibility

IIrc I had this bug since using ViMusic, but it's been a long time and I'm not really sure

### Additional information

I have no clue on what could possibly cause this and I've found no reliable way to reproduce it. It just happens every now and then.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
I was aware, but on very low priority. I'm currently migrating even more code, and it never seems to end. After that, I'll work on this again.

**Comment by 25huizengek1** [comment]
Thank you for reporting though

**Comment by XelXen** [comment]
Uhm, is this device-specific? I am not facing this issue in 1.0.4-REALEASE

**Comment by 25huizengek1** [comment]
Could be, it has to do something with the back handling.

**Comment by Monoxide8969** [comment]
> I'm currently migrating even more code, and it never seems to end. After that, I'll work on this again.

Sure, by all means take your sweet time. I opened the issue because I was finally able to record it, but it's definitely not an urgent bug, just a UX annoyance.

As always, thank you for mantaining the app

**Comment by JustRandomboy** [comment]
> I was aware, but on very low priority. I'm currently migrating even more code, and it never seems to end. After that, I'll work on this again.

Bro take you time and best of luck don't cause harm to your health stay safe 😌 🙏🏽

**Comment by PaolaAtilano** [comment]
> I was aware, but on very low priority. I'm currently migrating even more code, and it never seems to end. After that, I'll work on this again.

I understand, thanks so much for the reply! Keep up the good work and don't overwork yourself :'9

**Comment by 25huizengek1** [comment]
Fixed it.

**Comment by Monoxide8969** [comment]
Thank you!
