### ISSUE TITLE
Information about new releases from the marked artists

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#310]
I don't know if this is possible, but is there a way to be notified in some way about new releases from the artists you have tagged? Be it a notification or a hint through a dot or something similar.

In any case, this developer here has achieved this.

https://github.com/maxrave-dev/SimpMusic

I think such a function would be a great addition to this APP and you would be up to date with new releases from your favorite artists.

Thank you for the great app and your hard work.

**Comment by 25huizengek1** [comment]
SimpMusic seems to just poll Innertube. I guess that doesn't make sense at all because of networking/ratelimiting limitations.

Won't implement something like this for now. If YouTube decides to add notifications for this with official support of course I could reconsider.
