### ISSUE TITLE
Some ideas :]

### ISSUE THREAD

**Issue by col1iv** [25huizengek1/ViTune#312]
## Feature request: ...

1. Menu bar location.
It is a feature that lets you change where the menu bar is would be great. If the text is too - [ ] long to fit, maybe some icons would be nice, too.

2. Player size and lyrics button
To increase the cover art size.

3. Album and artist image customization

4. Download button at the player

5. Organizing the offline playlist songs by filters (name, date, artist, album, etc)
 
6. Sort music tab with filters as well: (All, downloaded, favorites,

**Comment by Monoxide8969** [comment]
1. Duplicate of #225 
3. Duplicate of #207 
5. Duplicate of #102 

Please review old issues before posting next time

**Comment by col1iv** [comment]
> 1 - Duplicate of #225 
> 3 - Duplicate of #207 (not exactly, but close enough)
> 5 - Duplicate of #102 
> 
> Please review old issues before posting next time

My bad!! But would it ever be possible to add:

Download button at player
Music tab filter sorting![Screenshot_20240525_140509.jpg](https://github.com/25huizengek1/ViTune/assets/152646768/4f3613f8-c867-4cad-a4e9-10f556e065f3)

**Comment by 25huizengek1** [comment]
Thank you for your suggestions, I do have some feedback though:

1. Not going to implement, see for example #225 
2. Exists
3. See #207
4. Exists
5. Already possible
6. Exists
