### ISSUE TITLE
Video thumbnail isn't properly rendered

### ISSUE THREAD

**Issue by PaolaAtilano** [25huizengek1/ViTune#314]
### Steps to reproduce the bug

If you choose to listen to a video, the thumbnail is cut short, and not properly rendered, making it look unfocused and awkward.

### Expected behavior

The video thumbnail should be properly rendered, giving it proper space so it isn't cropped awkwardly to fit into the dimensions of a song thumbnail.

### Actual behavior

The video thumbnail looks compressed and isn't properly rendered.

### Screenshots/Screen recordings

![Screenshot_2024-05-26-21-32-28-982_app vitune android](https://github.com/25huizengek1/ViTune/assets/106093120/0578e413-54d0-4196-a7b5-a4dc127f6363)

### ViTune version

v1.0.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

Redmi Note 9

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Not a bug, will take a look.

**Comment by Monoxide8969** [comment]
Making the app set the image to crop to height is probably good enough

**Comment by 25huizengek1** [comment]
Implemented.
