### ISSUE TITLE
Made an player redesign.

### ISSUE THREAD

**Issue by col1iv** [25huizengek1/ViTune#317]
Could be added as an extra player layout :)![Picsart_24-05-27_19-10-59-214.jpg](https://github.com/25huizengek1/ViTune/assets/152646768/14c9ff8e-2097-4930-8440-0212bc280b60)

**Comment by 25huizengek1** [comment]
Thank you for the design, but I don't understand. Why should the buttons take up less space and be placed awkwardly aligned to the left?

**Comment by col1iv** [comment]
> Thank you for the design, but I don't understand. Why should the buttons take up less space and be placed awkwardly aligned to the left?

well most of the times i use my phone on my left hand, and its a bit more of a help of having the buttons to a place where its easier to use, of course it's probably not a very innovative idea but it could be used as an accessibility function for left and right hand only :)

**Comment by col1iv** [comment]
> Thank you for the design, but I don't understand. Why should the buttons take up less space and be placed awkwardly aligned to the left?

oh, and it doesn't have to replace the two other layouts, it could be added as an extra layout :)

**Comment by 25huizengek1** [comment]
There is just so little difference, no? The only way I can justify this in my head is by calling it 'left-handed mode', but that also doesn't work, because of the like button all the way on the right.

**Comment by col1iv** [comment]
> There is just so little difference, no? The only way I can justify this in my head is by calling it 'left-handed mode', but that also doesn't work, because of the like button all the way on the right.

now that you're talking about it, i agree with you. maybe i was just reaching a little bit haha! sorry :]
