### ISSUE TITLE
Navigation Bar 

### ISSUE THREAD

**Issue by BesidesManthan** [25huizengek1/ViTune#320]
## Navigation bar at the bottom and streaming quality 

If the dev can add the option to get the navigation bar at bottom and streaming quality option the app will become the best out there right now I feel there is no one that can be said to be the best I hope dev takes this into consideration

**Comment by 25huizengek1** [comment]
This is just unneccesary in my opinion. This means I'll have to support two entire different kinds of layouts, the one with the vertical navbar, with the vertical structures layout/animations, and the horizontal bar, with all of the horizontal characteristics.

I think this is way too subtle for it to be viable to support. Besides, the vertical layout is something that makes ViTune/ViMusic unique in it's own way, IMO.

**Comment by BesidesManthan** [comment]
Hey I get it now felt it then but tes there is still one thing that is if
there can be a ui shift mode like the lyrics player of innertune is more
attractive can devs do it ?

**Comment by 25huizengek1** [comment]
@BesidesManthan What is it exactly that you are requesting here? Innertune has a different layout, please be more specific.

**Comment by BesidesManthan** [comment]
Not the layout I'm just asking for the lyrics player interface to be more
innertune like and having a streaming quality option as seen in the
pictures this is how I guess I can tell you if you want me.to be more
specific I'll just simply sum it up like when we toggle lyrics the
thumbnail must go blank and only lyrics should be there and audio quality
option will be appreciated too
