### ISSUE TITLE
Better Piped Integration

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#322]
I know I've asked about this feature before, maybe you'll think about it again.

Would it be possible to expand the Piped feature, i.e. create, delete and edit Piped playlists with ViTune? I think this feature would add even more value to the app.

**Comment by 25huizengek1** [comment]
Not going to do this, for the same exact reasons as before. This is not feasible with consistent state across all Piped playlists and the local versions of them. We'll keep Piped readonly for now.
