### ISSUE TITLE
Multi select 

### ISSUE THREAD

**Issue by TadeTorresMartin** [25huizengek1/ViTune#325]
## Feature request: ...

Hello, it's me, again
I've been using the app a lot and it's very good. My proposal is that you can select many items at the same time within a playlist/album this in order to be able to hide or add to a playlist or pre-cache for example

**Comment by 25huizengek1** [comment]
Good idea, but I don't know if this fits in ViTune's UI/UX, but I'll consider it.

**Comment by TadeTorresMartin** [comment]
> Good idea, but I don't know if this fits in ViTune's UI/UX, but I'll consider it.

Perhaps once a long touch is made one of the options is to start selection

**Comment by TadeTorresMartin** [comment]
> Good idea, but I don't know if this fits in ViTune's UI/UX, but I'll consider it.

Maybe once a long touch is made one of the options is to start selection
