### ISSUE TITLE
Shuffle button on music tab

### ISSUE THREAD

**Issue by col1iv** [25huizengek1/ViTune#326]
hiya, it's me again (sorry)

I've been using the app for over a week now, and i really loved it! one thing that's been bugging me is that the music tab doesn't have a specific shuffling/randomizer button. i don't know if there's already an issue to it or a solution to it already, but here's my vision of what it could be done.

since there are there are two search buttons at the music tab, we could take the big search button down there and turn it into a shuffling button.
![Picsart_24-05-31_14-55-39-930.jpg](https://github.com/25huizengek1/ViTune/assets/152646768/188011c3-2df4-48cc-8756-9da6fcf84fa5)

![Picsart_24-05-31_14-57-17-301.jpg](https://github.com/25huizengek1/ViTune/assets/152646768/8cb2411c-d6b7-4dfa-aba7-c7bc9125855d)

**Comment by genericbetatester** [comment]
Idk if you've noticed but opening the current queue reveals a shuffle button placed at the bottom right side of the screen, I believe that's what you are looking for

**Comment by col1iv** [comment]
> Idk if you've noticed but opening the current queue reveals a shuffle button placed at the bottom right side of the screen, I believe that's what you are looking for 
> 
> 

well, kind of? but wouldn't it be easier to just press a button for it to play a shuffled queue instead of clicking a song, opening the queue and then clicking to shuffle?

**Comment by genericbetatester** [comment]
It's already easy bro, 3 clicks isn't too hard is it. Besides, adding extra buttons clutters the clean minimal UI.

**Comment by col1iv** [comment]
> It's already easy bro, 3 clicks isn't too hard is it. Besides, adding extra buttons clutters the clean minimal UI. 

how would it clutter the ui, tho? it could also be added as a little small button next to these, too. i understand your concern about having a messy ui and everything, but i genuinely don't understand why to click on a song, get to the queue and then click to randomize instead having a button made for it. i do not want to come off as a rude person by questioning your opinion too. ![Picsart_24-05-31_21-00-52-223.jpg](https://github.com/25huizengek1/ViTune/assets/152646768/3ad14392-5e37-4d70-8dfd-746925835edb)

**Comment by 25huizengek1** [comment]
The UI in the top bar is already really crowded, adding another icon would make it even worse, and it wouldn't make sense as all buttons are for filtering/sorting, while saving only a few clicks.

I'm sorry, but I'll have to reject this for simplicity's sake.
