### ISSUE TITLE
[Feature Requests]: Precache + Notification + bug(s) + others

### ISSUE THREAD

**Issue by Enigma1309** [25huizengek1/ViTune#327]
#### Feature Requests

- The precache button should also cache the thumbnail of the song and if possible the synchronized lyrics (may fallback to un-synchronize lyrics if not found).

- When we enable  skip song if error, (Autoskip), change the notification priority from Urgent to medium or low by default (i can technically change it to low/medium from android settings but it would be better if it comes out of the box). because a notification sound in between the music listening ruins the experience.

- Hide the android top status bar when we are in fullscreen-lyrics mode, it becomes distracting on smaller devices.
- Talking about full-screen lyrics mode , it would be better if the lyrics mode turns off if the user clicks/taps out of the lyrics pop-up box. 

---

#### Bug(s) 
- a small bug i've noticed most probably after [this](87370d630032c332a9ec3d8c3d4ca8d0d7542b5c) commit , if we cache a big library and cancel the download (from notification) then try to cache anything else (say other playlist) then the cache button will do nothing. We have to manually force-stop the app for it to work again.

- Auto check for update feature don't works as expected (more info #319), i use fdroid client to update the apps but i've recommended this app to many of my friends.

**Comment by 25huizengek1** [comment]
Thank you for your suggestions, some feedback:

- This makes no sense in my opinion, please elaborate
- This is not intended, the player notification uses the lowest possible priority. Maybe your device uses some OEM-specific logic that deviates from stock Android that causes this behavior. When in doubt, please create a separate issue ticket because this could be seen as a bug
- Great suggestion, I'll implement it
- This is already the case
- Good call, I'll look into it
- I guess firing the update check on launch is not that bad, I'll consider it.

**Comment by Enigma1309** [comment]
> This makes no sense in my opinion, please elaborate

precaching is useful for downloading large playlist at once before going out (say to a place where we have no data connection) or just casually...the current precaching will only cache the music (which is okay) but it would be better if it catches the song thumbnail and lyrics too.



<details><summary>See the difference</summary>

![Screenshot_20240602-094331](https://github.com/25huizengek1/ViTune/assets/94917588/40b50823-cf86-44c9-90ca-fd5e3040e1a6)
   
![Screenshot_20240602-094700](https://github.com/25huizengek1/ViTune/assets/94917588/a256f302-5cee-47c5-bc96-b1164a11bca7)


</details>


> This is not intended

wait..i'll look more into it in the nightly version



> Talking about full-screen lyrics mode , it would be better if the lyrics mode turns off if the user clicks/taps out of the lyrics pop-up box.

>> This is already the case

This doesn't work as intended, i've to press back button to go out (instead of clicking out of box)

<details><summary>Video showcasing the same</summary>

https://github.com/25huizengek1/ViTune/assets/94917588/87129f06-64c9-4c1d-a64f-0b460edf633a


</details>




Thanks for looking into points 3,5 and 6...

also Thanks again for maintaining the app

**Comment by Enigma1309** [comment]
also a small bug(or is it?)

| Before (normal version)  | After (nightly) |
| -------- | ------- |
| ![Screenshot_20240602-101020](https://github.com/25huizengek1/ViTune/assets/94917588/f731ab60-4c93-46b8-8fbe-2b06d34a2cb2) | ![Screenshot_20240602-100805](https://github.com/25huizengek1/ViTune/assets/94917588/86497b9f-791c-48a9-9be7-03ad338d67a7)  |




dynamic aspect ratio is cool for yt videos but the thumbnail isn't getting sized by the height of image anymore(that's the problem) it fixed yt videos thumbs but somewhat broke normal thumbnails

**Comment by 25huizengek1** [comment]
It depends on the size of your device. It tries to get the most out of the space that is available.

**Comment by Enigma1309** [comment]
i hope you're talking about the thumbnail 

the thumbnail should resize using the height of the video also an option to turn off this feature should be there in setting --> appearance  --> Thumbnail aspect ratio 
a pop up should appear with the following values
- 1:1
- 16:9
- By Height (default)
- By Width (Use most of the space) 
- custom (this may or may not be necessary)

**Comment by 25huizengek1** [comment]
Since everything has been resolved, except for the aspect ratio thing, I guess closing this ticket in favor of #371 cleans things up a bit.

**Comment by Enigma1309** [comment]
Please consider other points too, like check for update and lyrics popup closed when clicked out also the autoskip song notification priority is set to high on every device I checked (have to manually change it on others)
