### ISSUE TITLE
Bigger font for song lyrics and exit fullscreen lyrics button

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#333]
I think the lyrics could use a bigger font, both the unsynced and the synced ones.

The fullscreen lyrics mode could especially benefit from this, displaying less text at once but in a more clear way.

I also noticed the lack of a button to exit the fullscreen lyrics mode, and because of this we need to tap on the three dots at the bottom right of the card to revert to the previous state. Adding a button to do so in the bottom left of the card (four arrows pointing inwards instead of outwards) would fix that.

**Comment by Syntax-Err5** [comment]
I'd also like to point out that, on previous versions of ViTune, having the synchronised lyrics open would prevent the screen time out, and this is no longer the case. It can get fairly annoying having to tap the screen every 30 secs while reading along with the lyrics.

**Comment by Monoxide8969** [comment]
This is a good point, it would be nice to see it implemented too

**Comment by 25huizengek1** [comment]
@Syntax-Err5 I deliberately removed it [here](https://github.com/25huizengek1/ViTune/commit/99b995f8e07aca274a6b6577b73ed3c660cf61ad#diff-74fd4ef5d38afdf68b0ef14c747185f6daff1bd7ab4a382cd3c650494c9f8543L352), because it didn't fit IMO. I'll add a toggle in the settings, I guess.

**Comment by 25huizengek1** [comment]
Forgot to close, my bad.

**Comment by Monoxide8969** [comment]
Idk why this is closed, nothing in the issue I raised has been addressed. May I ask you to reopen it?
