### ISSUE TITLE
You didn't have to change the pause/play button

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViTune#335]
## NOT A Feature request: ...

The new pause/play button has this sharp edges and it has also gotten thicker. Tbh, it looks awful and out of place compared to the gentle rounded look of other icons in the app. It looked fine before, you didn't have to change it. The old one looked better and I'll be glad to have that back

**Comment by Monoxide8969** [comment]
The play/pause button is rounded in both layouts. What are you referring to?

**Comment by genericbetatester** [comment]
Not here it doesn't , v 1.0.5
![Screenshot_20240605-110839](https://github.com/25huizengek1/ViTune/assets/140274753/1a433eca-1242-45f0-a7ae-e95ad8adcda5)
![Screenshot_20240605-110826](https://github.com/25huizengek1/ViTune/assets/140274753/556406c3-1d35-4900-809b-1cc0e42499be)

**Comment by 25huizengek1** [comment]
IMO this is way too subtle, but I currently use a Lottie animation in order to make it work. If you want, you could edit the [app/src/main/assets/lottie/play_pause.json](https://github.com/25huizengek1/ViTune/blob/master/app/src/main/assets/lottie/play_pause.json) file and open a PR.

**Comment by ZaldyColinares** [comment]
Go to settings>appearance and find "player layout" then set it to classic, easy profit. 🤑

**Comment by 25huizengek1** [comment]
No, that is not how it works. The button still gets animated.

**Comment by ZaldyColinares** [comment]
You meant the progress bar...?

**Comment by 25huizengek1** [comment]
Nope, the play/pause button's icon is the same for both layouts, so the animated button is there regardless of the layout
