### ISSUE TITLE
Adding search intents

### ISSUE THREAD

**Issue by Warden20** [25huizengek1/ViTune#336]
## Feature request: ...

Enabling the use of search intents by using a link like (https://www.music.youtube.com/results?search_query=%s) or (https://music.youtube.com/search?q=${1}&utm_source=opensearch) and opening it in Vitune instead of the browser.
### Other details
By enabling this integration, it could be used together with search applications or third party launchers, as in my case I use Kvaesitso.
My idea is that I make a search for example Sweet Victory and the search opens directly in Vitune facilitating its use.

**Comment by 25huizengek1** [comment]
Implemented, I'll record a demo for you, hang on.

**Comment by 25huizengek1** [comment]
https://github.com/25huizengek1/ViTune/assets/50515369/5118f3cb-6931-4a2f-a117-394f4571ca9a

**Comment by Warden20** [comment]
Thanks!
