### ISSUE TITLE
Able to visit artist

### ISSUE THREAD

**Issue by Jetliarm** [25huizengek1/ViTune#340]
## Feature request: ...

Able to Visit Artist by clicking the artist name

**Comment by genericbetatester** [comment]
I remember we had this feature, I guess it's broken

**Comment by 25huizengek1** [comment]
> I remember we had this feature, I guess it's broken 

Yes, it is, only in nightly for new songs though, I'll try to fix this asap

**Comment by genericbetatester** [comment]
I also noticed "more from <artist name>" is unavailable for some songs.

**Comment by 25huizengek1** [comment]
Fixed it, I accidentally just straight up forgot to include this for `Innertube.SongItem`s
