### ISSUE TITLE
An option to indicate which song is being played 

### ISSUE THREAD

**Issue by sidsharths1245** [25huizengek1/ViTune#343]
As of now there is no indication to show which song is being played. This gets troublesome when I search for a song and there are multiple versions of the same song or some other cases. It will be great if there is an icon indicating the current playing song. Here is a quick janky mockup I made for it.

![20240610_145604](https://github.com/25huizengek1/ViTune/assets/64619769/5f92e9e0-f77a-4df4-b6a2-6ec33b716770)

**Comment by xxpsychoo** [comment]
![IMG_20240610_222402.jpg](https://github.com/25huizengek1/ViTune/assets/124478368/71d9981f-985e-44fb-93fe-7c297e3bd08b)

This feature is already available if you click on the playlist. Please check it out.

**Comment by 25huizengek1** [comment]
I guess I could add it for every song item, but it's inconsistent for songs that already have an overlay on the album art, like in albums or play time.

**Comment by sidsharths1245** [comment]
@25huizengek1 I see this being implemented in the queue. BIG THANK YOU ♥️
![Screenshot_20240623-104255](https://github.com/25huizengek1/ViTune/assets/64619769/471ff30a-8867-4322-8c27-2b1c04279d1d)

But I don't see it anywhere else
![Screenshot_20240623-104255](https://github.com/25huizengek1/ViTune/assets/64619769/8ddf67ac-6682-47dc-8077-2e9891ae2cdb)
Are you planning on adding it later?

**Comment by sidsharths1245** [comment]
I see this being implemented in the queue, BIG THANK YOU ♥️
![Screenshot_20240623-104301](https://github.com/25huizengek1/ViTune/assets/64619769/b62d356e-581e-432a-8ad8-22d69fd7f4b8)

It's not implemented in other views though.
![Screenshot_20240623-104255](https://github.com/25huizengek1/ViTune/assets/64619769/cae06076-7a08-46a4-a33c-b8794bbd3beb)
Are you planning on adding it?
