### ISSUE TITLE
Add tranding music

### ISSUE THREAD

**Issue by xxpsychoo** [25huizengek1/ViTune#344]
## Feature request: ...

In the Discover tab, I would like to see an added list for songs that are currently hits or trending in our region.

It seems like it would make things more interesting.

**Comment by 25huizengek1** [comment]
I guess I could add the charts?
https://music.youtube.com/charts

**Comment by 25huizengek1** [comment]
Implemented.

**Comment by xxpsychoo** [comment]
Thank you for your response. I hope this app continues to improve, and I wish you health and success always.
