### ISSUE TITLE
Queue items overlap

### ISSUE THREAD

**Issue by NeeRaj-2401** [25huizengek1/ViTune#349]
### Steps to reproduce the bug

Adding songs by play next or enqueue or removal of items by swipes in queue

### Expected behavior

Shift of items with animation 

### Actual behavior

Queue items get Overlapped 

### Screenshots/Screen recordings

![Screenshot_20240612-084952](https://github.com/25huizengek1/ViTune/assets/88180887/85194e78-b13f-4167-9953-8eb0f7029737)

### ViTune version

1.0.5 nightly

### What kind of build are you using?

Nightly (F-Droid)

### Android version

14

### Device info

Nothing phone 2a

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
This specific nightly build was a bit broken for some reason. I'm currently waiting for Compose Animation to get these behaviors stable, after that, I'll have a look whether this needs more attention.
