### ISSUE TITLE
Add sorting to favorites tab

### ISSUE THREAD

**Issue by PaolaAtilano** [25huizengek1/ViTune#351]
hello! Thanks for the hard work, I have a suggestion for a future update. The songs tab is very organized and has a sorting section above, which is really useful, and I believe that same function could be added to the favorites tab, since it only has the sorting from latest to earliest, and it can be quite disorganized. Adding sorting would make it easier to find songs in the liked section instead of having to scroll in order to find them.

The songs tab with sorting function: 
![Screenshot_2024-06-12-11-01-42-270_app vitune android](https://github.com/25huizengek1/ViTune/assets/106093120/bb817416-3867-4771-860c-4ad27813037a)

The favorites tab section:
![Screenshot_2024-06-12-11-01-54-256_app vitune android](https://github.com/25huizengek1/ViTune/assets/106093120/37b724da-125a-4c2a-a53e-5d1ee0da8704)

**Comment by xxpsychoo** [comment]
It just makes the interface less simple, in my opinion. I think the current design is better. In fact, I believe it would be even better if it were made simpler.

**Comment by 25huizengek1** [comment]
It's already a filtered list of your favorites, so I won't complicate this further unfortunately, as this could cause confusion for users.

**Comment by PaolaAtilano** [comment]
I understand, thanks though!
