### ISSUE TITLE
Sleep timer causes app data to not load on next startup

### ISSUE THREAD

**Issue by Syntax-Err5** [25huizengek1/ViTune#354]
### Steps to reproduce the bug

1. Play any song
2. Start a sleep timer
3. Wait for timer to finish and app closes
4. Open ViTune again
5. App data (songs, playlists, artists, etc.) not showing

### Expected behavior

App data should be displayed as normal

### Actual behavior

Nothing shows. Going into Settings > Other > Troubleshoot > Reload App Internals & Kill App (usually) fixes the issue. 

### ViTune version

v1.0.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

I am using Oppo A54 5G, running ColorOS 13

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
#202 fixes this.
