### ISSUE TITLE
Support for Chinese

### ISSUE THREAD

**Issue by Tribbtsz** [25huizengek1/ViTune#359]
Hello!

Thank you very much for the development of this project. I would like to know if Vitune supports Chinese. If not, I would be very happy to contribute some help.

**Comment by Enigma1309** [comment]
you can edit https://github.com/25huizengek1/ViTune/blob/master/app/src/main/res/values/strings.xml and make a folder in the parent directory with the language you wanna and put the translated file in the same directory 

it's very well explained in [this](https://github.com/25huizengek1/ViTune/issues/178) issue

**Comment by Tribbtsz** [comment]
Thank you very much for the quick response. I will do my best to complete it.

**Comment by Tribbtsz** [comment]
#360 This is my first time making a PR. Please feel free to let me know if there are any mistakes or issues. Thank you!

**Comment by Enigma1309** [comment]
i appreciate the fast resolution of the issue <3
(although i don't understand Chinese so i can't verify but i'll try to approve it via google translate)

**Comment by Enigma1309** [comment]
yeah

**Comment by 25huizengek1** [comment]
@Tribbtsz Great! Thank you for your contribution. I'll have a look at the PR.
