### ISSUE TITLE
Playlists do not work

### ISSUE THREAD

**Issue by awwRoar** [25huizengek1/ViTune#363]
### Steps to reproduce the bug

1. Choose any playlist from 'Quick Picks' or 'Discover' (or search for any playlist)
2. Select one to open (any)
3. Just a blank screen with title 'Unknown'

### Expected behavior

The playlist should open and display normally. It was working fine until yesterday as far as I can remember. (I have just updated the app to v1.0.5 from v1.0.4 after playlists didn't work. Didn't work on v1.0.5 too)

### Actual behavior

Opens a blank screen with title 'Unknown' - screenshot below

### Screenshots/Screen recordings

![Screenshot_2024-06-22-17-35-53-164_app vitune android](https://github.com/25huizengek1/ViTune/assets/142053730/1f188933-e902-424f-9b2f-069f5bab571a)

### ViTune version

v1.0.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Xiaomi Pad 5 running HyperOS

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Apparently, YouTube changed their layout and therefore ViTune has to adapt. I'll push a fix tomorrow. I won't have time to code today.
