### ISSUE TITLE
Aspect ratio stuck in 16:9

### ISSUE THREAD

**Issue by MLGHerobrine** [25huizengek1/ViTune#369]
### Steps to reproduce the bug

Play any song after latest version (v1.0.6)

### Expected behavior

If the thumbnail is an album cover, it should be displayed in 1:1 (just like before the update). If the thumbnail is for a video, it should be in 16:9 or widescreen.

### Actual behavior

Instead, the thumbnail is always 16:9/widescreen, no matter whether it's a song or video. This results in some text / parts of the thumbnail being clipped as a 1:1 thumbnail is cropped to 16:9.

### Screenshots/Screen recordings

![Screenshot_20240624-113545](https://github.com/25huizengek1/ViTune/assets/67290917/cd54af22-5c7c-400e-8fd9-0135dedf2aab)
![Screenshot_20240624-113539](https://github.com/25huizengek1/ViTune/assets/67290917/6a7ca57d-0812-403d-bae4-42df5ac52dc5)
![Screenshot_20240624-113520](https://github.com/25huizengek1/ViTune/assets/67290917/823d77c8-38af-4b9c-8518-3d54b2fe94c5)

### ViTune version

v1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

Cat S22 Flip running stock Android 11

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
The aspect ratio is not defined. The thumbnail fills the width of the screen minus some padding, then renders the thumbnail in the original aspect ratio. If there is not enough space, like on your screenshot, the excess height gets cropped off.
