### ISSUE TITLE
Album don't work as intended.

### ISSUE THREAD

**Issue by H3T-Shah** [25huizengek1/ViTune#370]
### Steps to reproduce the bug

Listen to album. Remove some songs from cache by swiping L to R in Songs tab, where stats are shown.

### Expected behavior

All of the songs should be present.

### Actual behavior

Reopen the album, the song removed will not be present.

### Screenshots/Screen recordings

![Screenshot_2024-06-26-20-19-12-90_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/25huizengek1/ViTune/assets/135018516/f0e43339-026a-470c-a6bd-3f35279d6b5b)

### ViTune version

v1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Realme 12x, One UI 5

### Upstream reproducibility

I highly think, it must be reproducible in ViMusic case too.

### Additional information

As seen the in above pic, the info below album covers tells 4 songs but only 1 is visible.

This may be because, it's trying to read from cache and as I have cleared it, won't show in the album. To fix it, I need to clear cache but this will lead to delete all my pre-cached songs and It would be hassle to do it again.

Fix could be, making it fetch every time we try load an album and not from the cache.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
It does work as intended. Hiding a song means your phone doesn't know about it anymore.

**Comment by Syntax-Err5** [comment]
Sorry @25huizengek1, I don't think you understand the problem. When the song is "hidden", it disappears from the  artist's album page too. 

In the screen recording, I play the song "Heavy Games II" from an album with 11 songs, but after it's hidden, the song is no longer there and the album has 10 songs.


https://github.com/25huizengek1/ViTune/assets/123362106/5d0aa9b7-3c55-4f93-b808-5f26713e5e9f

**Comment by H3T-Shah** [comment]
> It does work as intended. Hiding a song means your phone doesn't know about it anymore.

But should be available in th album atleast it how else I'm able access it again if wanted!

@Syntax-Err5 thanks for the clarification!

That's the reason I stated to make album fetch it details every time and rather not read it from cache.
