### ISSUE TITLE
Can we change how Album works?

### ISSUE THREAD

**Issue by H3T-Shah** [25huizengek1/ViTune#372]
As I said in earlier in issue #370 
I was not able to clearly present what the issue was. My Bad.
As @Syntax-Err5 said it the [comments](https://github.com/25huizengek1/ViTune/issues/370#issuecomment-2194028593) it's impossible to play songs once we "hide" it. I get it the idea to hide can not be changed.

But what if we change how Album works, by making it to fetch details, every time we try to open and not reading it from cache. Then the issue is solved if we want to listen to the same song if we hide it.

**Comment by genericbetatester** [comment]
So that's what happened when I couldn't find all the songs in an album. I totally agree, it should fetch it from the cloud and not through the cache.

**Comment by Syntax-Err5** [comment]
I'd also like to see if fetching from the cloud would be possible for individual songs because some of my songs are missing data, such as album art, the "more from artist" button, and the "explicit" symbol.

**Comment by genericbetatester** [comment]
> I'd also like to see if fetching from the cloud would be possible for individual songs because some of my songs are missing data, such as album art, the "more from artist" button, and the "explicit" symbol.

**Comment by 25huizengek1** [comment]
As I pointed out in #370 (https://github.com/25huizengek1/ViTune/issues/370#issuecomment-2192597611), it does not make sense to change this behavior IMO.

**Comment by genericbetatester** [comment]
How does it not make sense? We should be able to find an artist's song irrespective of whether we removed it from our device.

**Comment by H3T-Shah** [comment]
> How does it not make sense? We should be able to find an artist's song irrespective of whether we removed it from our device.

I have already argued enough. I don't see any point in arguing anymore. 
Afterall it's his project and time. We just can't force anything on his project. 
We should and I respect the decisions he has made.
