### ISSUE TITLE
Automatic horizontal scrolling for long playlist/song titles not working

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#375]
### Steps to reproduce the bug

View a song/playlist with a long name

### Expected behavior

The text should slowly and automatically scroll horizontally

### Actual behavior

The text does not scroll

### ViTune version

v1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Samsung Galaxy A22 5G

### Additional information

Requested in #263, did not work in v1.0.5 either.

I asked before to reopen it, but you must have missed it. Feel free to reopen #263 and close this if you think it's better to do so.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
The text shouldn't automatically scroll, I think that's unintuitive and ugly, so this is definitely not a bug but rather personal preference.

You can scroll the text manually though...

**Comment by Monoxide8969** [comment]
> I think that's unintuitive and ugly

I feel the same about having to scroll the text manually, but you're the dev and you have the right to not want to implement this of course
