### ISSUE TITLE
Option to Disable Audio Focus

### ISSUE THREAD

**Issue by himadrisinha371** [25huizengek1/ViTune#376]
## Feature request: ...
This will allow music to play when another app requests audio focus. Eg:- During phone calls.

**Comment by Monoxide8969** [comment]
This would be a killer feature. I'd love it

**Comment by 25huizengek1** [comment]
Great idea, I'll work on this.

**Comment by 25huizengek1** [comment]
Implemented, please do note that this doesn't have much effect on Android 12 or later, since the system [enforces](https://developer.android.com/media/optimize/audio-focus) audio focus by default from that API version.
