### ISSUE TITLE
Keep screen awake (lyrics) not working properly

### ISSUE THREAD

**Issue by H0M3BR3WMA5TER** [25huizengek1/ViTune#380]
The new 'Keep Screen Awake' feature, when enabled, has kept my screen on even when I've turned off lyrics while listening to my queue.  I think the issue is with it only updating whether or not to keep the screen on when the next queue begins or when the current queue ends. Maybe changing over to an active check could stop it?

**Comment by 25huizengek1** [comment]
Very strange, I'll have a look at it after my break. (#382)
