### ISSUE TITLE
Player UI suggestions

### ISSUE THREAD

**Issue by CatGamer23** [25huizengek1/ViTune#386]
## Feature Request: Move around modern UI elements
---
This is specifically for the new modern UI.
Below is an example, and the repeat button can be added to the other menu, as it something that only needs to be toggled occasionally, and now constantly.

I like the big buttons as they make them really easy to press without looking, however, I also like to see the time left and the total length of the song. Which is what the 1 & 2 represent.

Underneath the song time bar? Not sure what it is called, would be the previous, play/pause, and next, in that order.

This could be another UI option in the settings, perhaps "Modern (Alternative)" or "Modern (Alt)"

When it comes to the tablet UI, the other menu icon, and the other icons on the bottom bar could get bigger, similar to the icons in the play/pause, skip, and previous buttons. And the bottom bar would be the thickness of 1.3 times the thickness of the play/pause button. The thickness would also apply to when the player is minimized, as I have found it hard to press without triggering the gesture control if decide to swipe it instead of tapping.

![Screenshot_20240711-095707](https://github.com/25huizengek1/ViTune/assets/44417404/3f34cc79-3581-490d-a785-11bd86c253b2)

**Comment by Sensex00** [comment]
Its already in there there 's no need to implement

Only thing need to change by your mean is change the loop in to heart

https://github.com/user-attachments/assets/6b4c375e-c2d1-4c4f-b2a7-4e837bf782b7

**Comment by Sensex00** [comment]
You can change to classic layout and there also heart I think there is no need to change

**Comment by Enigma1309** [comment]
i guess that's your personal preference,if you want you can create a pr...
just imagine someone else complaining about changing icon color of heart from red to purple or green..OR asking to move the thumbnail image down and controls up (i hope you get the point)
 [xkcd 927](https://xkcd.com/927/)

**Comment by 25huizengek1** [comment]
I'm sorry for my late response, but I agree with @Enigma1309 

> i guess that's your personal preference,if you want you can create a pr...
> just imagine someone else complaining about changing icon color of heart from red to purple or green..OR asking to move the thumbnail image down and controls up (i hope you get the point)
>  [xkcd 927](https://xkcd.com/927/)

I've got nothing to add, thank you @Enigma1309 for your assistance.
