### ISSUE TITLE
Sync playlist popup

### ISSUE THREAD

**Issue by UcraNerd** [25huizengek1/ViTune#387]
## Feature request: Add "playlist synced allert"

When I sync a playlist there should be at least a system popup message that says "playlist synced" or an internal one when it finishes.

Example (InnerTune):
![Screenshot_2024-07-11-17-46-42-470_com.malopieds.innertune.jpg](https://github.com/25huizengek1/ViTune/assets/102480084/38894758-2383-4fab-95af-fd4473a82861)

**Comment by 25huizengek1** [comment]
I guess I could add a loading indicator for the sync feature, a popup when it finishes seems counterintuitive though...
