### ISSUE TITLE
No lyrics icon

### ISSUE THREAD

**Issue by HungryhAr** [25huizengek1/ViTune#388]
### Steps to reproduce the bug

No lyrics icon shows while playback

### Expected behavior

Lyrics should show

### Actual behavior

No button or lyrics screen

### Screenshots/Screen recordings

![Screenshot_20240712_161627](https://github.com/user-attachments/assets/99c01a4e-e3b3-4455-8d1f-213ba48e3ed0)

### ViTune version

Newest

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

A14

### Device info

S21 Plus

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
First of all, this is not a bug, rather a feature request or question at most.

Just tap the album art to toggle lyrics.
