### ISSUE TITLE
Add metadata for song tracking apps

### ISSUE THREAD

**Issue by divno** [25huizengek1/ViTune#389]
## Feature request: Download song info metadata along with song 

Download metadata from YT music with the song (or at least the album metadata with the song title and artist of a song) so that apps that request metadata can access it easily without having to constantly edit.

**Comment by 25huizengek1** [comment]
I don't understand what you are requesting. Please explain.

**Comment by divno** [comment]
I'm not well versed in code but when downloading a song mp3 or m4a onto a device, there is song data attached to the file, I don't know if this is possible or not with ViTune as songs are temporarily stored in the cache, but since the music is technically "downloaded" would there be a way to add metadata to the song so that other apps can recognize albums? For now (I'm assuming) that ViTune separately downloads the audio, album art, and song and music title separately and then matches them to each song. 

I know I kind of repeated what I said above but I'm not too sure what other way to describe it, This screenshot shows an example of the kind of metadata I'm talking about.
![Screenshot_20240714-114629](https://github.com/user-attachments/assets/df7c29d8-b0b5-432b-9e66-df426affe671)

**Comment by 25huizengek1** [comment]
I don't understand. Other apps (except for Android Auto, Android Automotive, Google Assistant) cannot access ViTunes data as of right now. What are you requesting exactly?

**Comment by divno** [comment]
I'm unsure how to word it exactly since I don't know how it would work but one app that can access ViTune's data uses basically just the notification callback to copy song data like a scribbler for Last.fm

**Comment by 25huizengek1** [comment]
My bad, didn't mean to ref this issue

**Comment by 25huizengek1** [comment]
@divno I guess I could implement a content provider for ViTune's data with a permission system but there is no standardized way to provide this data on Android, so other apps won't be able to fetch the data from Android if they don't understand the contract with ViTune.

**Comment by 25huizengek1** [comment]
Not a viable feature for now
