### ISSUE TITLE
Discord integration?

### ISSUE THREAD

**Issue by ParussMan** [25huizengek1/ViTune#393]
Add option to link the app to your Discord so it shows what music is playing right now (sorta like Spotify does it).

**Comment by Logan7899** [comment]
> Add option to link the app to your Discord so it shows what music is playing right now (sorta like Spotify does it).

See vi tune is a open source app which fetch data from yt api so the discord ig will only support on original ytm app because vitune does not handle that

**Comment by ParussMan** [comment]
Damn :(

**Comment by 25huizengek1** [comment]
@ParussMan I'm sorry, @Logan7899 is not a maintainer and does not make such decisions, I've reopened this ticket, I'll look into it after my break (#382)

**Comment by ParussMan** [comment]
@25huizengek1 oh, my bad, didn't check it when I got the reply on my mail about this issue, thank you and have a nice break.

**Comment by 25huizengek1** [comment]
> This will help
> [Discord Rich Presence](https://github.com/dead8309/Kizzy)

@Solovertical I understand the way Discord's Rich Presence system works, thank you nonetheless.

**Comment by 770grappenmaker** [comment]
Discord appears to provide only two ways of setting the user activity:
- Pretending to be a Discord client (but this counts as a selfbot and is probably against the [Terms of Service](https://discord.com/terms))
- Using IPC (but the Android Discord app has no intents to support that, unlike the desktop application)

**Comment by 25huizengek1** [comment]
It seems like you're right. Unfortunately, that means I'll have to close. If you want to take the risk of violating Discord's ToS, you could use an external RPC manager.
