### ISSUE TITLE
Snapping for Sliders

### ISSUE THREAD

**Issue by Gmhfd** [25huizengek1/ViTune#394]
## Snapping for Sliders

Loudness normalization, bass bost etc. use Sliders, wich don't allow to set the values to nice even numbers.

Simply making the Sliders snap every 0.05 dezibels would fix this.

## Why is this an issue?
My perfectionism won't let me sleep with 0.04 db and it's such a simple change.

**Comment by Gmhfd** [comment]
E.g.: Here I am unable to set Loudness base gain to zero:

https://github.com/user-attachments/assets/fed04060-e4fe-4305-9bd8-1748adf17558

**Comment by Gmhfd** [comment]
Rotating my phone sideways I am able to set it to zero:
![Screenshot_20240721_182256](https://github.com/user-attachments/assets/0990db81-242a-4f47-b8cc-c90166e59c3d)
So this issue appears to be screen size dependent

**Comment by 25huizengek1** [comment]
@Gmhfd Great suggestion, I'll change this after my break (#389)
