### ISSUE TITLE
Lockscreen Media Art support on A13 & above.

### ISSUE THREAD

**Issue by epicX67** [25huizengek1/ViTune#396]
### Steps to reproduce the bug

I won't say it's a bug. 
But I want to let you know that,
Lockscreen Media wallpaper option in settings is not visible on devices running A13 or above. I saw there a condition mentioned in code when isAtLeastAndroid13 <> true then lockscreen option should not display on settings. Is there specific reason for this option?

I removed that condition from every place where mediametadata was set but I am still not able to see lockscreen Media wallpaper on my device. I assume this issue probably related to my device only. 
My device - Motorola G82
API - 33 (Running A13)
And it does have Peak display where it shows lockscreen Media wallpaper with controls.

I did little bit for try and I was successfully able to manage lockscreen Media wallpaper to work. But I am not fully sure if that is compatible with other devices or not.

So what I did to fix the issue,
I set the metadata on METADATA_KEY_ALBUM_ART instead of METADATA_KEY_ART.
And I removed A13 restrictions for my testing purpose and it now displays the art.

I attached before and after photo of the change.
Before,
![Photo0142_012338](https://github.com/user-attachments/assets/01f01f57-132c-4b01-b32d-fdb3e3294700)

After,
![Photo0140_012321](https://github.com/user-attachments/assets/d211319b-defd-42fe-9a80-a20052e33413)

### Expected behavior

Lockscreen Media Wallpaper option should display on latest Android running 13 or above.
Lockscreen Media wallpaper should work on all Motorola devices along with other devices running Android 13 or more.

### Actual behavior

Lockscreen Media wallpaper option is not visible on devices running A13 or above.
Lockscreen Media wallpaper is not working on Motorola devices.

### ViTune version

v1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Motorola G82
Also tested on Motorola G52

### Additional information

I checked same thing on other apps like YouTube music, Spotify & AIMP. Lockscreen Media wallpaper does show up in lockscreen on my G82.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Enigma1309** [comment]
> Lockscreen Media wallpaper is not working on Motorola devices.

bit of an overestimate cause lock-screen media works on my motoG4+ and motoG5+(i hope you're talking about wallpaper stuff) 

both running android 8.1

**Comment by epicX67** [comment]
> > Lockscreen Media wallpaper is not working on Motorola devices.
> 
> bit of an overestimate cause lock-screen media works on my motoG4+ and motoG5+(i hope you're talking about wallpaper stuff)
> 
> both running android 8.1

Yes, lockscreen Media works flawlessly but thumbnail doesn't appear. 
Here we have two issue.
One : Lockscreen media wallpaper functionality is not turned on in Android 13 or above.
Two : Even after removing the condition, it's not working. 

So maybe on lower Android versions it's working fine. Also are you saying about peak display of motorola right?

**Comment by 25huizengek1** [comment]
@epicX67 Thank you for your bug report. The Android version check is there to prevent users from turning off the album art on higher Android versions, so that doesn't matter for this issue.

I guess also adding `METADATA_KEY_ART` should fix it, it at least wouldn't hurt for compatibility with vendors who use that key, for some reason.

I'll look into this after my break. (#382)
