### ISSUE TITLE
The rerurned  video id doesnt  match  the  requested   one

### ISSUE THREAD

**Issue by fitisiko** [25huizengek1/ViTune#398]
### Steps to reproduce the bug

I tried to listen to an album that is not available in my country using a VPN and when selecting a track/album I get an error [The rerurned video id doesn’t match the requested one] but i can start this track in YTM

### Expected behavior

play music

### Actual behavior

it didnt play music

### Screenshots/Screen recordings

![image](https://github.com/user-attachments/assets/b1db0390-609c-4cda-a93f-8b3d560bb62f)

### ViTune version

V1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android13

### Device info

realme c33

### Additional information

in vimusic it worked

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Very strange, please try this for the same video in the same conditions on both ViTune and YouTube Music. And can you please provide logs as instructed by the issue template?

**Comment by fitisiko** [comment]
> Very strange, please try this for the same video in the same conditions on both ViTune and YouTube Music. And can you please provide logs as instructed by the issue template?

I tried many vpn services and locations. As it turned out, the problems lie in the vpn location, for example, in the UK this error appears, but not in the US. What about making an error in another vitune - this error appears with the same location if you run directly through YTM then there are no problems

**Comment by fitisiko** [comment]
> Very strange, please try this for the same video in the same conditions on both ViTune and YouTube Music. And can you please provide logs as instructed by the issue template?

![image](https://github.com/user-attachments/assets/fbb035f0-2027-48a7-b6d6-508e96011c2f)
� � � � � � �                                                                                                                                                                                                                                                                                                                                                                                                        � ��   �,     BNDL        0           B f v w t 8 q N X N s       2       �   BNDL        0           I .   F l i g h t   o f   t h e   N a v i g a t o r         1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             5 : 4 5         e x p l i c i t             � ��   �  �   BNDL        0           A _ e U H 8 r b 9 9 s       2       �   BNDL        0           D e a t h   B y   N u m b e r s         1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             0 : 4 4         e x p l i c i t             �u��   �l �   BNDL        0           F R h a Y 5 1 e d E M       2       �   BNDL        0           I I .   N o   E x i t       1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             2 : 5 2         e x p l i c i t             �y��   �t �   BNDL        0           X Z M h Z m i k O b A       2       �   BNDL        0           I .   T h e   P a r t y         1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             1 : 3 2         e x p l i c i t             �-��   �\     BNDL        0           t 6 m D U G i K V u g       2       �   BNDL        0       &   P l a y i n g   A r o u n d   B e f o r e   t h e   P a r t y   S t a r t s         1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             0 : 5 5         e x p l i c i t             �i��   �T �   BNDL        0           N 3 G Y g c 1 4 m R 4       2       �   BNDL        0           3 0 0 5         1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             3 : 5 5         e x p l i c i t             �%��   �L     BNDL        0           m W j Y u G K A X M M       2       �   BNDL        0       #   I V .   S w e a t p a n t s   ( f e a t .   J a s o n   M a r t i n )       1           C h i l d i s h   G a m b i n o         b       �       a n d r o i d . n e t . U r i $ S t r i n g U r i       �   https://lh3.googleusercontent.com/RJPprGvjwllbkjvoZqg2hrCAPykJX6-5KQ4h5iAigAYSaBxhc__XVJs24Cn8CnCOAU5ug9W_VeQ7o4TO4g=w544-h544-l90-rj       r s         X   BNDL        d u r a t i o n T e x t             3 : 0 1         e x p l i c i t

**Comment by ajk-47** [comment]
This problem happens to me too. I have been unhearting and re-searching for the song lately, which has been working, until the song "mango" wouldn't play at all today, even though it plays on ViMusic just fine (neither are cached).

**Comment by ajk-47** [comment]
![Screenshot_20240806-150309](https://github.com/user-attachments/assets/4e29a726-9a7c-47dc-9167-55bb903572c0)
![Screenshot_20240806-150253](https://github.com/user-attachments/assets/87fbac52-5397-4621-9256-80db7c0ab14a)

**Comment by 25huizengek1** [comment]
The available content on YouTube Music (and thus ViTune) differs between countries. In other words, some songs are blocked from certain countries. This means that when you're using a VPN, some songs may become unavailable. Some VPN providers are even blocked entirely from YouTube. This is why I've added the 'I am able to reach YouTube Music through the official app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)' box to the issue template checklist. Please refrain from filing a bug report while using a VPN in the future.
