### ISSUE TITLE
The ability to reorder songs in favorites 

### ISSUE THREAD

**Issue by findirfin** [25huizengek1/ViTune#401]
## Feature request: 

It would be very helpful to have the ability to reorder songs in favorites just like I can in other playlists.

**Comment by 25huizengek1** [comment]
Somewhat a duplicate of #351.

Not going to implement something like this as favorites are supposed to be a sorted list of liked songs, and I won't complicate this further.

You can always create a playlist from your favorites if you really want to reorder them.
