### ISSUE TITLE
make the player pop up smooth

### ISSUE THREAD

**Issue by sebsebseb9b** [25huizengek1/ViTune#403]
### Steps to reproduce the bug

Play a song

### Expected behavior

I wish the player just went up smoothly

### Actual behavior

It jumps open with no animation

### ViTune version

1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

15

### Device info

s24 ultra

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
First of all, not a bug.
Second, this is already implemented. Just make sure your animations are not turned off in settings.

**Comment by sebsebseb9b** [comment]
Yea so I runs off your phone animations scale. I made my phone animations
faster but what hoping for independent animations in the app itself
