### ISSUE TITLE
Cant Change Order of queue in v1.0.7

### ISSUE THREAD

**Issue by habnixzutun** [25huizengek1/ViTune#405]
### Steps to reproduce the bug

 Ever since i upgraded from v1.0.6 to v1.0.7, I have Not been able to find a way to change the order of songs in the currently playing queue

### Expected behavior

The order of the next songs is changed

### Actual behavior

The App Crashes instantly, everytime

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/af7a77d7-fee8-44c3-86a0-8cfaea444ee2

### Logs

![Screenshot_2024-08-10-00-14-21-646_com.miui.bugreport.jpg](https://github.com/user-attachments/assets/0586675d-b352-4575-9c91-4de2fe04f518)

(I'm so sorry the logs are a screenshot but I couldnt copy them)

### ViTune version

v1.0.7

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Xiaomi 13T Pro HyperOS 1.0.6.0 / Android 14
Samsung S9+ OneUI 6.1 / Android 14 (root)

### Additional information

It doesnt seem to matter how many Songs are in the queue

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
@habnixzutun I built a rolled back version of ViTune, with the same version name/code as the impacted version, that way you can roll back and use ViTune while I fix this issue.

For more information: https://github.com/25huizengek1/ViTune/releases/tag/v1.0.7

**Comment by habnixzutun** [comment]
Thank you so much

**Comment by 25huizengek1** [comment]
Fixed it, ViTune should be ready for Android 15 now. I'm sorry for the inconvenience.
