### ISSUE TITLE
Lyrics text size

### ISSUE THREAD

**Issue by Abhishekahhi-io** [25huizengek1/ViTune#406]
## Feature request: .

Please add an option to increase lyrics text size

**Comment by OutshineIssue** [comment]
It would be great if the lyrics could take up more of the player (without overlapping the play/pause), not just the tiny album cover @25huizengek1

**Comment by 25huizengek1** [comment]
@Abhishekahhi-io Just increase the text size in your system settings, that should do.

@OutshineIssue Tap the 'expand' icon in the bottom-left corner of the lyrics.

**Comment by OutshineIssue** [comment]
That overlaps the play/pause and the rest of media controls.
