### ISSUE TITLE
Import and export format issue 

### ISSUE THREAD

**Issue by Pranav9045** [25huizengek1/ViTune#407]
The import and export format it has doesnt support .xml, CSV or any other format which doesnt allow me to import or either export my playlist from the vitune app. The export file has size of 0B which I don't know why and says BIN(format)
I don't know much about how to convert it to other formats, it would be easier if the app would support .xml or CSV format 

thank you 

regards, Pranav

**Comment by H3T-Shah** [comment]
> The import and export format it has doesnt support .xml, CSV or any other format which doesnt allow me to import or either export my playlist from the vitune app. The export file has size of 0B which I don't know why and says BIN(format) I don't know much about how to convert it to other formats, it would be easier if the app would support .xml or CSV format
> 
> thank you
> 
> regards, Pranav

The export is SQL database.
You can find various program on pc to view and change the tables

**Comment by 25huizengek1** [comment]
@H3T-Shah is right. It just exports as a SQLite database, which you can query data from using any SQLite client.
