### ISSUE TITLE
Reordering quick controls like the ones on the playlists tab but within the offline and favourites playlists

### ISSUE THREAD

**Issue by coopershaw1116** [25huizengek1/ViTune#409]
## Feature request:

Reordering quick controls like the ones on the playlists tab but within the offline and favourites playlists

![Screenshot_20240816_072705.jpg](https://github.com/user-attachments/assets/aad943da-e2de-4f81-9a16-bcb182f047f4)

 playlist![Screenshot_20240816_072715.jpg](https://github.com/user-attachments/assets/231266ac-f9ba-4602-b8c8-26327bf54834)

![Screenshot_20240816_072723.jpg](https://github.com/user-attachments/assets/071bc537-d9d9-4ef5-bdf1-fc8e3a2cf4f1)

**Comment by siggi1984** [comment]
> ## Feature request:
> 
> Reordering quick controls like the ones on the playlists tab but within the offline and favourites playlists
> 
> ![Screenshot_20240816_072705.jpg](https://private-user-images.githubusercontent.com/118646792/358399998-aad943da-e2de-4f81-9a16-bcb182f047f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjExMjEsIm5iZiI6MTcyMzc2MDgyMSwicGF0aCI6Ii8xMTg2NDY3OTIvMzU4Mzk5OTk4LWFhZDk0M2RhLWUyZGUtNGY4MS05YTE2LWJjYjE4MmYwNDdmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMjI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjQ2YWQzOTM5ZDBlNTJiNWY0ZmU2ZjQxNDkyYzBiMmY4MTk1MmUxNWE0MWRlZDcyNmZhNTI1NTQ3OGE3YjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSeuRL2upRnehbs3Ym-vW9vG1TbsEOvbYc-mXgMW7LM)
> 
> playlist![Screenshot_20240816_072715.jpg](https://private-user-images.githubusercontent.com/118646792/358399999-231266ac-f9ba-4602-b8c8-26327bf54834.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjExMjEsIm5iZiI6MTcyMzc2MDgyMSwicGF0aCI6Ii8xMTg2NDY3OTIvMzU4Mzk5OTk5LTIzMTI2NmFjLWY5YmEtNDYwMi1iOGM4LTI2MzI3YmY1NDgzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMjI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjhlNThhMzYxYjY3ODU3NzdkOGJjOGRlNTdmZTVlNThhYjRjNjc5NWFkZTc5Yzc1NWFmMmQwMzYwNzcyZDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2NEHrSqM9qhdM8BJyE3BlnddRWkRaUZzcZJYkql-VWE)
> 
> ![Screenshot_20240816_072723.jpg](https://private-user-images.githubusercontent.com/118646792/358399997-071bc537-d9d9-4ef5-bdf1-fc8e3a2cf4f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjExMjEsIm5iZiI6MTcyMzc2MDgyMSwicGF0aCI6Ii8xMTg2NDY3OTIvMzU4Mzk5OTk3LTA3MWJjNTM3LWQ5ZDktNGVmNS1iZGYxLWZjOGUzYTJjZjRmMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMjI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2YzOWM3OTEwMTA0N2QyNDVmZTMxNGE3Yzg1YTIxNmZkMTNlYTI3NTAxNDdjYjY1OTI3ZjU1NTBmMWEzNGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QofLT4UmPNOTxWo0WwsGZFEl55_bqLNwWjZorykn3ow)


![302086698-72454446-f7a3-43ac-918f-8b69f3666fb9](https://github.com/user-attachments/assets/14c2e446-30a5-4f4b-8f4a-a45c4c35c53b)

I think if we could get these sorting options in the self-created playlists, that would be great. In my opinion, the Favorites, My Top x and Offline playlists don't need any sorting options, they're fine the way they are.

**Comment by cooper-shaw75** [comment]
> > ## Feature request:
> > 
> > Reordering quick controls like the ones on the playlists tab but within the offline and favourites playlists
> > 
> > ![Screenshot_20240816_072705.jpg](https://private-user-images.githubusercontent.com/118646792/358399998-aad943da-e2de-4f81-9a16-bcb182f047f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjExMjEsIm5iZiI6MTcyMzc2MDgyMSwicGF0aCI6Ii8xMTg2NDY3OTIvMzU4Mzk5OTk4LWFhZDk0M2RhLWUyZGUtNGY4MS05YTE2LWJjYjE4MmYwNDdmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMjI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjQ2YWQzOTM5ZDBlNTJiNWY0ZmU2ZjQxNDkyYzBiMmY4MTk1MmUxNWE0MWRlZDcyNmZhNTI1NTQ3OGE3YjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CSeuRL2upRnehbs3Ym-vW9vG1TbsEOvbYc-mXgMW7LM)
> > 
> > playlist![Screenshot_20240816_072715.jpg](https://private-user-images.githubusercontent.com/118646792/358399999-231266ac-f9ba-4602-b8c8-26327bf54834.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjExMjEsIm5iZiI6MTcyMzc2MDgyMSwicGF0aCI6Ii8xMTg2NDY3OTIvMzU4Mzk5OTk5LTIzMTI2NmFjLWY5YmEtNDYwMi1iOGM4LTI2MzI3YmY1NDgzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMjI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjhlNThhMzYxYjY3ODU3NzdkOGJjOGRlNTdmZTVlNThhYjRjNjc5NWFkZTc5Yzc1NWFmMmQwMzYwNzcyZDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2NEHrSqM9qhdM8BJyE3BlnddRWkRaUZzcZJYkql-VWE)
> > 
> > ![Screenshot_20240816_072723.jpg](https://private-user-images.githubusercontent.com/118646792/358399997-071bc537-d9d9-4ef5-bdf1-fc8e3a2cf4f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjExMjEsIm5iZiI6MTcyMzc2MDgyMSwicGF0aCI6Ii8xMTg2NDY3OTIvMzU4Mzk5OTk3LTA3MWJjNTM3LWQ5ZDktNGVmNS1iZGYxLWZjOGUzYTJjZjRmMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMjI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2YzOWM3OTEwMTA0N2QyNDVmZTMxNGE3Yzg1YTIxNmZkMTNlYTI3NTAxNDdjYjY1OTI3ZjU1NTBmMWEzNGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QofLT4UmPNOTxWo0WwsGZFEl55_bqLNwWjZorykn3ow)
> 
> I think if we could get these sorting options in the self-created playlists, that would be great. In my opinion, the Favorites, My Top x and Offline playlists don't need any sorting options, they're fine the way they are.
> 
> ![302086698-72454446-f7a3-43ac-918f-8b69f3666fb9](https://github.com/user-attachments/assets/14c2e446-30a5-4f4b-8f4a-a45c4c35c53b)
> 

No we DONT want those IN REGULAR PLAYLIST that defeats the purpose of a playlist, they should be added ti the OFFLINE AND FAVOURITES PLAYLISTS since you can reorder them, adding this would make it easier to pick the song you wanna play from those playlists.

**Comment by 25huizengek1** [comment]
@coopershaw1116 I'll put this on low prio. I think this could work, I'll see.

**Comment by coopershaw1116** [comment]
> @coopershaw1116 I'll put this on low prio. I think this could work, I'll see.

Awesome! I really hope a version of this gets added it would be so helpful.

I've also seen I few people ask for an option to display the Pre-Cache and Add To Playlist buttons on the quick bar in the player, I personally think it's pretty good idea wbu?
