### ISSUE TITLE
Some songs are played quietly

### ISSUE THREAD

**Issue by AktiVCTAC** [25huizengek1/ViTune#411]
### Steps to reproduce the bug

For some reason, some songs are played quietly, although this was not the case before

### Expected behavior

The song had a normal sound

### Actual behavior

The quiet sound of the song

### ViTune version

v.1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

Poco x3 pro

### Checklist

- [x] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by AktiVCTAC** [comment]
> ### Steps to reproduce the bug
> I recently listened to the album and one of the songs had poor sound quality, as I understood this audio from the music video. Is there a way to remove a music video??
> 
> ### Expected behavior
> Play music not from a music video
> 
> ### Actual behavior
> Low quality sound
> 
> ### Screenshots/Screen recordings
> _No response_
> 
> ### Logs
> _No response_
> 
> ### ViTune version
> v.1.0.6
> 
> ### What kind of build are you using?
> Release (GitHub / F-Droid)
> 
> ### Android version
> Android 12
> 
> ### Device info
> Poco x3 pro
> 
> ### Upstream reproducibility
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Checklist
> * [x]  I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
> * [x]  I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
> * [x]  This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Turn on normalization in Settings --> Player --> Loudness normalization. This accounts for the fact that every song is mastered differently and is louder/quieter than other songs as a result.
