### ISSUE TITLE
I Pre-cached some songs in offline and after 1 day or 2 days is disappeared 

### ISSUE THREAD

**Issue by omarblack21** [25huizengek1/ViTune#412]

**Comment by 25huizengek1** [comment]
@omarblack21 Please fill in the [bug report](https://github.com/25huizengek1/ViTune/issues/new?assignees=&labels=bug&projects=&template=bug_report.yaml) form, as I can't investigate this issue based on nothing.

That said, I have precached my entire library before and it still works fine, so this seems like a bug related to some device-specific storage behavior. Just a guess though.
