### ISSUE TITLE
Custom album covers

### ISSUE THREAD

**Issue by Dioramoz** [25huizengek1/ViTune#414]
## Feature request: Custom album covers

Can you please add a feature to choose a cover for album from device or from a song in this album?  Thank you.

**Comment by 25huizengek1** [comment]
Why does this make sense? Please elaborate.

**Comment by OutshineIssue** [comment]
This makes more sense for songs from the videos tab that use weird thumbnails, not the actual, real album covers.

**Comment by 25huizengek1** [comment]
I don't know if this makes sense. I'm aiming to accurately reflect the actual data from YouTube.
