### ISSUE TITLE
Pre cache all songs in "Songs" menu

### ISSUE THREAD

**Issue by Mirko117** [25huizengek1/ViTune#415]
I have been using ViMusic for past few months and I just switched to ViTune because I saw it has more features and it's up to date. I important database from ViMusic so I have all my playlists, but now I don't have cached songs. 

I saw there is option to pre cache all songs in playlist, but there is no option to do the same for all songs in "Songs" menu/section, so I thought that adding that would be a nice feature.

**Comment by Syntax-Err5** [comment]
I think this is a bit overkill. I have over 2000 songs in the "songs" menu which would take 6-7 GB of storage to cache.

Alternatively, you can just pre-cache your "favourites" playlist. Or if you really wanted to, you could play a song from the "songs" menu and make a new playlist with queue by pressing the song count, then cache that playlist.

**Comment by NeeRaj-2401** [comment]
> I saw there is option to pre cache all songs in playlist, but there is no option to do the same for all songs in "Songs" menu/section, so I thought that adding that would be a nice feature.


1. Play any song from songs tab
2. Open queue
3. Click on 'x songs' button which shows total songs in current queue
4. Add that queue to a new playlist temporarily 
5. Cache that playlist

**Comment by 25huizengek1** [comment]
@Syntax-Err5, @NeeRaj-2401 Thank you for your assistance. I also think this would be way too overkill. If you wanted to do this, @NeeRaj-2401's solution will do.
