### ISSUE TITLE
Playback Error and Video ID Mismatch Issue

### ISSUE THREAD

**Issue by asxhelr657** [25huizengek1/ViTune#418]
### Steps to reproduce the bug

1. Open ViTune application.
2. Play a song from the library.

### Expected behavior

The selected song should start playing without any errors

### Actual behavior

Upon attempting to play a song, the following error messages appear:
1. "The returned video ID doesn't match the requested one"
2. "An unknown playback error has occurred"

These errors occur inconsistently, with the first message being more prevalent

### ViTune version

v1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

I am using a Moto G9 Play running Android 11

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
@asxhelr657 Please provide logs with this. The second error message has been dealt with in #427, and the first one belongs in #424 (and yes, I know this issue was created first, but I already reacted in #424, so in order to clean up a bit I'll have to close this one)
