### ISSUE TITLE
Ability to Resize Lyrics Font

### ISSUE THREAD

**Issue by Melvinfused** [25huizengek1/ViTune#420]
Ability to resize Lyrics font. 
![Screenshot_2024-09-07-09-07-12-698_app vitune android](https://github.com/user-attachments/assets/38aaa730-6667-48b7-97f0-b882e2e949ea)
![Screenshot_2024-09-07-09-07-16-298_app vitune android](https://github.com/user-attachments/assets/72f3f8c5-4163-4a33-aad4-ef99e4fb763e)

**Comment by Melvinfused** [comment]
Could add option to change font size as in players like Jet Audio on Android.

**Comment by 25huizengek1** [comment]
@Melvinfused Just increase the text size in your system settings, that should do.
