### ISSUE TITLE
Album Sort By Publication Date Isn't Working

### ISSUE THREAD

**Issue by imugrage** [25huizengek1/ViTune#426]
### Steps to reproduce the bug

1. Go to albums tab
2. Sort albums by date published (little calendar icon)
3. Toggle ascending/descending with arrow 

### Expected behavior

The albums will sort in ascending/descending order when the arrow is toggled. 

### Actual behavior

They appeared in a random order and the arrow has no influence. 

### ViTune version

v1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

I am using Google Pixel 3a with stock Android 13. 

### Additional information

I don't really use this feature but was suprised not to find an issue about it. Figured it would help to keep the application looking sharp. 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Apparently, YouTube changed the way they provided this data to the user (_again_), so I accounted for it in 69264004f5be5e4f489a887eb35089515e14f841.
