### ISSUE TITLE
Constant Playback Errors on Streaming

### ISSUE THREAD

**Issue by imugrage** [25huizengek1/ViTune#427]
### Steps to reproduce the bug

1. Play a song that is not completely cached
2. Wait until the song is played back about 2/3 of the way

### Expected behavior

ViTune should be able to play a complete song, from start to finish, even if its not completly cached. 

### Actual behavior

Every time I played a song that hadn't been fully cached, it would stop about 2/3 through. ViTune gives "An unexpected playback error has occured" 

### ViTune version

v1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

I am using Google Pixel 3A with standard Android 13

### Additional information

At first I thought this was a random error, but I've noticed the errors happen in partially cached songs. While I've gotten some playback errors in the past that will constantly occur in a given song, once one of these errors happen, I can skip back to the song and it will finish playing just fine. I know this seems like a picky issue, but it 
a) makes sampling new music difficult
b) interupts my listening, while understand there will inevitably be errors, such a high frequency of them makes it hard to focus. 

If anyone has tips for more troubleshooting, that would be appreciated. I've intentionally gone to songs in my database that have a long duration but I've only played for a short time to test this, and sure enough, this error occurs more frequently then. It occurs more frequently when there is a greater disparity between the amount cached and the entire song duration. 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
I am aware of this happening. YouTube apparently now responds with a [416 Range Not Satisfiable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416) status code. This is not intended from YouTube's end, or at least I think so. Just stopping and starting the player should do the trick. Perhaps I should implement a fallback/retry behavior.

**Comment by 25huizengek1** [comment]
(kind of related to https://github.com/25huizengek1/ViTune/issues/424#issuecomment-2346659361)

**Comment by imugrage** [comment]
Thanks @25huizengek1. As long as this on your radar, that makes me feel a lot better to leave this in capable hands. Maybe once an error happens the player tries to play the song again, then if it retries and still hits an error it engages the autoskip? I don't really have the technical know how to know if that would work, just a thought.

**Comment by 25huizengek1** [comment]
Logs of this happening:

<details>
<summary>Click to expand</summary>

```
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal: Playback error
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:232)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:334)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:76)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:   Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 416
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:397)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at app.vitune.android.utils.ConditionalCacheDataSourceFactory$createDataSource$1.open(CacheState.kt:135)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:1012)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:   Caused by: androidx.media3.datasource.DataSourceException
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:395)
1726175861.899 10413  1876  2150 E ExoPlayerImplInternal:       ... 12 more
```

</details>

**Comment by 25huizengek1** [comment]
@imugrage That works, I'll have a look into it. Maybe it's just an internal difficulty at YouTube that we shouldn't have to worry about anyway, but who knows.

**Comment by 25huizengek1** [comment]
Added a fallback for now.
