### ISSUE TITLE
Add Spanish language

### ISSUE THREAD

**Issue by elmees21** [25huizengek1/ViTune#429]
## Feature request: Add Spanish language

Hi! I love your app and I would like it to be available in my language. I have created a strings.xml file with the Spanish translations.

[values-es.zip](https://github.com/user-attachments/files/17002011/values-es.zip)

**Comment by 25huizengek1** [comment]
@elmees21 Thank you so much for the translations! LGTM! I guess you could've created a pull request, but I'll commit this and put you as the author. Expect the translations in the next update!

**Comment by 25huizengek1** [comment]
0695599ef8bc8ff709db6e11da7f42d131642865

**Comment by aryaoffixial** [comment]
In the release v1.0.9 you typed chinese instead of Spanish

**Comment by 25huizengek1** [comment]
@aryaoffixial @elmees21 I'm sorry. I'll update the release.
