### ISSUE TITLE
Autoplay option

### ISSUE THREAD

**Issue by overchromemustangg** [25huizengek1/ViTune#432]
## Feature request: an option to either turn off/on autoplay
Whenever a song I selected ends, it automatically plays similar content. I'd prefer it would just stop and suggest similar content on the queue list just like when an album ends.

**Comment by 25huizengek1** [comment]
This is already possible, or at least works different than you describe. The radio only gets enabled when you click on a single song that is not in a playlist. Otherwise, the app would only play that single song, which doesn't make sense IMO. Otherwise, you have to click the (start) radio button.
