### ISSUE TITLE
Floating lyrics 

### ISSUE THREAD

**Issue by Rowhnn** [25huizengek1/ViTune#433]
## Feature request: Floating lyrics in anywhere

Previously when Resso was available in India, Resso had something unique feature called floating lyrics, where users can see the synced floating lyrics(2 lines before the main line and the next 2 lines of the song) even remaining out side of resso or inside of any other app. 

And in the lock screen, the thumbnail of the song, and lyrics floating on it... It is what used to be in Resso, I feel this is a great feature...

**Comment by 25huizengek1** [comment]
I guess I could add a PIP feature for the player, or at least a smaller, simplified version of it, alongside the lyrics?

I will consider this. I don't know if it's feasible or even allowed on stock Android but I'll let you know.

**Comment by Rowhnn** [comment]
Awesome!
💯❤️

**Comment by 25huizengek1** [comment]
Implemented. This is what it looks like:

**Comment by 25huizengek1** [comment]
https://github.com/user-attachments/assets/852d86be-338e-4058-85c7-0e278b63e125

**Comment by Rowhnn** [comment]
I love it! 💕
