### ISSUE TITLE
Ability to select from quick picks and perform actions

### ISSUE THREAD

**Issue by NeeRaj-2401** [25huizengek1/ViTune#436]
Sometimes a lot of songs seems interesting or something suddenly pops up which i used to listen earlier, in such cases i want to select those songs collectively then may be able to play all, or add to queue or add to playlist ( personally i keep track of a kind of 'watch later' playlist)

**Comment by 25huizengek1** [comment]
This is already possible, quick picks work the same way as all other songs are displayed/behave in ViTune.
