### ISSUE TITLE
Song not playing 

### ISSUE THREAD

**Issue by 2008priyanshu** [25huizengek1/ViTune#437]
### Steps to reproduce the bug

1. Play any song
2. It will play for some time and stops
3. Display source error

### Expected behavior

It should play song normally 

### Actual behavior

It shows source error

### Screenshots/Screen recordings

![Screenshot_2024-09-19-19-24-53](https://github.com/user-attachments/assets/1f619541-7a06-4e18-a818-c3cc6aafc61b)

### ViTune version

v1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 8.1

### Device info

Lenovo tab4 8

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
This already got fixed (YouTube changed the way they handle ranges)

Will release tomorrow.
