### ISSUE TITLE
Swipping song from songs tabs deletes it from playlists as well.

### ISSUE THREAD

**Issue by NeeRaj-2401** [25huizengek1/ViTune#438]
### Steps to reproduce the bug

1. Create a playlist of few songs
2. Play all songs from playlists
3. Swipe those songs away as its being added in songs tab

### Expected behavior

The playlist is a complete different thing to deal with, it should be treated separate from songs tab,

Swipping from songs tab should just delete it from there and cache, playlists should persists

### Actual behavior

Songs added to my playlists are also gone with it

### ViTune version

v1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Nothing phone 2a

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Not a bug. Hiding a song means your phone doesn't know about it anymore. Maybe I could add a warning that the song is associated with playlists.
