### ISSUE TITLE
The returned video id doesn't match the requested one

### ISSUE THREAD

**Issue by GXTRV** [25huizengek1/ViTune#440]
### Steps to reproduce the bug

Click "song"
And then it will show up "The returned video id doesn't match the requested one" "返回的视频ID与请求的ID不匹配"

### Expected behavior

This should play the song

### Actual behavior

Can't play any songs

### Screenshots/Screen recordings

![Screenshot_2024-09-20-07-51-10-959_app vitune android](https://github.com/user-attachments/assets/8caedaec-cf6a-49b6-962a-a3071017a059)

### ViTune version

V1.0.8-Release

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Redmi Note 12 Turbo

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by NeeRaj-2401** [comment]
May be #437

**Comment by 25huizengek1** [comment]
Tracking in #424
