### ISSUE TITLE
Unknown Error occuring in middle of song

### ISSUE THREAD

**Issue by TheWattz** [25huizengek1/ViTune#443]
### Steps to reproduce the bug

Open any song and listen.
Optionally close app to 100% it happen

### Expected behavior

Itll allow me to listen until end

### Actual behavior

It stops playing in middle of song

### Screenshots/Screen recordings

![Screenshot_20240922_133538](https://github.com/user-attachments/assets/fe7c963a-0056-4815-af71-681027ed5800)

### ViTune version

1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14 (UDC)

### Device info

Samsung Galaxy S23

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Mexiater** [comment]
Same issue here, popped up a couple days ago

**Comment by 25huizengek1** [comment]
Already fixed, release scheduled for today.

I'm sorry for the inconvenience, this unfortunately is caused by changes by YouTube Music.

**Comment by TheWattz** [comment]
> Already fixed, release scheduled for today.
> 
> I'm sorry for the inconvenience, this unfortunately is caused by changes by YouTube Music.

didn't thought itll be fixed **today** , so i already installed alt player, anyways, this one is my favorite, continue, we like it!

**Comment by sebastiano123-c** [comment]
I updated the app yesterday (so now I am on version 1.0.9) but I still experience the problem described by TheWattz.

**Comment by TheWattz** [comment]
> I updated the app yesterday (so now I am on version 1.0.9) but I still experience the problem described by TheWattz.

Create new issue
