### ISSUE TITLE
I can help with Russian and Estonian translations

### ISSUE THREAD

**Issue by TheWattz** [25huizengek1/ViTune#445]
These languages are my native, so i can help or make translation of app to these ones. You can DM me on Discord or just answer in here, 
Anyways 
My discord is @wqttzicue

**Comment by 25huizengek1** [comment]
@TheWattz Nice, you're more than welcome to contribute your translations to ViTune! You can create a pull request, or send me the translations directly in here.

**Comment by TheWattz** [comment]
> @TheWattz Nice, you're more than welcome to contribute your translations to ViTune! You can create a pull request, or send me the translations directly in here.

Hi, I've never translated apps using github pull requests, can you explain me how to make translation, or send some kind of a guide?
