### ISSUE TITLE
Other songs dont show the name of the artist

### ISSUE THREAD

**Issue by Kaynem706** [25huizengek1/ViTune#448]
### Steps to reproduce the bug

Download albums that were released mostly in 2019

### Expected behavior

The songs should show names of the artists not the year

### Actual behavior

Year on the artist name

### Screenshots/Screen recordings

![Screenshot_20240923_143636](https://github.com/user-attachments/assets/1eeb73ee-7154-4c85-bae0-db01b57cd918)

### ViTune version

1.0.9

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using Samsung a04e running on 1ui

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Kaynem706** [comment]
![Screenshot_20240923_143636](https://github.com/user-attachments/assets/01e33f23-984a-47d8-89cd-575426f9f715)

**Comment by 25huizengek1** [comment]
Apparently, YouTube changed the album UI again, so I'll have to update the scraping logic.

**Comment by 25huizengek1** [comment]
Unfortunately I cannot reproduce this for the exact same album in your screenshot.

**Comment by 25huizengek1** [comment]
I expect this to be a weird inconsistency on YouTube's servers. If it's still incorrect, feel free to reopen this issue.
