### ISSUE TITLE
the song are not playing 

### ISSUE THREAD

**Issue by farookhamdan** [25huizengek1/ViTune#450]
### Steps to reproduce the bug

recently I'm facing this issues I can't able to play the song fully and this app is not an alternative to spotify because in spotify it play on audio format but in vitune I convert the video song into audio song in that the vocal the are there so it not comfortable please development like spotify 

### Expected behavior

recently I'm facing this issues I can't able to play the song fully and this app is not an alternative to spotify because in spotify it play on audio format but in vitune I convert the video song into audio song in that the vocal the are there so it not comfortable please development like spotify 

### Actual behavior

![Screenshot_20240926_145258](https://github.com/user-attachments/assets/eab0758f-3444-43fc-85e7-c98661bf41d0)

### Screenshots/Screen recordings

![Screenshot_20240926_145258](https://github.com/user-attachments/assets/d31b13e7-7eaf-435f-8d29-3ea95573e56b)

### Logs

recently I'm facing this issues I can't able to play the song fully and this app is not an alternative to spotify because in spotify it play on audio format but in vitune I convert the video song into audio song in that the vocal the are there so it not comfortable please development like spotify 

### ViTune version

v1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 13

### Device info

I'm using samsung f62 in android 13

### Additional information

in this I can't able to listen the song fully and in some of the songs it convert the video song in to audio so in that song some if some speech that is Aloo coming so please fix it asap 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by TheWattz** [comment]
Up! Same thing.

**Comment by Mexiater** [comment]
It's something to do with the app trying to cache the song.
If you for example download an album before listening to it you'll have no problems

**Comment by Mexiater** [comment]
Oh yeah update the app as well!

**Comment by sidsharths1245** [comment]
I'm also getting the same error
