### ISSUE TITLE
The song is automatically added offline

### ISSUE THREAD

**Issue by Popka587bobik** [25huizengek1/ViTune#453]
How to disable this feature?

**Comment by NeeRaj-2401** [comment]
Automatically? Its doesn't until u listen to the song, i dont think there is a way to disable offline caching in this app

**Comment by 25huizengek1** [comment]
> How to disable this feature?

@Popka587bobik You don't, because why would you? I guess adding a 'pause cache' toggle to settings makes sense?

**Comment by NeeRaj-2401** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/156#issuecomment-1203047267
Nostalgia

**Comment by Popka587bobik** [comment]
> Automatically? Its doesn't until u listen to the song, i dont think there is a way to disable offline caching in this app

Yes, it is a little inconvenient :(

**Comment by NeeRaj-2401** [comment]
> Yes, it is a little inconvenient :(

You can reopen the issue, the dev was agreeing on ur point and was open for discussion

**Comment by genericbetatester** [comment]
Feature request these days are literally requests trying to break the core functionality of the app cuz why would you want to change that. That's literally the way the app works

**Comment by genericbetatester** [comment]
> [vfsfitvnm#156 (comment)](https://github.com/vfsfitvnm/ViMusic/issues/156#issuecomment-1203047267) Nostalgia

I checked the linked thread and I think this issue is pretty much solved. Set the cache limit to the lowest and it should suffice
