### ISSUE TITLE
"An unknown playback error has occurred" fix?

### ISSUE THREAD

**Issue by NicoxKurai** [25huizengek1/ViTune#461]
Been getting this message since couple days ago when the songs suddenly stop and there's no way to make them work again. Was happening with an old version so I uninstalled and updated it to the lastest version and still got tje issue. 

Any fix? 

Device: Xiaomi Redmi 9C
Android 14
Vitune v1.0.9

![image_2024-10-09_173139050](https://github.com/user-attachments/assets/01cde3aa-bc0b-440c-92f8-9c9145ffa189)

**Comment by 25huizengek1** [comment]
Already fixed by 531b531aeb1b4529d934dc6b54af1157ca08a90f

Will release soon
