### ISSUE TITLE
Feature Request: Discord Support Server for Users to Ask Questions and Get Help

### ISSUE THREAD

**Issue by KalpeshXOfficial** [25huizengek1/ViTune#468]
### Description:
I would like to propose the creation of a Discord server where users can join to ask questions, report issues, and receive direct assistance from the support team or the community. This will facilitate real-time communication and create a helpful space for users to resolve doubts more efficiently.

### Suggested Functionality:
1. **Server Creation**: Create a dedicated Discord server for app users.
2. **Easy Access**: Provide a link within the app or website that allows users to join the Discord server easily.
3. **Help Channels**: Organize the server into different channels (e.g., #general, #support, #bug-reports) to help users ask specific questions or report issues.
4. **Community Moderation**: Assign moderators or support staff to manage discussions, answer questions, and maintain a friendly environment.
5. **Announcements Channel**: Use a dedicated channel for important updates, new features, or bug fixes.
6. **Push Notifications (Optional)**: An optional feature to allow users to receive real-time notifications through Discord for important app-related updates or announcements.

### Benefits:
- Real-time communication between users and support staff.
- Builds an engaged community where users can help each other and share knowledge.
- Reduces the need for one-on-one support, improving response times and efficiency.
- Allows the sharing of updates and announcements directly to the user base.

### Additional Information:
Ensure the server is well-structured and that rules and guidelines are clearly communicated to foster a productive and respectful environment for all users.

**Comment by Wqttzicue** [comment]
Uh, isnt it same as i suggested?

**Comment by Wqttzicue** [comment]
Ye, its repeated check #460

**Comment by KalpeshXOfficial** [comment]
Hi, I noticed that the developer hasn't responded to any issues or pull requests on GitHub. It's possible they are busy, dealing with personal matters, or no longer actively maintaining the project. Sometimes open-source developers contribute in their free time, so delays in responses can happen. You might want to check if the project is still being actively developed or try reaching out through other channels like email or social media, if available.

**Comment by 25huizengek1** [comment]
@Wqttzicue @KalpeshXOfficial I do respond to issues, but not on a periodic basis. I only work on ViTune when I have some time to kill in my day. Yes, I have converted this to a discussion in #460, so let's continue the conversation over there.

**Comment by Wqttzicue** [comment]
> Hi, I noticed that the developer hasn't responded to any issues or pull requests on GitHub. It's possible they are busy, dealing with personal matters, or no longer actively maintaining the project. Sometimes open-source developers contribute in their free time, so delays in responses can happen. You might want to check if the project is still being actively developed or try reaching out through other channels like email or social media, if available.

Uhh, imo Dev is very active, and the thing that he dont answer means nothing, cuz there is 10010 issues about unknown error, and people sometimes yk, has own life.

**Comment by 25huizengek1** [comment]
Yes, that is indeed the case. YouTube constantly changing up the way things work mess up a lot in ViTune, which takes some time to investigate and fix. Combine that with the fact that I have a pretty busy life and can only dedicate so much time to side-projects. I really cannot work a lot on ViTune.

**Comment by Wqttzicue** [comment]
> Yes, that is indeed the case. YouTube constantly changing up the way things work mess up a lot in ViTune, which takes some time to investigate and fix. Combine that with the fact that I have a pretty busy life and can only dedicate so much time to side-projects. I really cannot work a lot on ViTune.

Maybe you need some guys whp will help you with developing it?
Btw discord server is good way to find some, but not guaranteed..
