### ISSUE TITLE
Error in playing some song

### ISSUE THREAD

**Issue by brnwlshubh** [25huizengek1/ViTune#475]
![Screenshot_20241016_185815](https://github.com/user-attachments/assets/0f6b1636-1700-4232-8024-4d19bbbd453c)

              @25huizengek1 I'm using the latest beta version.
I'm still facing this issue.

_Originally posted by @brnwlshubh in https://github.com/25huizengek1/ViTune/issues/466#issuecomment-2415875550_

**Comment by shrijithps** [comment]
happens for me too

**Comment by 25huizengek1** [comment]
See https://github.com/25huizengek1/ViTune/issues/467#issuecomment-2409096071
