### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by KshitiJ0123** [25huizengek1/ViTune#477]
### Steps to reproduce the bug

1.Open the music player app.
2.Play any song.
3.Keep changing songs by pressing the Next button multiple times.
4.After a few skips, an error message appears: "The returned video ID doesn't match the requested one."

### Expected behavior

The song should play without any issues after tapping the play button.

### Actual behavior

The app displays an error: "The returned video ID doesn't match the requested one."
The song does not play correctly, even though it appears in the UI.

### Screenshots/Screen recordings

![Screenshot_20241016_212746](https://github.com/user-attachments/assets/f53e9f66-26e4-4c5a-8d11-698f88b2645b)
![Screenshot_20241016_212730](https://github.com/user-attachments/assets/272ba6af-1883-4ac6-8a4e-168ae05c201a)

### ViTune version

V1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using Vivo Iqoo Neo 7 5G running on android 14

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
This is millionth issue about unknown error...

**Comment by MLGHerobrine** [comment]
> This is probably Youtube music's Issue.

Probably. However, I've also noticed an increase in this occuring since I updated. However, "refreshing" the song by going forward and back again usually will fix it. It may take a few times.

Potential solution: Add an option (if desired, or just make it a feature) to re-request the song data after it gives an error.

**Comment by Mexiater** [comment]
Yeah the issue got way worse with the new update, it also breaks the pre-cache feature getting it stuck on loading

**Comment by boly38** [comment]
If this issue is on YTM side, and even if not, I wopuld like an additionnal settings that allow me to 
- [ ] move automatically to the next song on play error/issue

**Comment by Wqttzicue** [comment]
> If this issue is on YTM side, and even if not, I would like an additionnal (user level?) settings that allow me to 
> - [ ] move automatically to the next song on play error/issue

Already exists.

**Comment by Wqttzicue** [comment]
> > This is probably Youtube music's Issue.
> 
> Probably. However, I've also noticed an increase in this occuring since I updated. However, "refreshing" the song by going forward and back again usually will fix it. It may take a few times.
> 
> Potential solution: Add an option (if desired, or just make it a feature) to re-request the song data after it gives an error.
> 
> Let me know if you would like me to attach any logs.

Suggest this solution , if its original

**Comment by kunal-1320** [comment]
Yup auto skip thingy works but should have like 2 sec delay to skip cause it takes time to load any song and it skips the songs too fast

**Comment by Wqttzicue** [comment]
> Yup auto skip thingy works but should have like 2 sec delay to skip cause it takes time to load any song and it skips the songs too fast 

Suggest it! If its original (im pretty sure tjis is priginal enchancement, and it supposed to be easy to implement.

**Comment by KshitiJ0123** [comment]
> > If this issue is on YTM side, and even if not, I would like an additionnal (user level?) settings that allow me to
> > 
> > * [ ]  move automatically to the next song on play error/issue
> 
> Already exists. Settings=>Player=>Autoskip


I’m facing a playback error when trying to play specific songs. If a user opens the app to listen to a particular song and it doesn’t play, the experience becomes frustrating, and skipping isn’t helpful.

Please resolve this issue at the earliest.

**Comment by genericbetatester** [comment]
> > > If this issue is on YTM side, and even if not, I would like an additionnal (user level?) settings that allow me to
> > > 
> > > * [ ]   move automatically to the next song on play error/issue
> > 
> > 
> > Already exists. Settings=>Player=>Autoskip
> 
> I’m facing a playback error when trying to play specific songs. If a user opens the app to listen to a particular song and it doesn’t play, the experience becomes frustrating, and skipping isn’t helpful.
> 
> Please resolve this issue at the earliest.

It's definitely frustrating, YouTube probably broke something again. One workaround I've found is to pause the song after it brings up the error, wait for it to load up and it'll play normally. You may have to try this a few times though, but it works. You have to turn off autoskip for this to work.

**Comment by Wqttzicue** [comment]
> > > > > If this issue is on YTM side, and even if not, I would like an additionnal (user level?) settings that allow me to
> > > > > 
> > > > > * [ ]    move automatically to the next song on play error/issue
> > > > 
> > > > 
> > > > Already exists. Settings=>Player=>Autoskip
> > > 
> > > 
> > > I’m facing a playback error when trying to play specific songs. If a user opens the app to listen to a particular song and it doesn’t play, the experience becomes frustrating, and skipping isn’t helpful.
> > > Please resolve this issue at the earliest.
> > 
> > It's definitely frustrating, YouTube probably broke something again. One workaround I've found is to pause the song after it brings up the error, wait for it to load up and it'll play normally. You may have to try this a few times though, but it works. You have to turn off autoskip for this to work.
> 
> 
> The only way to get rid of this problem is implementing Google Acount Sync/cache. 

Cache already exists, google sync is probably wont happen cuz this player is privacy and freeware orientated, according to Dev's words
