### ISSUE TITLE
Sometimes these messages are displayed and music stops 

### ISSUE THREAD

**Issue by kunal-1320** [25huizengek1/ViTune#479]
![Screenshot_20241017_233845.jpg](https://github.com/user-attachments/assets/d5e3a299-dabf-424e-8cfc-604c60b9fd85)

![Screenshot_20241017_233852.jpg](https://github.com/user-attachments/assets/ff385b0f-00fb-49c8-a34f-97c25482d0a7)

When I play next

**Comment by Wqttzicue** [comment]
Million first report about these errors..
Ill repeat dev words, this is YTM issue, its hard to fix.
(As i understood him, i may be wrong)

**Comment by kunal-1320** [comment]
The issue was already closed by me.

**Comment by Wqttzicue** [comment]
> The issue was already closed by me. 
> Thanks btw for your time 

Ah, ye, im blind, sorry..
