### ISSUE TITLE
Playlist/Song sharing from ViTune

### ISSUE THREAD

**Issue by Wqttzicue** [25huizengek1/ViTune#480]
## Feature request: ...

Inspired by #476 , 
What about making like links to playlists that you can open in app and add playlist or listen some song. 

And additionally itll be cool if you could listen it in link preview,
So you just send link and you can listen the music in preview.

Just in theory it is possible without transporting all traffic through ViTune's server, so as some future feature it is fine, and this will make ViTune much more popular.

**Comment by ygbillet** [comment]
My goal is to share songs and playlists with my family. I introduced ViTune to everyone, and now it’s the app we all use. However, we’re looking for a way to exchange songs and playlists directly within the app. I’ve tried other software, but I find their interfaces cluttered or overloaded with unnecessary features.

**Comment by Melvinfused** [comment]
What will happen if it become famous?

**Comment by Wqttzicue** [comment]
> What will happen if it become famous?

Nothing except more duplicating issues, so dev will just closing all except original ones.
And maybe someone will join this project and help poor Ingek in his unpaid work.

**Comment by 25huizengek1** [comment]
@Wqttzicue Thank you for the ideas, I prefer to keep everything in one issue (#476) though, so I'll close this one.
