### ISSUE TITLE
[BUG] Alphabetical order is case sensitive

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#481]
### Steps to reproduce the bug

1. Go to songs tab
2. Scroll to the bottom

### Expected behavior

The alphabetical order sorting should not be case sensitive.

### Actual behavior

Songs that start with the letter "a" are below those which start with "Z"

### ViTune version

v1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Samsung A22 5G

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [x] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
Uhh, i dont even know is it bug pr enchancement, but i agree.

**Comment by 25huizengek1** [comment]
While this isn't a bug, I also thought this is nice to have, so I've added it (by coincidence, I guess) in e81b2fabb27bfb88d54fdeb7a111b8bed01e3769 just a couple days before you created this issue... Nice!
