### ISSUE TITLE
Add Sponsorblock Highlights

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#482]
Add a button in the player to directly skip to the highlight section (if it does exist, of course). 
It would be useful to skip to the most enticing part of the song and a nice integration with SB in general.

There could be a toggle in the settings that appears after enabling sponsorblock (just below it) to let users choose if they want to enable sponsorblock highlights.

The icon could be placed as per the image below, it could be the one from sponsorblock or another one altogether. Maybe even adding a little spot on the timeline to let users know where the highligted spot is at a glance (again, like in the image)

![Group(1)](https://github.com/user-attachments/assets/e9d9a375-61d5-4348-acbf-fdd1dadf5e36)

**Comment by Wqttzicue** [comment]
I like that, but myself od added in corner, cuz this will fill the classic player interface with uneeded mostly button.
Or! Just add the highlight moment on track-line.

**Comment by Monoxide8969** [comment]
I agree, I am not a fan of cluttered UIs myself.

Another idea is double tapping on the song cover skips to the highlight. 
The toggle in the settings that appears after enabling sponsorblock could be something like:

**Enable Highlights**
_Double tap on the song cover to skip to the highlight_

**Comment by Monoxide8969** [comment]
> I haven't found a music video that has a highlight in it (yet).

https://www.youtube.com/watch?v=SRXH9AbT280

**Comment by 25huizengek1** [comment]
Implemented:

![Screenshot_20241022-014145.png](https://github.com/user-attachments/assets/f89b5a38-28e1-46da-b3be-2ac26e2f4f42)
