### ISSUE TITLE
Reload Song Data Upon Error

### ISSUE THREAD

**Issue by MLGHerobrine** [25huizengek1/ViTune#483]
## Feature request: Reload song data, if an error occurs.

A suggestion in response to #477.

Include a menu option or full feature to reload song data if an error occurs. This would be similar to autoskip, in that it is triggered upon an error. Upon being triggered, the player will reload the song and restart where the error occured. For example, if the player gave an error at 1:33 in a song because it did not have the entire song cached, it will reload the song and skip to 1:33 to resume almost uninterrupted playback. On the user's end, this may only sound like a few second pause, which is much better than the user having to reload the song manually.

## Why include this?
Since v1.1.0, people have noticed more errors while playing music (#477). The current temporary solution is to go forward and back to reload the song. This feature would catch overall player, cache, and YouTube Music errors and employ a basic solution to try to fix them without user intervention.

This feature could also be combined with autoskip. After a certain number of reloads, the player can automatically skip the song.

**Comment by 25huizengek1** [comment]
Added in 6fb1ab8d84812ecd5a6167c0721556e71898cc07

**Comment by genericbetatester** [comment]
One of the best and more better articulated feature request I've seen here
