### ISSUE TITLE
The returned video id doesn't match the requested one

### ISSUE THREAD

**Issue by Dadoxm** [25huizengek1/ViTune#485]
### Steps to reproduce the bug

Ho aperto l' app e selezionando una canzone mi appare questo messaggio "The returned video id doesn't match the requested one"

### Expected behavior

Vorrei risolvere in qualche modo per utilizzare l'app

### Actual behavior

E la musica non va

### ViTune version

V.1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Redmi 12c

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
Yes.

**Comment by Mexiater** [comment]
Per favore scrivi in inglese che nessuno qui capisce l'italiano.
Se cerchi tra gli altri problemi segnalati qualcun'altro ha già fatto notare sto errore.
Grazie comunque per la segnalazione!

**Comment by Mexiater** [comment]
Ah e per sistemare basta mettere in pausa e aspettare un paio di secondi in modo che la canzone si carichi, poi fai riparare e dovrebbe andare. Prova a farlo più di una volta se continua a darti problemi.
C'è anche un'opzione nelle impostazioni (impostazioni>player>autoskip) che ti permette di skippare in automatico gli errori di questo tipo

**Comment by Wqttzicue** [comment]
Uhh, in Italian i know only this, "vietato fumare" and "attenzione'

**Comment by MLGHerobrine** [comment]
This appears to be a duplicate / falls under the same issue as #477. Correct me if I'm wrong.

**Comment by Wqttzicue** [comment]
> This appears to be a duplicate / falls under the same issue as #477. Correct me if I'm wrong.

Ig they have same root. Anyways yöure right

**Comment by 25huizengek1** [comment]
Duplicate of (e.g.) #477
