### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by sidsharths1245** [25huizengek1/ViTune#487]
### Steps to reproduce the bug

1) Search for a song
2) Play one of the results
3) Hit the back button while the player is still open

The player window won't close, if i minimise the player window by swiping down and then search for another song, the search breaks and nothing happens.

### Expected behavior

Search results should appear 

### Actual behavior

Search results don't appear

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/7c8b47b7-98d6-4a67-bee8-8114cb7d0125

### ViTune version

1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Galaxy S23

### Upstream reproducibility

Not present on ViMusic

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
YES! And also there is issue that some songs generated automatically in queue dont play and automatically skip to previous song.
