### ISSUE TITLE
New Error Message

### ISSUE THREAD

**Issue by Wqttzicue** [25huizengek1/ViTune#492]
## Feature request: ...

Sometimes if you play some video grom regular youtube as song it maybe not avivable in ViTune cuz it requires to be 18+ to watch it on youtube.

So I suggest to add error message that will say something like "age restriction error".

Or just make it possible to play vids with restriction.

**Comment by 25huizengek1** [comment]
It _was_ possible to play video's with age restriction, but that relied on Piped. Since Piped implementation fails to access YouTube Music right now, I can only try to implement this JavaScript challenge myself.

So it may not seem like it, but this is actually just #499

**Comment by Wqttzicue** [comment]
> It _was_ possible to play video's with age restriction, but that relied on Piped. Since Piped implementation fails to access YouTube Music right now, I can only try to implement this JavaScript challenge myself.
> 
> So it may not seem like it, but this is actually just #499

No, i had this issue before, long time ago.
