### ISSUE TITLE
Translation of the application into Russian.

### ISSUE THREAD

**Issue by silence0000000000** [25huizengek1/ViTune#493]
## Feature request: ...

A clear and concise description of the feature you want to request.
Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p

**Comment by Wqttzicue** [comment]
Ты можешь сделать свой пулл-реквест с исправлениями, но мне казалось что я перевел все относительно неплохо..

**Comment by silence0000000000** [comment]
> Ты можешь сделать свой пулл-реквест с исправлениями, но мне казалось что я перевел все относительно неплохо..
> 
> Либо же просто скажи мне где ошибки и я исправлю. (Просто я использовал Эстонский вариант своего перевода, и Русским особо не пользовался, от чего и в правду мог не заметить ошибки)

Куда я могу отправить все поправки?

**Comment by Wqttzicue** [comment]
> > Ты можешь сделать свой пулл-реквест с исправлениями, но мне казалось что я перевел все относительно неплохо..
> > 
> > Либо же просто скажи мне где ошибки и я исправлю. (Просто я использовал Эстонский вариант своего перевода, и Русским особо не пользовался, от чего и в правду мог не заметить ошибки)
> 
> Куда я могу отправить все поправки?

Сюда

**Comment by silence0000000000** [comment]
> > > Ты можешь сделать свой пулл-реквест с исправлениями, но мне казалось что я перевел все относительно неплохо..
> > > Либо же просто скажи мне где ошибки и я исправлю. (Просто я использовал Эстонский вариант своего перевода, и Русским особо не пользовался, от чего и в правду мог не заметить ошибки)
> > 
> > 
> > Куда я могу отправить все поправки?
> 
> Сюда, исправлю, за одно Спонсорблок переведу, топ контрибьютор😎


(это просто мон мнение насчет перевода, я не заставляю вас переводить и енно так.)
Левая панель главной страницы:

Быстрый выбор - Главная
Открыть - Исследуйте
Песни - Музыка
Артисты - Исполнители
Локальные - Скачанные

Левая панель настроек:
Источник акцентного цвета - Цветовая схема
Синхронизировать - Синхронизация
Режим - Тема
Темнота - Степень темноты
Скругленность миниатюр - Скругленность обложек
Sponsorblock - блокирует рекламный контент
Взаимодействие с системным эквалайзером - Открыть встроенный эквалайзер

вроде всё.

**Comment by silence0000000000** [comment]
> > > Ты можешь сделать свой пулл-реквест с исправлениями, но мне казалось что я перевел все относительно неплохо..
> > > Либо же просто скажи мне где ошибки и я исправлю. (Просто я использовал Эстонский вариант своего перевода, и Русским особо не пользовался, от чего и в правду мог не заметить ошибки)
> > 
> > 
> > Куда я могу отправить все поправки?
> 
> Сюда, исправлю, за одно Спонсорблок переведу, топ контрибьютор😎

(Это мое мнение, я не заставляю переводить именно так)

Левая панель главной страницы:

Быстрый выбор - Главная
Открыть - Исследуйте
Песни - Музыка
Артисты - Исполнители
Локальные - Скачанные

Левая панель настроек:
Синхронизировать - Синхронизация

Настройки:
Источник акцентного цвета - Цветовая схема
Режим - Тема
Темнота - Степень темноты
Скругленность миниатюр - Скругленность обложек
Sponsorblock - блокирует рекламный контент
Взаимодействие с системным эквалайзером - Открыть встроенный эквалайзер

**Comment by Wqttzicue** [comment]
> > > > Ты можешь сделать свой пулл-реквест с исправлениями, но мне казалось что я перевел все относительно неплохо..
> > > > Либо же просто скажи мне где ошибки и я исправлю. (Просто я использовал Эстонский вариант своего перевода, и Русским особо не пользовался, от чего и в правду мог не заметить ошибки)
> > > 
> > > 
> > > Куда я могу отправить все поправки?
> > 
> > Сюда, исправлю, за одно Спонсорблок переведу, топ контрибьютор😎
> 
> (Это мое мнение, я не заставляю переводить именно так)
> 
> Левая панель главной страницы:
> 
> Быстрый выбор - Главная
> Открыть - Исследуйте
> Песни - Музыка
> Артисты - Исполнители
> Локальные - Скачанные
> 
> Левая панель настроек:
> Синхронизировать - Синхронизация
> 
> Настройки:
> Источник акцентного цвета - Цветовая схема
> Режим - Тема
> Темнота - Степень темноты
> Скругленность миниатюр - Скругленность обложек
> Sponsorblock - блокирует рекламный контент
> Взаимодействие с системным эквалайзером - Открыть встроенный эквалайзер

Хмм, да, несколько переводов даже лучше, 
Щас исправлю, и отправлю пулл реквест. Спасибо!

**Comment by Wqttzicue** [comment]
> ## Feature request: ...
> 
> A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p

Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо

**Comment by Wqttzicue** [comment]
@25huizengek1 this thread can be closed as done

**Comment by silence0000000000** [comment]
> > ## Feature request: ...
> > A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p
> 
> Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо

Спасибо что выслушали. На самом деле странно, что ваши друзья не обратили внимания на слово Артисты вместо исполнители) Я буду очеь рад, если меня укажут как контрибьютора в фиксах, спаибо огромное.

Кстати, если вам понадобится перевод на белорусский язык, обращайтесь 😉

**Comment by Wqttzicue** [comment]
> > > ## Feature request: ...
> > > A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p
> > 
> > 
> > Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо
> 
> Спасибо что выслушали. На самом деле странно, что ваши друзья не обратили внимания на слово Артисты вместо исполнители) Я буду очеь рад, если меня укажут как контрибьютора в фиксах, спаибо огромное.
> 
> Кстати, если вам понадобится перевод на белорусский язык, обращайтесь 😉

O, белорусский, круто
ты можешь сделать этот перевод сам, для этого нужно:

1. Форкнуть эту репозиторию к себе


2. Открыть форк, и открыть путь в файлах https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res


3. Открыть папку Values https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res/values/strings.xml


4. Скопировать или содержимое и вернуться в https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res


5. Там нажать "Add file" после чего откроется меню ввода содержимого, и сверху нужно назвать файл `values-br/strings.xml`


6. Содержимое values/strings.xml нужно закинуть в values-br/strings.xml и перевести все что на английском


Если что как переводить время или куда вставлять переведенный текст можешь посмотреть в моей репозитории
[app/src/main/res/values-ru/strings.xml](https://github.com/Wqttzicue/ViTune/blob/master/app/src/main/res/values-ru/strings.xml)


после перевода очень вероятно тебе предложит сделать pull request где просто - заголовок, описание.


Удачи :)

**Comment by Wqttzicue** [comment]
> > > > ## Feature request: ...
> > > > A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p
> > > 
> > > 
> > > Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо
> > 
> > 
> > Спасибо что выслушали. На самом деле странно, что ваши друзья не обратили внимания на слово Артисты вместо исполнители) Я буду очеь рад, если меня укажут как контрибьютора в фиксах, спаибо огромное.
> > Кстати, если вам понадобится перевод на белорусский язык, обращайтесь 😉
> 
> O, белорусский, круто ты можешь сделать этот перевод сам, для этого нужно:
> 
>     1. Форкнуть эту репозиторию к себе
> 
>     2. Открыть форк, и открыть путь в файлах https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> 
>     3. Открыть папку Values https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res/values/strings.xml
> 
>     4. Скопировать или содержимое и вернуться в https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> 
>     5. Там нажать "Add file" после чего откроется меню ввода содержимого, и сверху нужно назвать файл `values-br/strings.xml`
> 
>     6. Содержимое values/strings.xml нужно закинуть в values-br/strings.xml и перевести все что на английском
> 
> 
> Если что как переводить время или куда вставлять переведенный текст можешь посмотреть в моей репозитории [app/src/main/res/values-ru/strings.xml](https://github.com/Wqttzicue/ViTune/blob/master/app/src/main/res/values-ru/strings.xml)
> 
> после перевода очень вероятно тебе предложит сделать pull request где просто - заголовок, описание.
> 
> Удачи :)

P.S пока ты не форкнешь репозиторию эти ссылки не будут работать

**Comment by silence0000000000** [comment]
> > > > > ## Feature request: ...
> > > > > A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p
> > > > 
> > > > 
> > > > Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо
> > > 
> > > 
> > > Спасибо что выслушали. На самом деле странно, что ваши друзья не обратили внимания на слово Артисты вместо исполнители) Я буду очеь рад, если меня укажут как контрибьютора в фиксах, спаибо огромное.
> > > Кстати, если вам понадобится перевод на белорусский язык, обращайтесь 😉
> > 
> > 
> > O, белорусский, круто ты можешь сделать этот перевод сам, для этого нужно:
> > ```
> > 1. Форкнуть эту репозиторию к себе
> > 
> > 2. Открыть форк, и открыть путь в файлах https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> > 
> > 3. Открыть папку Values https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res/values/strings.xml
> > 
> > 4. Скопировать или содержимое и вернуться в https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> > 
> > 5. Там нажать "Add file" после чего откроется меню ввода содержимого, и сверху нужно назвать файл `values-br/strings.xml`
> > 
> > 6. Содержимое values/strings.xml нужно закинуть в values-br/strings.xml и перевести все что на английском
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Если что как переводить время или куда вставлять переведенный текст можешь посмотреть в моей репозитории [app/src/main/res/values-ru/strings.xml](https://github.com/Wqttzicue/ViTune/blob/master/app/src/main/res/values-ru/strings.xml)
> > после перевода очень вероятно тебе предложит сделать pull request где просто - заголовок, описание.
> > Удачи :)
> 
> P.S пока ты не форкнешь репозиторию эти ссылки не будут работать P.S.S И еще ставь галочку чтобы сделать новую ветку (ака. Branch) чтобы просто не запутаться, если надобудет исправить просио сверху указываешь именно ветку белорусского, и готово.

Я всё понял, спасибо!
Удачи!

**Comment by silence0000000000** [comment]
> > > > > > ## Feature request: ...
> > > > > > A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p
> > > > > 
> > > > > 
> > > > > Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо
> > > > 
> > > > 
> > > > Спасибо что выслушали. На самом деле странно, что ваши друзья не обратили внимания на слово Артисты вместо исполнители) Я буду очеь рад, если меня укажут как контрибьютора в фиксах, спаибо огромное.
> > > > Кстати, если вам понадобится перевод на белорусский язык, обращайтесь 😉
> > > 
> > > 
> > > O, белорусский, круто ты можешь сделать этот перевод сам, для этого нужно:
> > > ```
> > > 1. Форкнуть эту репозиторию к себе
> > > 
> > > 2. Открыть форк, и открыть путь в файлах https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> > > 
> > > 3. Открыть папку Values https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res/values/strings.xml
> > > 
> > > 4. Скопировать или содержимое и вернуться в https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> > > 
> > > 5. Там нажать "Add file" после чего откроется меню ввода содержимого, и сверху нужно назвать файл `values-br/strings.xml`
> > > 
> > > 6. Содержимое values/strings.xml нужно закинуть в values-br/strings.xml и перевести все что на английском
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Если что как переводить время или куда вставлять переведенный текст можешь посмотреть в моей репозитории [app/src/main/res/values-ru/strings.xml](https://github.com/Wqttzicue/ViTune/blob/master/app/src/main/res/values-ru/strings.xml)
> > > после перевода очень вероятно тебе предложит сделать pull request где просто - заголовок, описание.
> > > Удачи :)
> > 
> > 
> > P.S пока ты не форкнешь репозиторию эти ссылки не будут работать P.S.S И еще ставь галочку чтобы сделать новую ветку (ака. Branch) чтобы просто не запутаться, если надобудет исправить просио сверху указываешь именно ветку белорусского, и готово.
> 
>
 Я всё понял, спасибо!
Ещё один вопрос, смогу ли я сам проверить, что я напереводил, в самом приложении?

**Comment by Wqttzicue** [comment]
> > > > > > > ## Feature request: ...
> > > > > > > A clear and concise description of the feature you want to request. Hello. I have been using your app for half a year now and I am still happy with it. In version 1.1.0 you added support for the Russian language, but it has many errors, as if all the text in the app was translated through Google Translate 😅. I am fully fluent in Russian and would really like to help you with translation into Russian. Thank you for paying attention :p
> > > > > > 
> > > > > > 
> > > > > > Я добавил большинство твоих переводов, спасибо, щас еще Эстонский перевод обновлю и сдлеаю пулл реквест, спасибо
> > > > > 
> > > > > 
> > > > > Спасибо что выслушали. На самом деле странно, что ваши друзья не обратили внимания на слово Артисты вместо исполнители) Я буду очеь рад, если меня укажут как контрибьютора в фиксах, спаибо огромное.
> > > > > Кстати, если вам понадобится перевод на белорусский язык, обращайтесь 😉
> > > > 
> > > > 
> > > > O, белорусский, круто ты можешь сделать этот перевод сам, для этого нужно:
> > > > ```
> > > > 1. Форкнуть эту репозиторию к себе
> > > > 
> > > > 2. Открыть форк, и открыть путь в файлах https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> > > > 
> > > > 3. Открыть папку Values https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res/values/strings.xml
> > > > 
> > > > 4. Скопировать или содержимое и вернуться в https://github.com/silence0000000000/ViTune/tree/master/app/src/main/res
> > > > 
> > > > 5. Там нажать "Add file" после чего откроется меню ввода содержимого, и сверху нужно назвать файл `values-br/strings.xml`
> > > > 
> > > > 6. Содержимое values/strings.xml нужно закинуть в values-br/strings.xml и перевести все что на английском
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Если что как переводить время или куда вставлять переведенный текст можешь посмотреть в моей репозитории [app/src/main/res/values-ru/strings.xml](https://github.com/Wqttzicue/ViTune/blob/master/app/src/main/res/values-ru/strings.xml)
> > > > после перевода очень вероятно тебе предложит сделать pull request где просто - заголовок, описание.
> > > > Удачи :)
> > > 
> > > 
> > > P.S пока ты не форкнешь репозиторию эти ссылки не будут работать P.S.S И еще ставь галочку чтобы сделать новую ветку (ака. Branch) чтобы просто не запутаться, если надобудет исправить просио сверху указываешь именно ветку белорусского, и готово.
> > 
> >
>  Я всё понял, спасибо!
> Ещё один вопрос, смогу ли я сам проверить, что я напереводил, в самом приложении?

Да, для этого тебе нужно будет скомпилировать бранч  с переводом в приложение используя gradle, там можно легко собрать приложение не дожидаясь релиза.

**Comment by 25huizengek1** [comment]
I don't understand any of this, but I'd appreciate it if you opened a PR fixing this. I guess you guys in this thread are working on it?

**Comment by Wqttzicue** [comment]
> I don't understand any of this, but I'd appreciate it if you opened a PR fixing this. I guess you guys in this thread are working on it?

Already done, i made fixes, and Silence want to make Belorussian translation
