### ISSUE TITLE
Id doesn't match

### ISSUE THREAD

**Issue by leokeo0** [25huizengek1/ViTune#496]
### Steps to reproduce the bug

1. Start playing any song 
2.. 
![Screenshot_2024-10-24-00-32-39-475_app vitune android](https://github.com/user-attachments/assets/84587747-6478-4132-91d3-aa7454c5ba89)

### Expected behavior

The song starts playing typically 

### Actual behavior

No song is able to be played

### ViTune version

V1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I'm using the xiaomi 12 lite running hyperOS

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by BaccoTube** [comment]
![Screenshot_2024-10-24-07-25-30-15_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/4e9636e0-48e9-47bc-abb3-6e7697bdfd23)
I have the same problem too

**Comment by Mexiater** [comment]
Just found out the Piped Api (the service that grabs the song from youtube) is currently down, it has nothing to do with the app itself. We just have to wait.

**Comment by Wqttzicue** [comment]
Its 1,000,003 issue sbout this, are u sure it is original issue? i assume it is, 
check #477

**Comment by 25huizengek1** [comment]
Continuing the conversation in #499
