### ISSUE TITLE
"the returned video id doesn't match the requested one" bug occured vimusic

### ISSUE THREAD

**Issue by Malmals** [25huizengek1/ViTune#497]
### Steps to reproduce the bug

I didn't do anything.

### Expected behavior

Playing the music should have been continuously 

### Actual behavior

![Screenshot_20241024_113157](https://github.com/user-attachments/assets/2c2798cf-fcff-4e20-a4bb-4d3b2670502e)

### Screenshots/Screen recordings

![Screenshot_20241024_113157](https://github.com/user-attachments/assets/f8ecf16a-9464-4999-afab-408c39654770)

### ViTune version

v0.5.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

I am using vivo Y20i

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by aryan1996535** [comment]
Sa![Screenshot_20241024-093049.jpg](https://github.com/user-attachments/assets/4d8188d4-cb9c-42cb-9ca6-135194763598)

Same issue.

**Comment by Mexiater** [comment]
It happens with every song

**Comment by Refractivedog04** [comment]
It happens even with latest 1.1 build version of vitune

**Comment by Mexiater** [comment]
Just found out the Piped Api (the service that grabs the song from youtube) is currently down, it has nothing to do with the app itself. We just have to wait.

**Comment by Metgus** [comment]
> Только что выяснилось, что Piped Api (сервис, который загружает песни с YouTube) в данный момент не работает, это не связано с самим приложением. Нам просто нужно подождать.

I am writing through a translator if something is not clear, it is a pity that you will have to wait, but I hope everything will be resolved

**Comment by 25huizengek1** [comment]
Continuing the conversation in #499
