### ISSUE TITLE
Songs not playing

### ISSUE THREAD

**Issue by Ak07-gif** [25huizengek1/ViTune#502]
### Steps to reproduce the bug

Searched or opened playlist 
Clicked on the desired song

### Expected behavior

Song should start playing 

### Actual behavior

Instead it shows a banner saying 'the returned video id does not match the requested one'.

### Screenshots/Screen recordings

![Screenshot_2024-10-24-16-20-47-38_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/caf277b5-e81d-40fc-ab36-2fa6905bd926)

### ViTune version

V.1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

I am using oppo A17 running Android 12

### Upstream reproducibility

The same issue occurs in vimusic

### Additional information

Since last few days it would show the same thing but song would play after clicking many times or changing the song and replaying but since today morning not a single song would play!

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by genericbetatester** [comment]
Idk if you and others doing this don't notice that an issue have been opened already.  You alone have created 2 different threads on the same issue but you still tick "This issue has not been submitted already" and then repeat. You're stressing the devs by opening several issues. This problem is a known one, everyone is experiencing this and the devs are working on a fix. Just be patient and stop creating several threads

**Comment by Hemanth-konduru** [comment]
I am facing the same issue, with every app that uses YouTube's internal client codes and APIs. It was fine till yesterday

**Comment by genericbetatester** [comment]
> I am facing the same issue, with every app that uses YouTube's internal client codes and APIs. It was fine till yesterday

Same here, I've had the issue for some days to but today it got really worse. No song is streaming at all.

**Comment by 25huizengek1** [comment]
Continuing the conversation in #499
