### ISSUE TITLE
Requested ID Error constantly pops up

### ISSUE THREAD

**Issue by XelXen** [25huizengek1/ViTune#512]
### Steps to reproduce the bug

While this issue isn't happening on all songs, once it does, it doesn't stop until I restart the app or something 

There's not many steps to it, just listen to a song that is not in your local cache and 50% of the times, this error would occur

### Expected behavior

The song should play?

### Actual behavior

Song doesn't play?

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/14b0a3b0-9522-4cc0-bc38-addcd15db97b

### ViTune version

1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Nothing Phone (1), 8GB/256GB, Latest NothingOS

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by XelXen** [comment]
Update: Now every song except the ones in local cache are displaying this error. Great! I am going miss out on my favourite app 😶‍🌫️

**Comment by H3T-Shah** [comment]
This is because YT Music has made it mandatory to login to listen to music.

If you have been using Innertune, it was prompting me to login and after that music playback is all good. So it's the same issue here. But ViTune doesn't have an option to login so we need an update immediately.

**Comment by H3T-Shah** [comment]
@XelXen #499 Has already mentioned this issue. You should close this. It's a duplicate.
