### ISSUE TITLE
Thought 

### ISSUE THREAD

**Issue by muraikrishna239** [25huizengek1/ViTune#518]
Make a community group in telegram were we can share problem and fix it as vimusic is not working

**Comment by Vitalii-code** [comment]
I created a signal group
https://signal.group/#CjQKIDZSEtPaazDWchj6InlpvN7Mi8Wbksa2YKUQkW6x8eh_EhBQuUDv1HvOEIgN__rfmTvm

**Comment by Wqttzicue** [comment]
> I created a signal group
> https://signal.group/#CjQKIDZSEtPaazDWchj6InlpvN7Mi8Wbksa2YKUQkW6x8eh_EhBQuUDv1HvOEIgN__rfmTvm

Signal is paranoids thing

**Comment by 25huizengek1** [comment]
Thank you, @Wqttzicue. Let's keep this in one thread ==> #460
I kinda became distracted from this because of the fuzz around YouTube blocking requests here and there.

@muraikrishna239 Please don't create issues about this. These should be about the software itself.

**Comment by muraikrishna239** [comment]
Sir vi tune unable to play song showing this video is deleted
