### ISSUE TITLE
Music Player Widget!

### ISSUE THREAD

**Issue by Kimiberlianoputra** [25huizengek1/ViTune#519]
## Feature request: Make widget for this apk (if possible)

So I recently make a KWGT widget for this apk and thinking: hm... since the community still active and there's a issue that solved in millisecond by great developers (thanks!) Why don't build a widget for it? :3

**Comment by Wqttzicue** [comment]
Copy of #348

**Comment by 25huizengek1** [comment]
Duplicate of #348
