### ISSUE TITLE
It shows "The returned video ID doesn't match the requested one" 

### ISSUE THREAD

**Issue by Melvinfused** [25huizengek1/ViTune#520]
### Steps to reproduce the bug

I created a playlist on YT Music & made it public
Then pasted the link on ViTune Search (playlist)it said open playlist,
After that when I play from that playlist it says "The returned video ID doesn't match the requested one". 
![Screenshot_2024-10-26-09-57-58-230_app vitune android](https://github.com/user-attachments/assets/9fc490b0-0645-4d73-8eac-50675e5856f9)

### Expected behavior

It should just play the music from the playlist. 

### Actual behavior

It doesn't play from this & some other playlists that used to work.
Plays the tracks when played from outside the playlist
BTW the playlist doesn't show up when I search the name "Mach Rock"  [https://music.youtube.com/playlist?list=PL6ZtjggQcyrJXxwx4rEoyze3DKLLxM-d6&si=g0qtUIOP9YjUacYR](url)

### ViTune version

1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

I'm using Poco M2 Pro

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
UTFA. Update app - this will solve it

**Comment by 25huizengek1** [comment]
Thank you @Wqttzicue, it has been fixed.

That said, I do want to note that, as pointed out in the bug report form, you should update to the latest version first before creating a bug report.

**Comment by Wqttzicue** [comment]
> Thank you @Wqttzicue, it has been fixed.
> 
> That said, I do want to note that, as pointed out in the bug report form, you should update to the latest version first before creating a bug report.

Make checkbox instead, like "I have latest version of ViTune"
