### ISSUE TITLE
JSON playlist sharing

### ISSUE THREAD

**Issue by Wqttzicue** [25huizengek1/ViTune#521]
## Feature request: ...

Perviously in #480 i suggested using links.
This time i suggest using json files as playlist sharing way, as it done in Nuclear Player.

 So you just go into your playlist, press "Export"
 And other guy presses "Import" chooses file with playlist, and gets it in his playlists tab.

Also its good way to backup playlists

**Comment by 25huizengek1** [comment]
@Wqttzicue Thank you for the ideas, I prefer to keep everything in one issue (#476) though, so I'll close this one.
