### ISSUE TITLE
Where?

### ISSUE THREAD

**Issue by Popka588bobik** [25huizengek1/ViTune#523]
Why can't I download some songs? (No button)

![Screenshot_2024-10-26-21-07-26-908_app vitune android](https://github.com/user-attachments/assets/59260c89-6fbd-4cc5-a9b0-d42b2a3eeb13)

**Comment by Wqttzicue** [comment]
Ну бля, YTM не имеет возможности скачать песню...
Для этого нужно имплементировать savefromnet  в плеер. И то песни сохраняются в кэше

**Comment by MLGHerobrine** [comment]
ViTune uses cache, and does not have "downloads".

**Comment by Wqttzicue** [comment]
> ViTune uses cache, and does not have "downloads".

Btw MLG do you use discord? I just made unofficial one for ViTune, id like to see active contributors/issues answerers in there.

**Comment by 25huizengek1** [comment]
If the song is already cached, the download icon disappears. I thought the UI is cleaner that way.
