### ISSUE TITLE
A new bug similar to requested Id doesn't match

### ISSUE THREAD

**Issue by Jarletoss** [25huizengek1/ViTune#532]
### Steps to reproduce the bug

Play song imported fromp previous save or in general

### Expected behavior

Song should play normally after bug fix

### Actual behavior

Some songs do play normally, even videos, some songs don't play, but it doesn't show an error, they're just frozen at 0 seconds elapsed without starting. 

### Screenshots/Screen recordings

![Screenshot_20241029_011747_app vitune android](https://github.com/user-attachments/assets/32abd37d-e70f-4db3-b735-35d8ea60e09e)

### ViTune version

1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

I am using a Huawei p40 lite
OS build is emui 12

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
As I said earlier in #499, ViTune still won't be able to play all songs, unfortunately. It does try to play it anyway by impersonating a lot of YouTube clients (and now that I think of it, I guess I should add exponential backoff, but oh well) before showing an error, and depending on your internet connection, this may take a while, so the error doesn't show (yet).
