### ISSUE TITLE
Feature request: change song metadata

### ISSUE THREAD

**Issue by LogicForg** [25huizengek1/ViTune#533]
Let us rename songs , change album covers and their artists for customisation, specially in local files.

I hope you all can implement this feature , would be real thankful 🙏🙏

**Comment by Wqttzicue** [comment]
I Like that! I hope ingek will implement this

**Comment by Monoxide8969** [comment]
I was sure this issue was a duplicate but apparently nobody has yet suggested it. That's great, I've wanted this feature for a long time

**Comment by LogicForg** [comment]
Can it be added in the next update 🥺👉👈

**Comment by Wqttzicue** [comment]
> Can it be added in the next update 🥺👉👈

No, this wont happen beacause this sugg isnt even on low:prio.

**Comment by 25huizengek1** [comment]
Duplicate of #308 (my bad, just doing this on my phone right now)
