### ISSUE TITLE
Speed and Pitch Upgrade

### ISSUE THREAD

**Issue by JondyGems** [25huizengek1/ViTune#536]
The thing about speed and pitch is that it would be great to have it locked. Adding a button to lock both to offer a choice is a great solution in my opinion.

Also having quick access to this setting, by holding down the play/pause button would be esspecialy amazing.

**Comment by 25huizengek1** [comment]
Why add a lock button when you can just, not touch the sliders? This would overcomplicate the UI. I don't think this is a good idea.
