### ISSUE TITLE
Good afternoon. I'm sure, but it still goes out. RiMusic, for example, has a different mechanism of screen timeout and it works 100%. Thank you.

### ISSUE THREAD

**Issue by Wind092** [25huizengek1/ViTune#540]
Good afternoon. I'm sure, but it still goes out. RiMusic, for example, has a different mechanism of screen timeout and it works 100%. Thank you.

_Originally posted by @Wind092 in https://github.com/25huizengek1/ViTune/issues/528#issuecomment-2446395342_

**Comment by 25huizengek1** [comment]
Duplicate of #540. Please don't create separate issues to try to 'grab' my attention. Thank you.
