### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by AverageAndroidUser21** [25huizengek1/ViTune#542]
## Feature request: ...
Hi so I'm sorry if this isn't a feature request, I couldn't find another way to contact you but I'd love to know what font you use for the app, and is there any way I can download it and use it on my device? Thank you for the app its one of the best apps I've used in a long time

**Comment by andietablante18** [comment]
Hey there. If you go the settings, on the appearance section, there is “Font.” After clicking “Font”, you will see the various fonts available and in used within the application. If you wish to download and use the font as your system font, you first have to search the font’s name on the internet and find a download file of it. After that, find a video tutorial on YouTube that gives you a step-by-step guide on how to use the downloaded font as your system font.

**Comment by 25huizengek1** [comment]
@AverageAndroidUser21 What @andietablante18 said. By default ViTune uses Poppins (free to download from fonts.google.com)
