### ISSUE TITLE
After searching twice consecutively, back button goes to previous search rather than home screen

### ISSUE THREAD

**Issue by HudsonKnott** [25huizengek1/ViTune#548]
### Steps to reproduce the bug

1. Open the app to the home screen and search for something
2. After the search results appear, tap on the top bar where your search query is displayed to search again
3. Input a new query
4. Press the back button

### Expected behavior

In older versions of the app, the back button, no matter how many consecutive searches had been done, would take you back home. Not sure if this is intended behaviour - if it is then perhaps a separate home button would be a good idea so I don't have to flick through several pages of searches to return.

### Actual behavior

When clicking the back button, I am brought to my previous search, rather than to the home screen. This means I have to click the back button many times to return home after a few consecutive searches.

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Samsung Galaxy S21, One UI

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by genericbetatester** [comment]
Yup, can confirm this. I reckon it's not a bug rather the devs thought it makes more sense to go back to the last page which I agree but then, it becomes really annoying when you have searched for so many songs and you have to click so many times before getting back home.

**Comment by 25huizengek1** [comment]
Yup, this is intended. I guess navigation will always be imperfect. I personally like it better this way. I guess it's not a big deal since you can always just close the app entirely and re-open it? But correct me if I'm wrong though.
