### ISSUE TITLE
Make the queue collapse button centered 

### ISSUE THREAD

**Issue by mpekurin** [25huizengek1/ViTune#549]
It would be nice to have the queue collapse button in the center of the screen, simply for aesthetic reasons. Currently it's centered between the buttons that have different width so it's always slightly shifted:
![Screenshot_20241104-150328](https://github.com/user-attachments/assets/0b04a1ac-236f-48ca-9727-3369f23826cd)

For instance, how it was in ViMusic:
![Screenshot_20241104-151042](https://github.com/user-attachments/assets/1783ed6f-b037-4b22-b4c4-95562bad939c)

**Comment by habnixzutun** [comment]
Would cause problems with other languages. For example with german

![Screenshot_2024-11-05-20-12-33-322_app vitune android-edit](https://github.com/user-attachments/assets/422e2e05-cab7-4338-9fbc-abad9e547870)

**Comment by 25huizengek1** [comment]
It's perfectly centered, and since the app has translations/support for different screen sizes/support for different text sizes, I unfortunately cannot do anything about it.
