### ISSUE TITLE
the returned video id doesn't match the requested one

### ISSUE THREAD

**Issue by maxitflo** [25huizengek1/ViTune#552]
### Steps to reproduce the bug

I simply played a song

### Expected behavior

The song should play

### Actual behavior

Instead the song didn't play and a message popped up that said "the requested video id doesn't match the requested one"

### Screenshots/Screen recordings

![Screenshot_2024-11-05-08-19-22-80_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/39b96b04-4e11-402e-ac0d-351389ead04c)

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

I am using an Oppo Reno 2, running stock Android 11

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by ganairm** [comment]
search for the song to play it instead of playing uncached song in your library

**Comment by 25huizengek1** [comment]
@maxitflo Unfortunately sometimes songs get re-released on YouTube Music, which we cannot detect. Please search again for the song in order to play the newer version.
