### ISSUE TITLE
The 'returned video ID doesn't match the requested one' issue

### ISSUE THREAD

**Issue by akashk0712** [25huizengek1/ViTune#558]
### Steps to reproduce the bug

1. Whenever I try to play a song, the issue 'returned video ID doesn't match the requested one' issue pops up in the album image

### Expected behavior

The requested song should play when it is tap upon

### Actual behavior

The son doesn't plays. Instead the 'returned video ID doesn't match the requested one' issue persists

### Screenshots/Screen recordings

![Screenshot_2024-11-09_22-42-36](https://github.com/user-attachments/assets/62a01682-797f-4fe5-bae7-9adbdc60a649)

### ViTune version

1.0.8

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

I am using Nokia 5.4 based on Android 12 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
@akashk0712 Already solved, please update your ViTune to the [latest version](https://github.com/25huizengek1/ViTune/releases/latest)
