### ISSUE TITLE
Add login to YouTube music and sync playlist 
Add import playlist
Add 

### ISSUE THREAD

**Issue by abdalftah193** [25huizengek1/ViTune#565]
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by Wqttzicue** [comment]
Already suggested, this **WON'T** happen.

**Comment by abdalftah193** [comment]
Why?

**Comment by Wqttzicue** [comment]
> Why? 

ViTune is more privacy orientated player, and integrationf of googöe services will completely ruin it and also this will mean ads in music.

ViTune uses Piped Api instead of Youtube.

**Comment by abdalftah193** [comment]
Also you can add features from the ri Music application such as adding a playlist from YouTube through a link

**Comment by Wqttzicue** [comment]
> Also you can add features from the ri Music application such as adding a playlist from YouTube through a link

Such thing is already suggested, and its accepted someway

**Comment by 25huizengek1** [comment]
Duplicate of #199
