### ISSUE TITLE
Implement option to disable unnecessary tabs/button

### ISSUE THREAD

**Issue by max5354** [25huizengek1/ViTune#566]
It will be great if you implement option to disable some unnecessary option/tab according to users need/taste you can add one option/feature that disable some options like LIKE BUTTON, START RADIO, GO TO ALBUM, MORE FROM ARTIST, ADD TO BLOCK LIST, DISCOVER (TAB) , ALBUM (TAB), ARTIST ( TAB) etc.......plz add this one option to disable most of unnecessary option i hope you understand and implement this...

**Comment by Wqttzicue** [comment]
Well, this may have place

**Comment by max5354** [comment]
> Well, this may have place

Thanks for accepting my request....also any ETA of this feature?

**Comment by genericbetatester** [comment]
Tabs can be disabled if you press and hold on them. Using the "modern" theme you can choose to hide the like button on player screen

**Comment by 25huizengek1** [comment]
> > Well, this may have place
> 
> Thanks for accepting my request....also any ETA of this feature?

@max5354 To clarify: @Wqttzicue was just commenting on this. I'm the actual maintainer of this.

That said, it's implemented. Simply press and hold any tab in a tab row in order to hide tabs.
