### ISSUE TITLE
Audio Adjustment Controls for Reverb, Tempo, and Bass

### ISSUE THREAD

**Issue by itssagnikmukherjee** [25huizengek1/ViTune#569]
I would like to request a feature that enables users to adjust the reverb, tempo, and bass of audio tracks, similar to the current controls for speed and pitch. This enhancement would provide a richer, more customizable listening experience, particularly beneficial for users who enjoy lo-fi music. The ability to fine-tune these settings will help listeners tailor audio playback to their preferences, creating an immersive experience.

**Comment by genericbetatester** [comment]
Tbh I don't even get why we have speed and pitch settings, it's a music player not a DAW let's keep it that way. That said, there are reverb and bass adjustments in settings, so check that out.

**Comment by 25huizengek1** [comment]
@genericbetatester Making my point for me. I fully agree. These settings already exist and have their own places within the app.
