### ISSUE TITLE
Implement BOOKMARK feature in playlists

### ISSUE THREAD

**Issue by max5354** [25huizengek1/ViTune#573]
It will be great if you implement bookmark playlist feature.  Every time we need to search and find playlist to play songs but if you implement bookmark button in playlists so we can bookmark playlist also we can easily access playlists instead of searching it.....

**Comment by genericbetatester** [comment]
![Screenshot_20241115-111518](https://github.com/user-attachments/assets/6e55d71d-7349-47d4-b56f-ab7900ce875b)
Wdym bro, your words are not clear. You can save playlists using the "+" button I highlighted above. It gets saved to the "playlist" tab.

**Comment by max5354** [comment]
> ![Screenshot_20241115-111518](https://private-user-images.githubusercontent.com/140274753/386556115-6e55d71d-7349-47d4-b56f-ab7900ce875b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzQxMzAsIm5iZiI6MTczMTY3MzgzMCwicGF0aCI6Ii8xNDAyNzQ3NTMvMzg2NTU2MTE1LTZlNTVkNzFkLTczNDktNDdkNC1iNTZmLWFiNzkwMGNlODc1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxMjMwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDE3Y2FjNGE3ZTViY2MxZGVkMmUwNWNkMzljMjk2ZjY0ZmI5NDQyMTYwYWYzNDUwMDZhOWJkMDkzZjk5MDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PJd2JL1cvMA6dEj7qd2fjBULa7GR747dkjylgCmF9ww) Wdym bro, your words are not clear. You can save playlists using the "+" button I highlighted above. It gets saved to the "playlist" tab.

Ohk ohk sorry bro it's my fault.....i got that feature i am deleting this issue right now...
