### ISSUE TITLE
start radio

### ISSUE THREAD

**Issue by fanaH7** [25huizengek1/ViTune#575]
I'm suggesting to make the "start radio" to change the playlist. make it random. same function like yt music's start radio button. it change the playlist when the "start radio" button been hit

![Screenshot_20241118-180413](https://github.com/user-attachments/assets/bcc13cef-7c10-464d-a2c8-ae869cce5ba5)

**Comment by Wqttzicue** [comment]
Uhhh, its already, it is on the screenshot, innit?

**Comment by fanaH7** [comment]
> Uhhh, its already, it is on the screenshot, innit?

yes, and it's function just like the shuffle button. l mean the "start radio" button should be functionally to make the whole playlist change, not reshuffle. make it play a different song that still related to currently song.


https://github.com/user-attachments/assets/fa2fe76e-4d41-407b-84a7-b50ad2f996f6

some of the song are changed and some aren't. it just my suggestion to make it more easier to play a different playlist everytime the song been playing

**Comment by Wqttzicue** [comment]
Ah, k, i never used that thing, lets just wait Ingek's response

**Comment by 25huizengek1** [comment]
You cannot start the radio for a local playlist, as there doesn't exist a radio for it.
