### ISSUE TITLE
Spanish (updated) and Catalan translations

### ISSUE THREAD

**Issue by elmees21** [25huizengek1/ViTune#578]
Hi, I have updated the values-es.xml and created values-ca.xml. Sorry for not opening a Pull Request, I don't know how to do it.

Spanish: [values-es.zip](https://github.com/user-attachments/files/17843991/values-es.zip)
Catalan: [values-ca.zip](https://github.com/user-attachments/files/17843989/values-ca.zip)

**Comment by 25huizengek1** [comment]
Great! I'll review this later. Thank you in advance for your help!

**Comment by 25huizengek1** [comment]
LGTM! Thank you for the translations!
