### ISSUE TITLE
A missing song 

### ISSUE THREAD

**Issue by SKQ-Official** [25huizengek1/ViTune#583]
### Steps to reproduce the bug

Hey, thanks for your efforts, Just wanted to let you know that I searched for YESSIR! by Rarin, not the remix tho, but it's not showing up. It seems like the system didn't pick it, just figured to let you guys know to identify the issue here. And thanks again for what you are doing here I really appreciate it

### Expected behavior

To be there

### Actual behavior

Not there

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

S24 ultra 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment]
![Screenshot_20241124_022154.png](https://github.com/user-attachments/assets/95a1a942-647c-4411-af3f-1f10108c8864)

Use "Videos" instead tho, and i have no idea why it dont exist, probably Piped issue.

**Comment by 25huizengek1** [comment]
@Wqttzicue You keep saying ViTune uses Piped, but while this has been the case for streaming only, ViTune doesn't rely on Piped anymore. Only when you log in with Piped you can see your playlists, but that's it.

Nonetheless, this song hasn't properly been published to YouTube Music, so it won't appear. There is nothing we can do about that. I recommend just listening to the music video.

**Comment by Wqttzicue** [comment]
> @Wqttzicue You keep saying ViTune uses Piped, but while this has been the case for streaming only, ViTune doesn't rely on Piped anymore. Only when you log in with Piped you can see your playlists, but that's it.
> 
> Nonetheless, this song hasn't properly been published to YouTube Music, so it won't appear. There is nothing we can do about that. I recommend just listening to the music video.

Ah k, ill remember
