### ISSUE TITLE
Requesting a Feature for ViTune

### ISSUE THREAD

**Issue by Aqua-X7** [25huizengek1/ViTune#592]
## Feature request: 

Allow us to customise our own playlist like: Changing their thumbnail (from our own custom image), descriptions for that Playlist, etc.

**Comment by Wqttzicue** [comment]
Already suggested

**Comment by Wqttzicue** [comment]
Btw @25huizengek1 please add Desync button to plsylists, cuz i saved sone playlist from ytm and i removed and added some songs, but after some time it just synced back to original, so annoying.

Or desync playlist if you edited it somehow.

**Comment by 25huizengek1** [comment]
Duplicate of #533
