### ISSUE TITLE
the downloads are automaticcy deleted 

### ISSUE THREAD

**Issue by soham99302** [25huizengek1/ViTune#593]
### Steps to reproduce the bug

i downloaded all the songs from history tab .they stayed this day and now they are gone from cache 

### Expected behavior

the songs should stay in the offline sections ie downloads 

### Actual behavior

they are auto deleted even if i updated the app settings to .turned off the pause app if unused ( ie clear cache if unused ) 

### Screenshots/Screen recordings

![Screenshot_2024-11-27-23-05-38-80_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/b8527552-9d1c-49b6-a64a-14b178588771)
![Screenshot_2024-11-27-23-05-32-69_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/d5eb72e3-7314-4777-a730-9bc2873ed7b1)

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using realme c55 

### Upstream reproducibility

don't know vi music is alredy discontinued this happens with vitune

### Additional information

i turned off the setting to auto clear cache if app is unused it is not working 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Actucutel** [comment]
I have the same bug, I have downloaded all the songs 3 times and the 3 times and within hours they are all deleted, even when I'm using the app

**Comment by Spandan122008** [comment]
The same also happening for me I am downloading the songs and the songs are getting deleted automatically and even cannot play the music as it's saying 'an unknown playback error has occurred' and after pausing the music and then starting again it starts

**Comment by 25huizengek1** [comment]
See: https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501, https://github.com/25huizengek1/ViTune/issues/379#issuecomment-2211387359
