### ISSUE TITLE
Feature Request for ViTune

### ISSUE THREAD

**Issue by nathn01** [25huizengek1/ViTune#594]
Hey, i was wondering if you could add like some sort of indicator that shows if we have downloaded/cached the songs,
like a small gray dot next to the title of the song then it would light up as soon as you have downloaded the song that u wanted.

I also suggest that if you could add something that tells us how many songs we have already downloaded in a playlist like 
"28 out of 30 songs downloaded", you can put this after we pressed the three dots on the playlist.

Thank you.

**Comment by 25huizengek1** [comment]
Duplicate of #531
