### ISSUE TITLE
Addition Song from device 

### ISSUE THREAD

**Issue by Simarsahota** [25huizengek1/ViTune#599]
## Feature request: ...

A clear and concise description of the feature you want to request.
I Need To Add Some Song which Ai Generated in Sidhu moose wala Voice . Please Add Feature To Add Download Song in Vi tune Playlist.

**Comment by Simarsahota** [comment]
Please Add Feature in Vi tune To Add New Song From Device

**Comment by 25huizengek1** [comment]
Go to the Local tab in the bottom-left corner of your screen. Local songs can be played/added to playlists from there.
