### ISSUE TITLE
Facing an unknown error after every song 

### ISSUE THREAD

**Issue by Pradee-ui** [25huizengek1/ViTune#600]
### Steps to reproduce the bug

We cannot hear to the song in locked screen

### Expected behavior

Suddenly the songs are paused 

### Actual behavior

This should not work like that
![Uploading Screenshot_20241129_221539.jpg…]()

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Iqoo Z7S 5G

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Please fill out the form correctly. I don't know what the issue is/what is going wrong.

**Comment by 25huizengek1** [comment]
@Pradee-ui Also, please wait before submitting until your uploads are finished, because your screenshot didn't get through.

**Comment by Pradee-ui** [comment]
Ohhh sorry about that😔
