### ISSUE TITLE
vi tune is not supporting for Android 5.1.1 which version of vi tune will support

### ISSUE THREAD

**Issue by farookhamdan** [25huizengek1/ViTune#602]
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by 25huizengek1** [comment]
ViTune does support Android 5. Please let me know if there are any compatibility issues though.

**Comment by farookhamdan** [comment]
after I'm installing it...the application is not opening it shows the
unfortunately vi tune is stopped

what should i do

**Comment by 25huizengek1** [comment]
Please try to record your screen / get some logs. I'll test this on a virtual device later.
