### ISSUE TITLE
Diffuse support

### ISSUE THREAD

**Issue by lolstijl** [25huizengek1/ViTune#612]
Could you please if possible add support for the diffuse app. Diffuse is a live wallpaper app that changes to the album art of the song that's currently playing but sadly vitune is not supported.
I understand if this is something only the diffuse app developers can fix but I'm not sure how this works so I wanted to ask anyway.

I love ViTune so keep up the good work!

**Comment by 25huizengek1** [comment]
Apparently, Diffuse queries for `ACTION_MUSIC_PLAYER` (which is not a real action). I'll add that to the manifest.

**Comment by lolstijl** [comment]
Might be an old action because diffuse hasn't been updated in like 5 years.

**Comment by lolstijl** [comment]
Could you maybe send me a pre-release with this change please?
