### ISSUE TITLE
Offline songs dissapering

### ISSUE THREAD

**Issue by Aakira-dot** [25huizengek1/ViTune#619]
### Steps to reproduce the bug

1. Listen to songs
2. Song gets saved
3. After some days/time
4. Offline songs and cache is cleared

### Expected behavior

Song should be saved as long as cache is not cleared by me

### Actual behavior

Song and cache is cleared

### ViTune version

v1.1.1-RELEASE

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

15

### Device info

Im using samsung A53 5g
One UI 6.1

### Additional information

Was gonna listen to some tunes in collage and i see that my offline song aint there happed 4 times after that so i re downloaded it and i has happned once again

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
See: https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501, https://github.com/25huizengek1/ViTune/issues/379#issuecomment-2211387359
