### ISSUE TITLE
Elvis

### ISSUE THREAD

**Issue by Elvisgarzon** [25huizengek1/ViTune#624]
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by Elvisgarzon** [comment]
Hello

**Comment by Wqttzicue** [comment]
Nah, Best fq I ever red

**Comment by 25huizengek1** [comment]
@Elvisgarzon What are you trying to do? I see you filed this issue ticket right after joining GitHub. Was this an accident? If so, I could delete this if you want.

**Comment by 25huizengek1** [comment]
Closing this for now. Please reopen this or get in touch at development@vitune.app if there are any further concerns.
