### ISSUE TITLE
Bass Frequency Equalizer Feature Request

### ISSUE THREAD

**Issue by MimirHim** [25huizengek1/ViTune#628]
Vitune should include a feature that allows users to adjust the bass frequency of a song, similar to how the pitch slider currently functions. This would enhance the overall audio customization experience.

**Comment by 25huizengek1** [comment]
That is just not possible (I'm not an audio expert, but I found [a similar thread on the Audacity forums](https://forum.audacityteam.org/t/changing-what-level-hertz-bass-hits-at/37747), so please read something like that if you want to learn more from the audio guys). It is up to the producer of a song, I guess? You could always open up the equalizer using the three dots in the bottom-right corner of the player screen.
