### ISSUE TITLE
pre cache

### ISSUE THREAD

**Issue by nathn01** [25huizengek1/ViTune#629]
idrk if this is a bug or something but can you make the Pre-Cache feature download only the specific playlist?

like when i use the pre-cache feature, it must download the songs only on that playlist, not downloading the songs outside of it, same goes for when downloading a certain album.

Thanks

**Comment by 25huizengek1** [comment]
You can download playlists, albums, or individual songs by just tapping the icon. An album/playlist can be downloaded using the icon at the top-right (it disappears if all songs are pre-cached), individual songs by pressing and holding a song and tapping 'Pre cache'. If you want to save an album/playlist, tap the bookmark/plus icon to save it locally.
