### ISSUE TITLE
Unknown playback error 

### ISSUE THREAD

**Issue by ShauryaPratapSingh070408** [25huizengek1/ViTune#631]
There's an unknown playback error due to which the music gets stopped any time.![Screenshot_2024-12-15-14-20-58-40_c41d99f29ddb98f2b2d1f5dfe2e7da20.jpg](https://github.com/user-attachments/assets/bf89a59a-ce9b-405a-8fac-466257d98a32)

``

**Comment by 25huizengek1** [comment]
Duplicate of #553
