### ISSUE TITLE
Hi.i really liked your app,can you make the look of player more like yt music

### ISSUE THREAD

**Issue by Blhhamza** [25huizengek1/ViTune#633]
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by DaniloPedrazzi** [comment]
The player could be more like yt music if you change the apperance of it to `Classic` in the settings:

`Settings > Apperance > Player > Player Layout`

**Comment by 25huizengek1** [comment]
> The player could be more like yt music if you change the apperance of it to `Classic` in the settings:
> 
> `Settings > Apperance > Player > Player Layout`

@Blhhamza Closing as completed.
