### ISSUE TITLE
Yearly wrapped(like spotify) and/or in depth analysis

### ISSUE THREAD

**Issue by Sumdhe** [25huizengek1/ViTune#637]
Hello i thought it would be pretty cool if we had a yearly wrapped like that of spotify and/or in depth analysis (yearly monthly weekly etc)

**Comment by Wqttzicue** [comment]
This feature is already planned. Have you checked your suggestion for originality?

**Comment by DaniloPedrazzi** [comment]
See the start #615 and the work done on this feature #621.

Feel free to contribute with ideas!

**Comment by Sumdhe** [comment]
> This feature is already planned. Have you checked your suggestion for originality?

Ah my bad, im not a github user i just created this account for suggesting this idea really sorry about that, thank you for your reply!

**Comment by Sumdhe** [comment]
> See the start #615 and the work done on this feature #621.
> 
> Feel free to contribute with ideas!

Thank you very much i appreciate it
