### ISSUE TITLE
Slow download 

### ISSUE THREAD

**Issue by Shubham315417** [25huizengek1/ViTune#639]
when I download song it take too much time

**Comment by 25huizengek1** [comment]
@Shubham315417 Can you please file [a proper bug report](https://github.com/25huizengek1/ViTune/issues/new?assignees=&labels=bug&projects=&template=bug_report.yaml) that describes the issue you are having? Maybe this has something to do with your internet connection, or this is actually a bug on ViTune's part. Without the right information (or, in this case, any information at all) I can't do something about the issues you are experiencing.
