### ISSUE TITLE
Music paused when notification comes or volume on 0%

### ISSUE THREAD

**Issue by dxhanzz0** [25huizengek1/ViTune#642]
### Steps to reproduce the bug

1. Play music
2. Set volume to 0% or notification comes

### Expected behavior

Music still playing

### Actual behavior

Music stop or pause

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using vivo v27, running funtouch os

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by ganairm** [comment]
that's a feature i think

**Comment by 25huizengek1** [comment]
Not a bug. This is intentionally implemented by me.
