### ISSUE TITLE
Storing songs

### ISSUE THREAD

**Issue by PorkSiomai** [25huizengek1/ViTune#643]
I want to request where when I clear cache the app, the songs I downloaded would not be remove/delete from offline unless I click the clear data on the app
![Screenshot_20241218-150306](https://github.com/user-attachments/assets/93625871-6de0-4208-bf88-361d205587de)

**Comment by OutshineIssue** [comment]
I would rather not. Data is data, cache is cache, and saved songs are part of the cache.

**Comment by 25huizengek1** [comment]
@PorkSiomai ViTune doesn't delete cache: see: https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501, https://github.com/25huizengek1/ViTune/issues/379#issuecomment-2211387359
