### ISSUE TITLE
Please add a download option it will be a big help if you did that I maybe helpful in some language translation like malayalam and Hindi other than that nothing

### ISSUE THREAD

**Issue by Athullost** [25huizengek1/ViTune#647]
## Feature request: ...

A clear and concise description of the feature you want to request.
I want an option for downloading songs so that I can listen to them offline and enjoy it.

**Comment by 25huizengek1** [comment]
Already implemented. Songs get cached automatically when you listen to them. If you want to cache a song without listening to it, tap 'Pre cache' next to a song/after pressing and holding a song.
