### ISSUE TITLE
Albums not displaying all songs 

### ISSUE THREAD

**Issue by Mexiater** [25huizengek1/ViTune#648]
### Steps to reproduce the bug

-open a saved album 
-some songs may be missing 

### Expected behavior

Have a list of all the songs on the album 

### Actual behavior

Some songs may be missing from the list

### Logs

![Screenshot_20241219-143047](https://github.com/user-attachments/assets/a0760db5-df0f-42ee-8f50-6b138527c422)
![Screenshot_20241219-143115](https://github.com/user-attachments/assets/bf6248bb-e925-4625-9698-ea60d04dce5a)

In this case "Auntie Dairies" is missing, and it plays completely fine when searched up on the app.

### ViTune version

V1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14 and 15

### Device info

Happened on a Redmi note 8 and on a Nothing 2a plus

### Additional information

This started to happen after the whole YouTube Api thing, some songs started to disappear from albums even though they are completely playable when searched. The issue persisted even after changing phone, since I let google cline the app between from the old to the new phone.

### Checklist

- [x] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Not a bug. When you hide a song, your device doesn't know about it anymore. This means albums do not/cannot show said song anymore.

**Comment by Mexiater** [comment]
Problem is the song is not hidden at all. I never delisted it from ever appearing.

**Comment by Mexiater** [comment]
And it shows up when searched.
