### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by MaazSiddiquiCS** [25huizengek1/ViTune#652]
### Steps to reproduce the bug

Open Vitune played a music

### Expected behavior

Music should play with or without VPN

### Actual behavior

I have to use VPN to play music 

### ViTune version

V1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using Redmi 12

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
@MaazSiddiquiCS Did you check off the checklist without reading? You clearly can't reach YouTube from your own network.
