### ISSUE TITLE
Offline music download problem 

### ISSUE THREAD

**Issue by MananPadhiyar03** [25huizengek1/ViTune#657]
### Steps to reproduce the bug

Download music or pre cache problem some time's it's work , but some time not and music playing problem stop automatic 

### Expected behavior

Download music or pre cache problem some time's it's work , but some time not and music playing problem stop automatic 

### Actual behavior

Download music or pre cache problem some time's it's work , but some time not and music playing problem stop automatic 

### Screenshots/Screen recordings

Download music or pre cache problem some time's it's work , but some time not and music playing problem stop automatic 

### Logs

.

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Vivo 1806

### Upstream reproducibility

.

### Additional information

.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
@MananPadhiyar03  I don't understand any of this. Please file a proper bug report.
