### ISSUE TITLE
No. Of Views on song

### ISSUE THREAD

**Issue by Keshab8108** [25huizengek1/ViTune#663]
## Feature request: ...

A clear and concise description of the feature you want to request.

Few days before i used the Vimusic app but I have recently switched to the vitune app. But here i have not seen the views of the song. Because that was very useful information on every song side. That helps to identify the popular songs among the long list of songs. So vitune team should consider integrating that field of information on the side of the song.

**Comment by 25huizengek1** [comment]
@Keshab8108 This was an inconsistency in ViMusic that I removed. It showed the view count only when searching for a song, for some specific songs. This data is not available for every song at any moment, so I cannot implement this myself. If YouTube Music decides to change this behavior, I'll reconsider.
