### ISSUE TITLE
Playlist & Album details

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#82]
## Feature request: Playlist & Album details

Albums could show information about them, how many songs, total duration and the release year, This could also apply to playlists

Album [ (Title Album) \n (Author), (Year) \n (Total songs) • (Total duration) ]  
Playlist [ (Title Playlist) \n (Total songs) • (Total duration) ]

![Screenshot_20240118-163855](https://github.com/25huizengek1/ViMusic/assets/1917871/35f18a5a-b690-44d6-878f-a4a975e9fda4)![Screenshot_20240118-164000](https://github.com/25huizengek1/ViMusic/assets/1917871/b99e816d-830d-4e60-957d-ad2eea833b87)
![Screenshot_20240118-164044](https://github.com/25huizengek1/ViMusic/assets/1917871/2c9c9405-896d-447a-a96f-4c3a9c7ce599)

**Comment by 25huizengek1** [comment]
Good idea, will schedule for implementation.

**Comment by dtomvan** [comment]
+1 Although the extra title would be redundant, wouldn't it?

**Comment by dtomvan** [comment]
Alright, then we can have an extended title on overflow I guess.

**Comment by 25huizengek1** [comment]
I guess I can just handle the titles the same way as in the player, with the fading edges instead of ellipsis?

**Comment by 25huizengek1** [comment]
Added, it looks like this now:
![image](https://github.com/25huizengek1/ViMusic/assets/50515369/ff168bb2-7b66-442c-b79f-ac53d4444645)

**Comment by Syntax-Err5** [comment]
Hey, I'm on the nightly build and just wanted to point out that the album synopsis takes up a lot of space on some albums (see screenshot).

Maybe we could have it so that it's shortened with fading edges and expands when the user touches it? 

![IMG_20240224_174725](https://github.com/25huizengek1/ViMusic/assets/123362106/0020990a-a97a-4fd1-b260-ec7869f2d294)

**Comment by 25huizengek1** [comment]
That is a good idea. I don't know what behavior is sensible in this case: should we only 'preview' the first line and use a fading edge after that?

This might even become a text measuring nightmare but who knows...

**Comment by Syntax-Err5** [comment]
>should we only 'preview' the first line and use a fading edge after that?

That sounds like a good idea

>This might even become a text measuring nightmare but who knows...

I guess it's worth a shot...

**Comment by vedxp** [comment]
Playlist details, as discussed above, will be helpful for saved playlists too.

> ![Screenshot_20240226-181120](https://github.com/25huizengek1/ViMusic/assets/87353286/9e56b2aa-4930-4d30-aeed-1414b62b6fe8)

**Comment by vedxp** [comment]
> Playlist details, as discussed above, will be helpful for saved playlists too.
> 
> > ![Screenshot_20240226-181120](https://private-user-images.githubusercontent.com/87353286/307790751-9e56b2aa-4930-4d30-aeed-1414b62b6fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzg2OTcsIm5iZiI6MTcxMDEzODM5NywicGF0aCI6Ii84NzM1MzI4Ni8zMDc3OTA3NTEtOWU1NmIyYWEtNDkzMC00ZDMwLWFlZWQtMTQxNGI2MmI2ZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NGY3ZTA1ZTUyNmQ1NTg1YTBiYzA4NzRhNGRmZjBiYmRiY2JlYTFiZjlhYjc3MDZlNTZkYjgwZWZiNWRmZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LCvb0RFgv88ZSJQTrQwvXVZ3kK8gHv7OiHF-aiaYFBE)

@25huizengek1 thoughts on adding this?

**Comment by vedxp** [comment]
> Playlist details, as discussed above, will be helpful for saved playlists too.
> 
> > ![Screenshot_20240226-181120](https://private-user-images.githubusercontent.com/87353286/307790751-9e56b2aa-4930-4d30-aeed-1414b62b6fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzE4NjUsIm5iZiI6MTcxMjE3MTU2NSwicGF0aCI6Ii84NzM1MzI4Ni8zMDc3OTA3NTEtOWU1NmIyYWEtNDkzMC00ZDMwLWFlZWQtMTQxNGI2MmI2ZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE5MTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMmM4ODc5ODI3YjU5ODM5MjNhNWI0YzBkMzYxNzE1ODFiMjEzYWVlODNmNDY5ZjAwM2E2YjhkYmMzNzg4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzgfd-VdXbXXHoIiWqu0yLaj0GIEKdkDf7SHawexaBo)

@25huizengek1 thoughts on implementing this?

**Comment by 25huizengek1** [comment]
#207
