### ISSUE TITLE
Album and artist precache

### ISSUE THREAD

**Issue by Erik-vdb** [25huizengek1/ViTune#93]
## Feature request: Album and artist precache

As of currently, there is only pre-cacehing for individual songs and playlists. It would be nice if said capability extended to albums and, more importantly, the artists themselves (downloading the whole song list from the artist).
 
Since the album and song list are pretty akin to a playlist, would it be possible to adapt the playlist pre-cache code into those pages?

**Comment by siggi1984** [comment]
> ## Feature request: Album and artist precache
> 
> As of currently, there is only pre-cacehing for individual songs and playlists. It would be nice if said capability extended to albums and, more importantly, the artists themselves (downloading the whole song list from the artist).
> 
> Since the album and song list are pretty akin to a playlist, would it be possible to adapt the playlist pre-cache code into those pages?

Yes, this function/extension would be really great.

**Comment by 25huizengek1** [comment]
For albums, this makes sense. But why would we want this feature for artists?

**Comment by Erik-vdb** [comment]
> For albums, this makes sense. But why would we want this feature for artists?

Well, personally I often wanted to just download the whole artist, mainly in some that, more soften than not, tend to release singles rather than albums. I.E.: Chiru-san, Mili, Geoxor, etc. In those cases I had to either dl each of their songs manually or make a playlist from queue, download the playlist and then delete it.
I only saw RiMusic trying to implement this, but it only downloads the first 5 songs from overview.

**Comment by 25huizengek1** [comment]
So pre-fetching should load the entire song list first? This is definitely possible, I think the pre-fetch button should be in the Songs tab for artists then?

**Comment by Erik-vdb** [comment]
> So pre-fetching should load the entire song list first? This is definitely possible, I think the pre-fetch button should be in the Songs tab for artists then?

Exactly! Although I would avoid making the songs start loading in the UI, since artists with a lot of years of trajectory and a ton of songs might suck the life out of low end devices (Grain of salt. I don't know the internal workings and optimizations of the app, I just have an LG Q60 and it sometimes lags, further testing might be needed).

**Comment by 25huizengek1** [comment]
Implemented. I decided to only add this to albums, since fetching all songs from a single artist is actually not reliably possible (in YouTube). Ratelimiting is probably also an issue.
